import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import pc from "picocolors";
import type { ZodType, ZodOptional, ZodTypeAny } from "zod";
import {
  type TableDescriptor,
  type ColumnDef,
  type SqlColumnType,
  type GenerateOptions,
  type ReverseRef,
  isTableDescriptor,
} from "./types.js";

/**
 * Map Zod type to SQL column type
 */
function zodToSqlType(zodType: ZodTypeAny): SqlColumnType | null {
  const typeName = zodType._def.typeName;

  switch (typeName) {
    case "ZodString":
      return { kind: "string" };
    case "ZodNumber":
      // Zod numbers are floats by default
      return { kind: "f64" };
    case "ZodBigInt":
      return { kind: "i64" };
    case "ZodBoolean":
      return { kind: "bool" };
    case "ZodDate":
      // Dates stored as i64 timestamps
      return { kind: "i64" };
    case "ZodUint8Array":
    case "ZodInstanceOf":
      // Assume instanceof Uint8Array
      return { kind: "bytes" };
    default:
      return null;
  }
}

/**
 * Unwrap ZodOptional to get the inner type
 */
function unwrapOptional(
  zodType: ZodTypeAny
): { inner: ZodTypeAny; optional: boolean } {
  if (zodType._def.typeName === "ZodOptional") {
    return {
      inner: (zodType as ZodOptional<ZodTypeAny>)._def.innerType,
      optional: true,
    };
  }
  return { inner: zodType, optional: false };
}

/**
 * Analyze a table's columns and return structured column definitions
 */
function analyzeTable(
  tableName: string,
  table: TableDescriptor,
  allTables: Map<TableDescriptor, string>
): ColumnDef[] {
  const columns: ColumnDef[] = [];

  for (const [colName, colValue] of Object.entries(table.columns)) {
    // Check if it's a table reference
    if (isTableDescriptor(colValue)) {
      const refTableName = allTables.get(colValue);
      if (!refTableName) {
        throw new Error(
          `Column "${colName}" in table "${tableName}" references an unknown table. ` +
            `Make sure the referenced table is included in generateSchema().`
        );
      }
      columns.push({
        name: colName,
        sqlType: { kind: "ref", table: refTableName },
        nullable: false,
        refTable: colValue,
      });
      continue;
    }

    // It's a Zod type - check if optional
    const { inner, optional } = unwrapOptional(colValue as ZodTypeAny);

    // Check if the inner type is a table reference (for z.optional(Table))
    if (isTableDescriptor(inner)) {
      const refTableName = allTables.get(inner as unknown as TableDescriptor);
      if (!refTableName) {
        throw new Error(
          `Column "${colName}" in table "${tableName}" references an unknown table. ` +
            `Make sure the referenced table is included in generateSchema().`
        );
      }
      columns.push({
        name: colName,
        sqlType: { kind: "ref", table: refTableName },
        nullable: true,
        refTable: inner as unknown as TableDescriptor,
      });
      continue;
    }

    // Regular Zod type
    const sqlType = zodToSqlType(inner);
    if (!sqlType) {
      throw new Error(
        `Column "${colName}" in table "${tableName}" has unsupported Zod type: ${inner._def.typeName}`
      );
    }

    columns.push({
      name: colName,
      sqlType,
      nullable: optional,
    });
  }

  return columns;
}

/**
 * Generate SQL CREATE TABLE statement
 */
function generateSql(
  tables: Map<string, { descriptor: TableDescriptor; columns: ColumnDef[] }>
): string {
  const lines: string[] = [
    "-- Generated by @jazz/schema",
    "-- DO NOT EDIT MANUALLY",
    "",
  ];

  for (const [tableName, { columns }] of tables) {
    lines.push(`CREATE TABLE ${tableName} (`);

    const colLines: string[] = [];
    for (const col of columns) {
      let sqlType: string;
      switch (col.sqlType.kind) {
        case "bool":
          sqlType = "BOOL";
          break;
        case "i64":
          sqlType = "I64";
          break;
        case "f64":
          sqlType = "F64";
          break;
        case "string":
          sqlType = "STRING";
          break;
        case "bytes":
          sqlType = "BYTES";
          break;
        case "ref":
          sqlType = `REFERENCES ${col.sqlType.table}`;
          break;
      }

      const nullable = col.nullable ? "" : " NOT NULL";
      colLines.push(`    ${col.name} ${sqlType}${nullable}`);
    }

    lines.push(colLines.join(",\n"));
    lines.push(");");
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Convert table name to PascalCase for TypeScript interface
 */
function toPascalCase(str: string): string {
  return str
    .replace(/[-_](\w)/g, (_, c) => c.toUpperCase())
    .replace(/^\w/, (c) => c.toUpperCase());
}

/**
 * Simple pluralization for table names (reverse collection names).
 * Handles common cases but not all English irregularities.
 */
function pluralize(str: string): string {
  if (str.endsWith("s") || str.endsWith("x") || str.endsWith("z") ||
      str.endsWith("ch") || str.endsWith("sh")) {
    return str + "es";
  }
  if (str.endsWith("y") && !["a", "e", "i", "o", "u"].includes(str[str.length - 2])) {
    return str.slice(0, -1) + "ies";
  }
  return str + "s";
}

/**
 * Build reverse references for all tables.
 *
 * For each table, find all other tables that have a ref pointing to it.
 * These become reverse relationships (one-to-many collections).
 */
function buildReverseRefs(
  tables: Map<string, { descriptor: TableDescriptor; columns: ColumnDef[] }>
): Map<string, ReverseRef[]> {
  const reverseRefs = new Map<string, ReverseRef[]>();

  // Initialize empty arrays for all tables
  for (const tableName of tables.keys()) {
    reverseRefs.set(tableName, []);
  }

  // Scan all tables for refs
  for (const [sourceTable, { columns }] of tables) {
    for (const col of columns) {
      if (col.sqlType.kind === "ref") {
        const targetTable = col.sqlType.table;
        const refs = reverseRefs.get(targetTable);
        if (refs) {
          refs.push({
            name: pluralize(sourceTable),
            sourceTable,
            sourceColumn: col.name,
            nullable: col.nullable,
          });
        }
      }
    }
  }

  return reverseRefs;
}

/**
 * Map SQL type to TypeScript type
 */
function sqlTypeToTs(sqlType: SqlColumnType, nullable: boolean): string {
  let tsType: string;
  switch (sqlType.kind) {
    case "bool":
      tsType = "boolean";
      break;
    case "i64":
      tsType = "bigint";
      break;
    case "f64":
      tsType = "number";
      break;
    case "string":
      tsType = "string";
      break;
    case "bytes":
      tsType = "Uint8Array";
      break;
    case "ref":
      tsType = "ObjectId";
      break;
  }
  return nullable ? `${tsType} | null` : tsType;
}

/**
 * Generate TypeScript types
 */
function generateTypes(
  tables: Map<string, { descriptor: TableDescriptor; columns: ColumnDef[] }>,
  reverseRefs: Map<string, ReverseRef[]>
): string {
  // First pass: determine which tables have refs or reverse refs (need Depth/Loaded types)
  const tablesWithRefs = new Set<string>();
  const tablesWithReverseRefs = new Set<string>();
  for (const [tableName, { columns }] of tables) {
    if (columns.some((c) => c.sqlType.kind === "ref")) {
      tablesWithRefs.add(tableName);
    }
  }
  for (const [tableName, refs] of reverseRefs) {
    if (refs.length > 0) {
      tablesWithReverseRefs.add(tableName);
    }
  }

  const lines: string[] = [
    "// Generated by @jazz/schema",
    "// DO NOT EDIT MANUALLY",
    "",
    "/** ObjectId is a 128-bit unique identifier (UUIDv7) represented as a Base32 string */",
    "export type ObjectId = string;",
    "",
    "/** Base interface for all Groove rows */",
    "export interface GrooveRow {",
    "  id: ObjectId;",
    "}",
    "",
  ];

  // Generate Depth types first (they reference each other)
  lines.push("// === Depth types (specify which refs to load) ===");
  lines.push("");
  for (const [tableName, { columns }] of tables) {
    const interfaceName = toPascalCase(tableName);
    const refColumns = columns.filter((c) => c.sqlType.kind === "ref");
    const tableReverseRefs = reverseRefs.get(tableName) ?? [];

    if (refColumns.length === 0 && tableReverseRefs.length === 0) {
      // No refs or reverse refs - empty depth type
      lines.push(`export type ${interfaceName}Depth = {};`);
    } else {
      lines.push(`export type ${interfaceName}Depth = {`);
      // Forward refs
      for (const col of refColumns) {
        const refInterfaceName = toPascalCase(
          (col.sqlType as { kind: "ref"; table: string }).table
        );
        lines.push(`  ${col.name}?: true | ${refInterfaceName}Depth;`);
      }
      // Reverse refs (arrays)
      for (const rev of tableReverseRefs) {
        const refInterfaceName = toPascalCase(rev.sourceTable);
        lines.push(`  ${rev.name}?: true | ${refInterfaceName}Depth;`);
      }
      lines.push("};");
    }
    lines.push("");
  }

  // Generate base types and Loaded types
  lines.push("// === Row types ===");
  lines.push("");

  for (const [tableName, { columns }] of tables) {
    const interfaceName = toPascalCase(tableName);
    const hasRefs = tablesWithRefs.has(tableName);
    const hasReverseRefs = tablesWithReverseRefs.has(tableName);
    const refColumns = columns.filter((c) => c.sqlType.kind === "ref");
    const tableReverseRefs = reverseRefs.get(tableName) ?? [];

    // Main interface (with ObjectId for refs, no reverse refs)
    lines.push(`/** ${interfaceName} row from the ${tableName} table */`);
    lines.push(`export interface ${interfaceName} extends GrooveRow {`);
    for (const col of columns) {
      const tsType = sqlTypeToTs(col.sqlType, col.nullable);
      lines.push(`  ${col.name}: ${tsType};`);
    }
    lines.push("}");
    lines.push("");

    // Insert type (omits id, refs can be ObjectId or loaded object)
    lines.push(`/** Data for inserting a new ${interfaceName} */`);
    lines.push(`export interface ${interfaceName}Insert {`);
    for (const col of columns) {
      const optional = col.nullable ? "?" : "";
      let tsType: string;

      if (col.sqlType.kind === "ref") {
        const refInterfaceName = toPascalCase(col.sqlType.table);
        tsType = `ObjectId | ${refInterfaceName}`;
        if (col.nullable) {
          tsType = `${tsType} | null`;
        }
      } else {
        tsType = sqlTypeToTs(col.sqlType, col.nullable);
      }

      lines.push(`  ${col.name}${optional}: ${tsType};`);
    }
    lines.push("}");
    lines.push("");

    // Loaded type with generic depth parameter
    if (hasRefs || hasReverseRefs) {
      lines.push(
        `/** ${interfaceName} with refs/reverse refs resolved based on depth parameter D */`
      );
      lines.push(
        `export type ${interfaceName}Loaded<D extends ${interfaceName}Depth = {}> = {`
      );
      lines.push("  id: ObjectId;");

      // Forward refs
      for (const col of columns) {
        if (col.sqlType.kind === "ref") {
          const refInterfaceName = toPascalCase(col.sqlType.table);
          const refHasRefs = tablesWithRefs.has(col.sqlType.table);
          const refHasReverseRefs = tablesWithReverseRefs.has(col.sqlType.table);
          const nullSuffix = col.nullable ? " | null" : "";

          // Generate conditional type based on depth spec
          lines.push(`  ${col.name}: '${col.name}' extends keyof D`);
          lines.push(`    ? D['${col.name}'] extends true`);
          lines.push(`      ? ${refInterfaceName}${nullSuffix}`);
          if (refHasRefs || refHasReverseRefs) {
            lines.push(`      : D['${col.name}'] extends object`);
            lines.push(
              `        ? ${refInterfaceName}Loaded<D['${col.name}'] & ${refInterfaceName}Depth>${nullSuffix}`
            );
            lines.push(`        : ObjectId${nullSuffix}`);
          } else {
            lines.push(
              `      : D['${col.name}'] extends object`
            );
            lines.push(`        ? ${refInterfaceName}${nullSuffix}`);
            lines.push(`        : ObjectId${nullSuffix}`);
          }
          lines.push(`    : ObjectId${nullSuffix};`);
        } else {
          const tsType = sqlTypeToTs(col.sqlType, col.nullable);
          lines.push(`  ${col.name}: ${tsType};`);
        }
      }

      // Close the base type before adding reverse ref intersections
      lines.push("}");

      // Reverse refs (arrays) - add as intersection types
      for (const rev of tableReverseRefs) {
        const refInterfaceName = toPascalCase(rev.sourceTable);
        const refHasRefs = tablesWithRefs.has(rev.sourceTable);
        const refHasReverseRefs = tablesWithReverseRefs.has(rev.sourceTable);

        // Reverse refs are only included when explicitly requested in depth
        lines.push(`  & ('${rev.name}' extends keyof D`);
        lines.push(`    ? D['${rev.name}'] extends true`);
        lines.push(`      ? { ${rev.name}: ${refInterfaceName}[] }`);
        if (refHasRefs || refHasReverseRefs) {
          lines.push(`      : D['${rev.name}'] extends object`);
          lines.push(
            `        ? { ${rev.name}: ${refInterfaceName}Loaded<D['${rev.name}'] & ${refInterfaceName}Depth>[] }`
          );
          lines.push(`        : {}`);
        } else {
          lines.push(`      : D['${rev.name}'] extends object`);
          lines.push(`        ? { ${rev.name}: ${refInterfaceName}[] }`);
          lines.push(`        : {}`);
        }
        lines.push(`    : {})`);
      }

      // Final semicolon
      lines.push(";");
      lines.push("");
    } else {
      // No refs or reverse refs - Loaded is just an alias to the base type
      lines.push(
        `/** ${interfaceName} has no refs, so Loaded is the same as base type */`
      );
      lines.push(
        `export type ${interfaceName}Loaded<D extends ${interfaceName}Depth = {}> = ${interfaceName};`
      );
      lines.push("");
    }
  }

  return lines.join("\n");
}

/**
 * Generate TypeScript types and SQL schema from table definitions.
 *
 * Call this at the end of your schema file:
 * ```ts
 * generateSchema({ Chat, Message, Folder });
 * ```
 *
 * Then run: `npx tsx src/schema.ts`
 */
export function generateSchema(
  tables: Record<string, TableDescriptor>,
  options?: GenerateOptions
): void {
  const startTime = Date.now();

  // Determine output directory
  const schemaFile = process.argv[1];
  const outputDir = options?.output ?? dirname(schemaFile);

  // Build table name map (TableDescriptor -> name)
  const tableNameMap = new Map<TableDescriptor, string>();
  for (const [name, descriptor] of Object.entries(tables)) {
    descriptor.name = name;
    tableNameMap.set(descriptor, name);
  }

  // Analyze all tables
  const analyzedTables = new Map<
    string,
    { descriptor: TableDescriptor; columns: ColumnDef[] }
  >();

  for (const [name, descriptor] of Object.entries(tables)) {
    const columns = analyzeTable(name, descriptor, tableNameMap);
    analyzedTables.set(name, { descriptor, columns });
  }

  // Build reverse references (one-to-many relationships)
  const reverseRefs = buildReverseRefs(analyzedTables);

  // Generate outputs
  const sql = generateSql(analyzedTables);
  const types = generateTypes(analyzedTables, reverseRefs);

  // Ensure output directory exists
  mkdirSync(outputDir, { recursive: true });

  // Write files
  const sqlPath = join(outputDir, "schema.sql");
  const typesPath = join(outputDir, "types.ts");

  writeFileSync(sqlPath, sql);
  writeFileSync(typesPath, types);

  const elapsed = Date.now() - startTime;
  const tableCount = Object.keys(tables).length;

  console.log(
    pc.green("✓") +
      ` Generated ${pc.bold(tableCount)} table(s) in ${elapsed}ms`
  );
  console.log(`  ${pc.dim("→")} ${sqlPath}`);
  console.log(`  ${pc.dim("→")} ${typesPath}`);
}
