// Settlement-baseline native Jazz storage corpus.
//
// This is deliberately an integration receipt over the production ordered-KV
// adapters rather than a second hand-written byte codec.  The eventual checked
// in physical fixtures generated from this scenario live in #2307; keeping the
// producer here makes the semantic shape, backend profile, and reopen contract
// executable beside the NodeState paths that actually write it.

use crate::storage_codec_profile::epoch_1_storage_codec_profile;
use base64::{Engine as _, engine::general_purpose::STANDARD};
use jazz_storage_rocksdb::Durability as RocksDurability;
use jazz_storage_sqlite::{Durability as SqliteDurability, SqliteStorage as ImmediateSqliteStorage};
use sha2::{Digest, Sha256};

/// The storage families that the native settlement producer must prove before
/// its logical pack can be promoted to a committed historical fixture.
///
/// `catalogue` includes the committed active lineage and current-write pointer
/// on this base.  It intentionally excludes pending/staged catalogue crash
/// state: that state has a separate recovery receipt and must not be made part
/// of a settled historical fixture merely to inflate this corpus.
const NATIVE_CORPUS_REQUIRED_STORES: &[&str] = &[
    "jazz_catalogue",
    "jazz_catalogue_pointer",
    "jazz_nodes",
    "jazz_schema_versions",
    "jazz_transactions",
    "jazz_merge_heads",
    "jazz_global_changes",
    "jazz_deletion_history",
    "jazz_authority_policy_bindings",
    "jazz_known_state_facts",
    "jazz_settled_program_facts",
    groove::db::LARGE_VALUE_METADATA_CF,
];
const NATIVE_CORPUS_PACK_HEADER: &str = "JAZZ-NATIVE-STORAGE-CORPUS-1";
const EPOCH_1_NATIVE_CORPUS_PACK_BASE64: &str =
    include_str!("../../../fixtures/epoch-1-native-jazz-corpus.pack.base64");
const EPOCH_1_NATIVE_CORPUS_PACK_SHA256: &str =
    "fc28ce3fa5eee206f375c6dccb3ad8eaacd953b083a5d7739788f3e92125bfbd";
// Generated by the current producer through the guarded
// `JAZZ_NATIVE_CORPUS_PACK_OUT` receipt path. Unlike the epoch-one pack above,
// this records current fixture wiring and is not used to reinterpret the
// committed historical binary stores.
const CURRENT_PRODUCER_NATIVE_CORPUS_PACK_BASE64: &str =
    include_str!("../../../fixtures/current-native-jazz-producer.pack.base64");
const CURRENT_PRODUCER_NATIVE_CORPUS_PACK_SHA256: &str =
    "4aec397721f146845becdf0d5268a2229242a88ffe8b882312345d0039482d65";
const CURRENT_PRODUCER_NATIVE_CORPUS_RECEIPT_SHA256: &str =
    "180cb5a7e50253ff1880c4a066ac987de4c889acee49fd93bdb75782727b9699";
const CURRENT_NATIVE_SQLITE_BASE64: &str = include_str!("../../../fixtures/current-native-jazz.sqlite.gz.base64");
const CURRENT_NATIVE_SQLITE_ARCHIVE_SHA256: &str = "8ad336a716f3166896cd9d5bcbc73140871bb2b6ed1dbe1e06589db924eb39ef";
const CURRENT_NATIVE_SQLITE_SHA256: &str = "68392b7e23153baece369a7905532c5ed52efb1f572a35383cbfedaefa3e251c";
const CURRENT_NATIVE_ROCKSDB_BASE64: &str = include_str!("../../../fixtures/current-native-jazz-rocksdb.tar.gz.base64");
const CURRENT_NATIVE_ROCKSDB_SHA256: &str = "d215f099b52e40da63ad1b8d9ea55efa44deb67fe6811f870b185fc63b4314d6";
const EPOCH_1_NATIVE_SQLITE_BASE64: &str =
    include_str!("../../../fixtures/epoch-1-native-jazz.sqlite.gz.base64");
const EPOCH_1_NATIVE_SQLITE_ARCHIVE_SHA256: &str =
    "0436f97b2b8bb04ee286b1ce9a7e1866bdd40115e0878223135bb0e700c5c3a8";
const EPOCH_1_NATIVE_SQLITE_SHA256: &str =
    "9cf200ef662e18a0f841b9a9ff6606528b026de2ddde5c66703d762e92f457ac";
const EPOCH_1_NATIVE_ROCKSDB_BASE64: &str =
    include_str!("../../../fixtures/epoch-1-native-jazz-rocksdb.tar.gz.base64");
const EPOCH_1_NATIVE_ROCKSDB_SHA256: &str =
    "c59d02314c1dc58b69dc51904ecf062ff004fef8056b853d8cb071dd484e9ab7";

#[derive(Debug, Clone, PartialEq, Eq)]
struct NativeCorpusReceipt {
    /// Table entries retain raw primary-key/value bytes in canonical scan order.
    /// Direct-store entries encode decoded semantic Values for this test pack;
    /// their postcard representation is not the authoritative storage format.
    /// SQLite pages and RocksDB SSTs remain separate physical fixture artifacts.
    stores: BTreeMap<String, Vec<(Vec<u8>, Vec<u8>)>>,
}

fn native_corpus_checksum(receipt: &NativeCorpusReceipt) -> String {
    let mut digest = Sha256::new();
    for (store, rows) in &receipt.stores {
        digest.update((store.len() as u64).to_be_bytes());
        digest.update(store.as_bytes());
        digest.update((rows.len() as u64).to_be_bytes());
        for (key, value) in rows {
            digest.update((key.len() as u64).to_be_bytes());
            digest.update(key);
            digest.update((value.len() as u64).to_be_bytes());
            digest.update(value);
        }
    }
    format!("{:x}", digest.finalize())
}

fn native_corpus_pack(receipt: &NativeCorpusReceipt) -> String {
    let mut pack = format!("{NATIVE_CORPUS_PACK_HEADER}\n");
    for (store, rows) in &receipt.stores {
        // Preserve empty authoritative families too.  A row-only listing
        // cannot distinguish an empty-but-opened family from one the
        // producer accidentally omitted from the corpus.
        use std::fmt::Write as _;
        writeln!(pack, "store\t{store}")
            .expect("writing an in-memory corpus pack cannot fail");
        for (key, value) in rows {
            writeln!(pack, "entry\t{store}\t{}\t{}", hex::encode(key), hex::encode(value))
                .expect("writing an in-memory corpus pack cannot fail");
        }
    }
    pack
}

fn epoch_1_native_corpus_pack() -> String {
    decode_native_corpus_pack(
        EPOCH_1_NATIVE_CORPUS_PACK_BASE64,
        EPOCH_1_NATIVE_CORPUS_PACK_SHA256,
        "committed epoch-one native corpus pack",
    )
}

fn current_producer_native_corpus_pack() -> String {
    decode_native_corpus_pack(
        CURRENT_PRODUCER_NATIVE_CORPUS_PACK_BASE64,
        CURRENT_PRODUCER_NATIVE_CORPUS_PACK_SHA256,
        "current native corpus producer pack",
    )
}

fn decode_native_corpus_pack(base64: &str, expected_sha256: &str, name: &str) -> String {
    let bytes = STANDARD
        .decode(base64.trim())
        .expect("native corpus pack must be base64");
    assert_eq!(
        format!("{:x}", Sha256::digest(&bytes)),
        expected_sha256,
        "{name} checksum must match before it is compared"
    );
    let pack = String::from_utf8(bytes).expect("native corpus pack must be UTF-8");
    assert!(
        pack.starts_with(&format!("{NATIVE_CORPUS_PACK_HEADER}\n")),
        "{name} must retain its exact epoch header"
    );
    pack
}

fn decode_native_physical_fixture(
    base64: &str,
    expected_sha256: &str,
    family: &str,
) -> Result<Vec<u8>, String> {
    let bytes = STANDARD
        .decode(base64.lines().collect::<String>())
        .map_err(|error| format!("{family} corpus fixture is not base64: {error}"))?;
    if format!("{:x}", Sha256::digest(&bytes)) != expected_sha256 {
        return Err(format!("{family} corpus fixture checksum does not match"));
    }
    Ok(bytes)
}

fn materialize_native_sqlite_fixture(path: &std::path::Path, base64: &str) -> Result<(), String> {
    materialize_native_sqlite_fixture_with_hashes(path, base64, EPOCH_1_NATIVE_SQLITE_ARCHIVE_SHA256, EPOCH_1_NATIVE_SQLITE_SHA256)
}

fn materialize_native_sqlite_fixture_with_hashes(path: &std::path::Path, base64: &str, archive_sha: &str, sqlite_sha: &str) -> Result<(), String> {
    // Verify the immutable payload before creating a target. This is both a
    // corruption receipt and a guard against a bad checked-in fixture being
    // reported later as an adapter-open failure.
    let bytes = decode_native_physical_fixture(
        base64,
        archive_sha,
        "SQLite",
    )?;
    let mut sqlite = Vec::new();
    std::io::Read::read_to_end(
        &mut flate2::read::GzDecoder::new(std::io::Cursor::new(bytes)),
        &mut sqlite,
    )
    .map_err(|error| format!("SQLite corpus fixture is not gzip: {error}"))?;
    if format!("{:x}", Sha256::digest(&sqlite)) != sqlite_sha {
        return Err("SQLite corpus decompressed checksum does not match".to_owned());
    }
    materialize_native_sqlite_bytes(path, &sqlite)
}

/// Materialize an already validated SQLite image at a new physical location.
///
/// The producer uses this independently of its live database: a candidate is
/// only useful as a future historical fixture if a fresh process can open the
/// copied bytes, rather than if the still-open producer root happens to work.
fn materialize_native_sqlite_bytes(path: &std::path::Path, sqlite: &[u8]) -> Result<(), String> {
    std::fs::write(path, sqlite).map_err(|error| error.to_string())
}

fn unpack_native_rocksdb_fixture(
    root: &std::path::Path,
    base64: &str,
) -> Result<std::path::PathBuf, String> {
    let bytes = decode_native_physical_fixture(
        base64,
        EPOCH_1_NATIVE_ROCKSDB_SHA256,
        "RocksDB",
    )?;
    unpack_native_rocksdb_archive(root, &bytes)
}

/// Unpack a gzip-compressed RocksDB candidate into a fresh root.  This is kept
/// separate from base64/checksum admission so the producer can prove its
/// newly-exported archive, not just the pinned checked-in artifact.
fn unpack_native_rocksdb_archive(
    root: &std::path::Path,
    archive_bytes: &[u8],
) -> Result<std::path::PathBuf, String> {
    let decoder = flate2::read::GzDecoder::new(std::io::Cursor::new(archive_bytes));
    tar::Archive::new(decoder)
        .unpack(root)
        .map_err(|error| format!("native RocksDB corpus archive is not safe: {error}"))?;
    let database = root.join("rocksdb-epoch-1");
    if !database.is_dir() {
        return Err("native RocksDB corpus archive does not contain rocksdb-epoch-1 root".to_owned());
    }
    Ok(database)
}

fn inspect_native_sqlite_candidate(path: &std::path::Path) -> Result<(), String> {
    let connection = rusqlite::Connection::open_with_flags(
        path,
        rusqlite::OpenFlags::SQLITE_OPEN_READ_ONLY,
    )
    .map_err(|error| format!("candidate SQLite image cannot open read-only: {error}"))?;
    let rows: u64 = connection
        .query_row("SELECT COUNT(*) FROM kv", [], |row| row.get(0))
        .map_err(|error| format!("candidate SQLite image lacks readable kv rows: {error}"))?;
    if rows == 0 {
        return Err("candidate SQLite image has no durable rows".to_owned());
    }
    Ok(())
}

fn inspect_native_rocksdb_candidate(path: &std::path::Path) -> Result<(), String> {
    let options = rocksdb::Options::default();
    let families = rocksdb::DB::list_cf(&options, path)
        .map_err(|error| format!("candidate RocksDB root cannot list column families: {error}"))?;
    let read_only = rocksdb::DB::open_cf_for_read_only(&options, path, &families, false)
        .map_err(|error| format!("candidate RocksDB root cannot open read-only: {error}"))?;
    let rows = families
        .iter()
        .filter_map(|family| read_only.cf_handle(family))
        .map(|family| {
            read_only
                .iterator_cf(family, rocksdb::IteratorMode::Start)
                .count()
        })
        .sum::<usize>();
    if rows == 0 {
        return Err("candidate RocksDB root has no durable rows".to_owned());
    }
    Ok(())
}

/// A regeneration request is intentionally a two-phase operation.  The live
/// producer is only a source for a private staged candidate; an externally
/// requested artifact is not made visible until that candidate has passed the
/// independent fresh-root compatibility receipt.
fn assert_native_corpus_candidate_is_staged(
    live: &std::path::Path,
    candidate: &std::path::Path,
    kind: &str,
) {
    assert!(candidate.exists(), "{kind} staged candidate must exist");
    assert_staged_path_is_distinct(live, candidate, kind)
        .unwrap_or_else(|error| panic!("{kind} candidate must be staged outside the live producer root: {error}"));
}

/// Resolve a corpus file through its existing parent.  Candidates are required
/// to be direct children of an existing staging directory: that makes a path
/// which has not been created yet just as checkable as one which has, while
/// still resolving `.` and symlink aliases in the parent before any bytes are
/// written.
fn canonical_corpus_child(path: &std::path::Path, role: &str) -> Result<std::path::PathBuf, String> {
    let name = path
        .file_name()
        .filter(|name| !name.is_empty())
        .ok_or_else(|| format!("{role} must name a file directly below an existing directory"))?;
    let parent = path
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
        .ok_or_else(|| format!("{role} must have an existing parent directory"))?;
    let canonical_parent = std::fs::canonicalize(parent)
        .map_err(|error| format!("cannot resolve {role} parent {parent:?}: {error}"))?;
    if !canonical_parent.is_dir() {
        return Err(format!("{role} parent {canonical_parent:?} is not a directory"));
    }
    Ok(canonical_parent.join(name))
}

/// Create an implementation-owned staging root.  Regeneration accepts a
/// maintainer-selected *publication* path, but never a staging path: the
/// source database must first be copied into a private, independent location
/// before the fresh-root receipt is allowed to inspect it.
fn private_native_corpus_staging_root(kind: &str) -> tempfile::TempDir {
    tempfile::Builder::new()
        .prefix(&format!("jazz-native-corpus-{kind}-staging-"))
        .tempdir()
        .expect("create private native corpus staging root")
}

fn path_entry_exists(path: &std::path::Path) -> Result<bool, String> {
    match std::fs::symlink_metadata(path) {
        Ok(_) => Ok(true),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(false),
        Err(error) => Err(format!("cannot inspect corpus path {path:?}: {error}")),
    }
}

fn same_existing_file_identity(
    left: &std::path::Path,
    right: &std::path::Path,
) -> Result<bool, String> {
    let left_metadata = std::fs::metadata(left)
        .map_err(|error| format!("cannot stat left corpus path {left:?}: {error}"))?;
    let right_metadata = std::fs::metadata(right)
        .map_err(|error| format!("cannot stat right corpus path {right:?}: {error}"))?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::MetadataExt as _;
        return Ok(left_metadata.dev() == right_metadata.dev() && left_metadata.ino() == right_metadata.ino());
    }
    #[cfg(windows)]
    {
        use std::os::windows::fs::MetadataExt as _;
        return Ok(
            left_metadata.volume_serial_number() == right_metadata.volume_serial_number()
                && left_metadata.file_index_high() == right_metadata.file_index_high()
                && left_metadata.file_index_low() == right_metadata.file_index_low(),
        );
    }
    #[cfg(not(any(unix, windows)))]
    {
        // A platform without a stable file identity cannot prove hard-link
        // separation.  Canonical paths still reject dot and symlink aliases;
        // callers additionally reject the same canonical path below.
        let _ = (left_metadata, right_metadata);
        Ok(false)
    }
}

/// Return every regular member of a live store.  SQLite contributes its one
/// image; RocksDB contributes its manifest, logs, SSTs, and any other regular
/// backend-owned members.  Symlinks are deliberately not followed: this is a
/// trusted-maintainer accidental-alias guard, not an attempt to make a
/// concurrent hostile filesystem namespace safe against TOCTOU replacement.
fn regular_files_below(path: &std::path::Path) -> Result<Vec<std::path::PathBuf>, String> {
    let metadata = std::fs::symlink_metadata(path)
        .map_err(|error| format!("cannot inspect corpus path {path:?}: {error}"))?;
    if metadata.file_type().is_symlink() {
        return Err(format!("corpus path {path:?} is a symlink"));
    }
    if metadata.is_file() {
        return Ok(vec![path.to_path_buf()]);
    }
    if !metadata.is_dir() {
        return Ok(Vec::new());
    }

    let mut files = Vec::new();
    for entry in std::fs::read_dir(path)
        .map_err(|error| format!("cannot list corpus directory {path:?}: {error}"))?
    {
        let entry = entry.map_err(|error| format!("cannot read corpus directory entry: {error}"))?;
        let child = entry.path();
        let child_metadata = std::fs::symlink_metadata(&child)
            .map_err(|error| format!("cannot inspect corpus member {child:?}: {error}"))?;
        if child_metadata.file_type().is_symlink() {
            return Err(format!("corpus member {child:?} is a symlink"));
        }
        if child_metadata.is_file() {
            files.push(child);
        } else if child_metadata.is_dir() {
            files.extend(regular_files_below(&child)?);
        }
    }
    Ok(files)
}

/// A staged file must not share physical identity with *any* regular member of
/// the live store.  Checking only the live root misses the dangerous RocksDB
/// case where a candidate entry aliases an SST or MANIFEST directly.
fn assert_candidate_regular_files_are_independent(
    live: &std::path::Path,
    candidate: &std::path::Path,
    kind: &str,
) -> Result<(), String> {
    if !path_entry_exists(candidate)? {
        return Ok(());
    }
    let live_files = regular_files_below(live)?;
    let candidate_files = regular_files_below(candidate)?;
    for candidate_file in &candidate_files {
        for live_file in &live_files {
            if same_existing_file_identity(live_file, candidate_file)? {
                return Err(format!(
                    "{kind} candidate file {candidate_file:?} is physically linked to live producer member {live_file:?}"
                ));
            }
        }
    }
    Ok(())
}

/// Prove a staged candidate cannot be the live producer through spelling,
/// symlink, or (on platforms that expose one) physical-file aliasing.  `live`
/// is a SQLite file or a RocksDB root/archive source; candidates may be absent
/// when this is used to vet a not-yet-created temporary publication path.
fn assert_staged_path_is_distinct(
    live: &std::path::Path,
    candidate: &std::path::Path,
    kind: &str,
) -> Result<(), String> {
    let live_canonical = std::fs::canonicalize(live)
        .map_err(|error| format!("cannot resolve live {kind} producer {live:?}: {error}"))?;
    let live_root = if live_canonical.is_dir() {
        live_canonical.clone()
    } else {
        live_canonical
            .parent()
            .ok_or_else(|| format!("live {kind} producer has no parent"))?
            .to_path_buf()
    };
    let candidate_canonical = canonical_corpus_child(candidate, &format!("{kind} candidate"))?;

    if candidate_canonical == live_canonical
        || candidate_canonical.starts_with(&live_root)
    {
        return Err(format!(
            "candidate {candidate:?} resolves inside live producer root {live_root:?}"
        ));
    }
    if path_entry_exists(candidate)? {
        let candidate_metadata = std::fs::symlink_metadata(candidate)
            .map_err(|error| format!("cannot inspect existing {kind} candidate {candidate:?}: {error}"))?;
        if candidate_metadata.file_type().is_symlink() {
            return Err(format!("candidate {candidate:?} is a symlink"));
        }
        let candidate_target = std::fs::canonicalize(candidate)
            .map_err(|error| format!("cannot resolve existing {kind} candidate {candidate:?}: {error}"))?;
        if candidate_target == live_canonical || candidate_target.starts_with(&live_root) {
            return Err(format!(
                "candidate {candidate:?} resolves through an alias inside live producer root {live_root:?}"
            ));
        }
    }
    assert_candidate_regular_files_are_independent(live, candidate, kind)?;
    Ok(())
}

/// A candidate and publication destination must not alias, even where their
/// textual paths differ.  This protects an existing destination from being
/// silently used as the source and makes a future temporary name checkable
/// before it exists.
fn assert_publication_paths_are_distinct(
    candidate: &std::path::Path,
    requested: &std::path::Path,
) -> Result<(std::path::PathBuf, std::path::PathBuf), String> {
    let candidate_canonical = canonical_corpus_child(candidate, "corpus candidate")?;
    let requested_canonical = canonical_corpus_child(requested, "requested corpus output")?;
    if candidate_canonical == requested_canonical {
        return Err("requested corpus output aliases its staged candidate".to_owned());
    }
    if path_entry_exists(requested)? {
        return Err("requested corpus output already exists; choose a new path or delete it before regeneration".to_owned());
    }
    Ok((candidate_canonical, requested_canonical))
}

/// Publish a *previously verified* candidate without exposing a partially
/// copied output.  This deliberately does not validate the candidate itself:
/// callers must run the semantic verifier first, which keeps the publication
/// boundary obvious in the regeneration receipt.
fn publish_verified_native_corpus_candidate(
    candidate: &std::path::Path,
    requested: &std::path::Path,
) -> Result<(), String> {
    publish_verified_native_corpus_candidate_with_copy(candidate, requested, |candidate, temporary| {
        std::fs::copy(candidate, temporary)
            .map(|_| ())
            .map_err(|error| error.to_string())
    })
}

/// The copy operation is an explicit seam so this receipt can prove that an
/// interrupted staged copy never touches a pre-existing destination.  The
/// normal publisher above supplies `std::fs::copy`; no production path may
/// write directly to `requested` before the staged copy has completed.
fn publish_verified_native_corpus_candidate_with_copy(
    candidate: &std::path::Path,
    requested: &std::path::Path,
    copy: impl FnOnce(&std::path::Path, &std::path::Path) -> Result<(), String>,
) -> Result<(), String> {
    let (candidate, requested) = assert_publication_paths_are_distinct(candidate, requested)?;
    let parent = requested.parent().expect("canonical child has a parent");
    let file_name = requested.file_name().expect("canonical child has a name");
    let temporary = parent.join(format!(
        ".{}.native-corpus-staging-{}",
        file_name.to_string_lossy(),
        uuid::Uuid::new_v4()
    ));
    // Reserve the private name before copying.  It lives next to the requested
    // output so a later hard-link publication is an atomic create-new operation
    // on one filesystem; an existing output, including a dangling symlink, is
    // always rejected above and never overwritten.
    std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&temporary)
        .map_err(|error| format!("reserve private corpus publication path {temporary:?}: {error}"))?;
    if let Err(error) = copy(&candidate, &temporary) {
        let _ = std::fs::remove_file(&temporary);
        return Err(error);
    }
    std::fs::hard_link(&temporary, &requested).map_err(|error| {
        let _ = std::fs::remove_file(&temporary);
        format!("publish verified corpus without overwriting {requested:?}: {error}")
    })?;
    std::fs::remove_file(&temporary)
        .map_err(|error| format!("remove private corpus staging file {temporary:?}: {error}"))
}

/// Keep failed admissions from accidentally reaching the requested path.  The
/// production receipt uses the same sequencing explicitly around its full
/// semantic verifier; this smaller helper lets planted corrupt candidates
/// prove the publication guard without constructing a full producer.
fn verify_then_publish_native_corpus_candidate(
    verify: impl FnOnce() -> Result<(), String>,
    candidate: &std::path::Path,
    requested: &std::path::Path,
) -> Result<(), String> {
    verify()?;
    publish_verified_native_corpus_candidate(candidate, requested)
}

fn assert_same_native_corpus(
    left: &NativeCorpusReceipt,
    right: &NativeCorpusReceipt,
    message: &str,
) {
    if left == right {
        return;
    }
    let differing_store = left
        .stores
        .keys()
        .chain(right.stores.keys())
        .find(|store| left.stores.get(*store) != right.stores.get(*store));
    panic!(
        "{message}; first differing store={differing_store:?}, left checksum={}, right checksum={}",
        native_corpus_checksum(left),
        native_corpus_checksum(right),
    );
}

/// Return the engine-owned metadata ledger from Groove's shared large-value
/// class. `chunk/` entries are the backing chunk plane's bytes and its local
/// installation receipt; their physical representation is backend-owned.
/// Every other key prefix is a canonical Groove metadata/lifecycle record and
/// is therefore part of the backend-neutral historical pack. Unknown keys
/// fail closed rather than disappearing from the corpus when that ledger
/// grows.
fn native_corpus_large_value_metadata_entries<S>(node: &NodeState<S>) -> Vec<(Vec<u8>, Vec<u8>)>
where
    S: OrderedKvStorage,
{
    let entries = crate::db::block_on(
        node.database
            .large_value_metadata_entries_for_compatibility(),
    )
    .expect("scan Groove large-value metadata corpus family");
    let metadata_prefixes: &[&[u8]] = &[
        b"root/",
        b"node/",
        b"reclaim/",
        b"staged/",
        b"upload/",
        b"completed-upload/",
        b"completed-receipt/",
        b"install/",
    ];
    entries
        .into_iter()
        .filter_map(|(key, value)| {
            if key.starts_with(b"chunk/") {
                return None;
            }
            assert!(
                metadata_prefixes.iter().any(|prefix| key.starts_with(prefix)),
                "unknown key in Groove large-value metadata family must be explicitly classified before corpus publication: {}",
                hex::encode(&key),
            );
            Some((key, value))
        })
        .collect()
}

fn native_corpus_schema() -> JazzSchema {
    build_public_test_schema(
        PublicSchemaBuilder::new()
            .table(
                PublicTableSchemaBuilder::new("todos")
                    .column("branch_id", PublicColumnType::Uuid)
                    .column("title", PublicColumnType::Text)
                    .column("attachment", PublicColumnType::Bytea)
                    .branch_by("branch_id"),
            )
            .table(PublicTableSchemaBuilder::new("notes").column("body", PublicColumnType::Text)),
    )
}

fn native_corpus_evolved_schema() -> JazzSchema {
    build_public_test_schema(
        PublicSchemaBuilder::new()
            .table(
                PublicTableSchemaBuilder::new("todos")
                    .column("branch_id", PublicColumnType::Uuid)
                    .column("title", PublicColumnType::Text)
                    .column("attachment", PublicColumnType::Bytea)
                    .branch_by("branch_id"),
            )
            .table(
                PublicTableSchemaBuilder::new("notes")
                    .column("body", PublicColumnType::Text)
                    .column("genre", PublicColumnType::Text),
            ),
    )
}

fn native_corpus_lineage(
    snapshot: &crate::protocol::CatalogueSnapshot,
) -> SchemaLineagePublication {
    let namespace = uuid::Uuid::from_bytes([0x4a; 16]);
    let source = native_corpus_schema();
    let target = SchemaVersion::new(native_corpus_evolved_schema());
    let mut publication = SchemaLineagePublication::author_from_prior(
        &source,
        &snapshot.genesis_physical_identities,
        target.clone(),
        MigrationLens::new(
            source.version_id(),
            target.id,
            vec![
                TableLens {
                    source_table: "todos".to_owned(),
                    target_table: "todos".to_owned(),
                    ops: Vec::new(),
                },
                TableLens {
                    source_table: "notes".to_owned(),
                    target_table: "notes".to_owned(),
                    ops: vec![LensOp::AddColumn {
                        column: "genre".to_owned(),
                        default: v("instrumental"),
                    }],
                },
            ],
        )
        .expect("native corpus lineage is valid"),
        Vec::<String>::new(),
        Vec::<String>::new(),
    )
    .expect("native corpus lineage is valid");
    publication.physical_identities.tables.get_mut("notes")
        .expect("lineage retains notes table")
        .columns.get_mut("genre")
        .expect("lineage allocates genre column")
        .id = crate::ids::GlobalPhysicalColumnId(uuid::Uuid::new_v5(
            &namespace,
            b"table/notes/column/genre",
        ));
    publication.id = publication.content_id();
    publication
}

fn publish_native_corpus_lineage<S>(
    node: &mut NodeState<S>,
    snapshot: &crate::protocol::CatalogueSnapshot,
)
where
    S: ReopenableStorage,
{
    let publication = native_corpus_lineage(snapshot);
    let target = publication.schema.id;
    node.apply_trusted_catalogue_message_settled(SyncMessage::PublishSchemaWithLens {
        author: AuthorSubject::SYSTEM,
        catalogue_seq: 1,
        publication: Box::new(publication),
    })
    .expect("publish native corpus lineage");
    // A published lineage is not itself a write-pointer change.  The corpus
    // deliberately exercises both durable records: recovering an active lens
    // and projecting the old note into its descendant current-write schema.
    node.apply_trusted_catalogue_message_settled(SyncMessage::SetCurrentWriteSchema {
        author: AuthorSubject::SYSTEM,
        pointer: crate::protocol::CurrentWriteSchema {
            revision: 1,
            schema: target,
        },
    })
    .expect("activate native corpus descendant write schema");
}

fn seed_native_corpus_settled_query_state<S>(node: &mut NodeState<S>)
where
    S: ReopenableStorage,
{
    let (shape, binding) = node
        .whole_table_shape_binding("notes")
        .expect("native corpus prepares a notes query shape");
    // The corpus receiver consumes the authority's SYSTEM+claims-scoped
    // closure below. Register its exact shape/options once, then install that
    // same policy-scoped binding; a bare synthetic subscription is a distinct
    // fixture identity and cannot admit this source closure.
    node.apply_sync_message_settled(SyncMessage::RegisterShape {
        shape_id: shape.shape_id(),
        ast: crate::protocol::ShapeAst::from_validated(&shape),
        opts: crate::protocol::RegisterShapeOptions::default(),
    })
    .expect("native corpus registers exact notes shape");
    let subscription = node
        .whole_table_subscription_key("notes")
        .expect("native corpus registers its notes subscription");
    // Keep one policy-scoped authority receipt in the corpus. Its fixed
    // ordered-key handle and typed collision-check directory are storage
    // format, not an optional cache implementation detail.
    let policy_claims = BTreeMap::from([(
        "corpus_scope".to_owned(),
        Value::String("settlement-v1".to_owned()),
    )]);
    node.apply_sync_message_settled(SyncMessage::Subscribe(crate::protocol::Subscribe {
        shape_id: shape.shape_id(),
        subscription,
        values: Vec::new(),
        known_state: None,
        delegated_session: Some(crate::protocol::DelegatedSessionBinding {
            identity: AuthorSubject::SYSTEM,
            claims: policy_claims.clone(),
        }),
    }))
    .expect("native corpus registers a policy-scoped receipt");
    let mut authority = PeerState::relay();
    authority.set_subscription_policy_binding(
        subscription,
        (AuthorSubject::SYSTEM, policy_claims),
    );
    let update = authority
        .rehydrate_query_for_subscription_with_opts(
            node,
            subscription,
            &shape,
            &binding,
            crate::protocol::RegisterShapeOptions::default(),
        )
        .expect("native corpus derives an exact source closure")
        .expect("native corpus receives an authority reset");
    node.apply_sync_message_settled(update)
        .expect("native corpus persists exact source-closure facts");
}

fn native_corpus_branch(byte: u8) -> BranchSelector {
    BranchSelector::new([("branch_id", Value::Uuid(uuid::Uuid::from_bytes([byte; 16])))])
}

fn native_corpus_large_attachment() -> Vec<u8> {
    // Cross the public inline boundary by one byte.  The repeated payload
    // keeps the checked-in physical fixture compact under the native adapters'
    // ordinary compression while still forcing a real indirect root/node
    // closure into the historical store.
    vec![0x5a; groove::large_values::INLINE_VALUE_MAX_BYTES + 1]
}

fn native_corpus_storage_tables(schema: &JazzSchema) -> (Vec<String>, Vec<String>) {
    let lowered = schema.lower_to_groove();
    let mut tables = lowered
        .tables
        .iter()
        .map(|table| table.name.clone())
        .collect::<Vec<_>>();
    tables.sort();
    tables.dedup();
    let mut direct_stores = lowered
        .direct_record_stores
        .iter()
        .map(|store| store.name.clone())
        .collect::<Vec<_>>();
    direct_stores.sort();
    direct_stores.dedup();
    (tables, direct_stores)
}

/// The authority mints permanent physical identities exactly once.  A native
/// compatibility corpus must replay that one authority snapshot into every
/// backend: independently calling `NodeState::new` would correctly allocate
/// different UUID identities, but would make the purportedly backend-neutral
/// historical pack meaningless.
fn native_corpus_authority_snapshot(schema: &JazzSchema) -> crate::protocol::CatalogueSnapshot {
    // This deliberately mirrors the authority's one-time UUID allocation,
    // but derives the fixture identities from a fixed namespace. Random UUIDs
    // are right in real authority publication; they would make a committed
    // byte corpus change on every test run.
    let namespace = uuid::Uuid::from_bytes([0x4a; 16]);
    let physical_identities = crate::protocol::PhysicalIdentityManifest {
        tables: schema
            .tables
            .iter()
            .map(|table| {
                let columns = table
                    .columns
                    .iter()
                    .map(|column| {
                        let path = format!("table/{}/column/{}", table.name, column.name);
                        (
                            column.name.clone(),
                            crate::protocol::PhysicalColumnIdentity {
                                id: crate::ids::GlobalPhysicalColumnId(uuid::Uuid::new_v5(
                                    &namespace,
                                    path.as_bytes(),
                                )),
                                // The corpus schema intentionally contains no
                                // enums; enum identity fixtures remain in the
                                // focused catalogue corpus.
                                enum_variants: BTreeMap::new(),
                            },
                        )
                    })
                    .collect();
                (
                    table.name.clone(),
                    crate::protocol::PhysicalTableIdentity {
                        id: crate::ids::GlobalPhysicalTableId(uuid::Uuid::new_v5(
                            &namespace,
                            format!("table/{}", table.name).as_bytes(),
                        )),
                        columns,
                    },
                )
            })
            .collect(),
    };
    crate::protocol::CatalogueSnapshot {
        genesis_physical_identities: physical_identities,
        schemas: vec![crate::protocol::SchemaVersion::new(schema.clone())],
        lineages: Vec::new(),
        current_write_schema: crate::protocol::CurrentWriteSchema {
            revision: 0,
            schema: schema.version_id(),
        },
    }
}

fn native_corpus_required_application_stores<S>(
    node: &NodeState<S>,
) -> BTreeSet<String>
where
    S: OrderedKvStorage,
{
    // Resolve the physical family names through the restored catalogue rather
    // than logical lowering.  Logical tables are not storage identities; a
    // lineage can retain a table name while changing which permanent physical
    // table owns its historical records.
    let mut stores = BTreeSet::new();
    for version in node.catalogue_schemas().values() {
        for table in &version.schema.tables {
            let table_id = node
                .physical_table_id_for_schema(version.id, &table.name)
                .unwrap_or_else(|error| {
                    panic!("resolve physical corpus table {}: {error}", table.name)
                });
            stores.extend([
                physical_history_table_name(table_id),
                physical_register_table_name(table_id),
                physical_global_current_table_name(table_id),
                physical_register_global_current_table_name(table_id),
                physical_ahead_current_table_name(table_id),
                physical_register_ahead_current_table_name(table_id),
                physical_rejected_versions_table_name(table_id),
            ]);
        }
    }
    stores
}

fn native_corpus_receipt<S>(node: &NodeState<S>, schema: &JazzSchema) -> NativeCorpusReceipt
where
    S: OrderedKvStorage,
{
    let (tables, direct_stores) = native_corpus_storage_tables(schema);
    let mut stores = tables
        .into_iter()
        .map(|table| {
            let rows = crate::db::block_on(node.database.primary_key_scan_raw(&table, &[]))
                .unwrap_or_else(|error| panic!("scan corpus store {table}: {error}"));
            (
                table,
                rows.into_iter()
                    .map(|row| row.into_parts())
                    .collect::<Vec<_>>(),
            )
        })
        .collect::<BTreeMap<_, _>>();
    for store_name in direct_stores {
        let store = node
            .database
            .direct_record_store(&store_name)
            .unwrap_or_else(|error| panic!("open corpus direct store {store_name}: {error}"));
        let entries = crate::db::block_on(store.prefix_entries(&[]))
            .unwrap_or_else(|error| panic!("scan corpus direct store {store_name}: {error}"));
        let rows = entries
            .into_iter()
            .map(|entry| {
                let key = postcard::to_allocvec(&entry.key)
                    .expect("corpus direct-store key has a canonical semantic fixture");
                let values = entry
                    .value
                    .to_values()
                    .expect("corpus direct-store value decodes");
                let value = postcard::to_allocvec(&values)
                    .expect("corpus direct-store value has a canonical semantic fixture");
                (key, value)
            })
            .collect::<Vec<_>>();
        // The baseline corpus intentionally has no scope-isolated relay
        // attachment. Keep its historical receipt focused on settled state;
        // a populated repair ledger is separately exercised by relay tests.
        if store_name == crate::schema::SCOPE_RELAY_REPAIR_LEDGER_STORE && rows.is_empty() {
            continue;
        }
        stores.insert(store_name, rows);
    }

    // Groove's large-value metadata plane is deliberately neither an
    // application table nor a direct record store: its key namespace selects
    // several engine-owned canonical record shapes (root refcounts, node
    // edges/refcounts, staging/upload lifecycle journals, and install/reclaim
    // markers).  Freeze its exact ordered bytes alongside Jazz's physical row
    // families rather than accidentally treating the row descriptor as the
    // whole indirect-value persistence contract.
    let large_value_entries = native_corpus_large_value_metadata_entries(node);
    assert!(
        stores
            .insert(
                groove::db::LARGE_VALUE_METADATA_CF.to_owned(),
                large_value_entries,
            )
            .is_none(),
        "the engine-owned large-value metadata family is not an application direct store"
    );

    // Application rows do not live in the authored logical table declarations.
    // They are lowered into permanent physical table identities, with separate
    // immutable-history, register, current-winner, and rejected families. A
    // corpus that scans only `lower_to_groove()` therefore misses the bytes it
    // exists to freeze.
    for storage_table in native_corpus_required_application_stores(node) {
        let rows = crate::db::block_on(node.database.primary_key_scan_raw(&storage_table, &[]))
            .unwrap_or_else(|error| panic!("scan physical corpus store {storage_table}: {error}"));
        assert!(
            stores
                .insert(
                    storage_table.clone(),
                    rows.into_iter().map(|row| row.into_parts()).collect(),
                )
                .is_none(),
            "one permanent physical table identity must have one receipt entry: {storage_table}"
        );
    }
    NativeCorpusReceipt { stores }
}

fn assert_native_corpus_has_required_families<S>(node: &mut NodeState<S>, receipt: &NativeCorpusReceipt)
where
    S: OrderedKvStorage,
{
    for store in NATIVE_CORPUS_REQUIRED_STORES {
        assert!(
            receipt.stores.contains_key(*store),
            "the producer registry must include {store}"
        );
    }
    for store in [
        "jazz_catalogue",
        "jazz_nodes",
        "jazz_schema_versions",
        "jazz_transactions",
        "jazz_merge_heads",
        "jazz_global_changes",
        "jazz_deletion_history",
        "jazz_known_state_facts",
        "jazz_settled_program_facts",
        groove::db::LARGE_VALUE_METADATA_CF,
    ] {
        assert!(
            !receipt.stores[store].is_empty(),
            "the settlement producer must actually write {store}"
        );
    }
    let application = native_corpus_required_application_stores(node);
    assert!(
        application.iter().all(|store| receipt.stores.contains_key(store)),
        "the corpus must scan every permanent physical application family derived from the authority manifest"
    );
    assert!(
        application.iter().any(|store| {
            store.ends_with("_history") && !receipt.stores[store].is_empty()
        }),
        "the authority-derived physical application closure must contain historical row records"
    );
    assert!(
        application.iter().any(|store| {
            (store.ends_with("_global_current") || store.ends_with("_ahead_current"))
                && !receipt.stores[store].is_empty()
        }),
        "the authority-derived physical application closure must contain current row projections"
    );

    // The seeded descriptor must be tied to real metadata, not merely present
    // in a transaction/version byte.  Root and node keys are each the exact
    // canonical NodeRef selected by that descriptor; their non-empty values
    // carry the durable/reference-count and child-edge state.  A healthy
    // local finalize has no remaining `install/` marker: that marker is an
    // interrupted remote-hydration recovery obligation, not durable ownership.
    let versions = node
        .query_table_versions("todos")
        .expect("read native corpus attachment history");
    let table = node.table("todos").expect("native corpus todos table");
    let attachment = versions
        .iter()
        .find(|version| version.row_uuid() == row(0xc1))
        .and_then(|version| version.cell(table, "attachment").expect("decode corpus attachment"))
        .expect("seeded corpus row retains an attachment");
    let Value::Large(value_ref) = attachment else {
        panic!("seeded corpus attachment must be an indirect large value");
    };
    let encoded_root = groove::large_values::encode_node_ref(&value_ref.root)
        .expect("seeded large-value root has a canonical NodeRef");
    let mut root_key = b"root/".to_vec();
    root_key.extend_from_slice(&encoded_root);
    let mut node_key = b"node/".to_vec();
    node_key.extend_from_slice(&encoded_root);
    let metadata = &receipt.stores[groove::db::LARGE_VALUE_METADATA_CF];
    assert!(
        metadata.iter().any(|(key, value)| key == &root_key && !value.is_empty()),
        "the seeded descriptor's exact root key retains nonempty durable lifecycle/refcount metadata"
    );
    assert!(
        metadata.iter().any(|(key, value)| key == &node_key && !value.is_empty()),
        "the seeded descriptor's exact root node retains nonempty child/reference metadata"
    );
    assert!(
        metadata.iter().all(|(key, _)| !key.starts_with(b"install/")),
        "a completed local seed leaves no unfinished remote-install journal"
    );
}

fn seed_native_corpus<S>(
    node: &mut NodeState<S>,
    first_title: &str,
    note_body: &str,
) -> (RowUuid, TxId)
where
    S: OrderedKvStorage + ReopenableStorage + 'static,
{
    let row_uuid = row(0xc1);
    let branch = native_corpus_branch(0xc2);
    let mut first_commit = MergeableCommit::new("todos", row_uuid, 100)
        .branch(branch.clone())
        .cells(BTreeMap::from([("title".to_owned(), v(first_title))]));
    // Normal applications deliberately receive fresh random retrieval
    // capabilities. The corpus is the exception: it needs one replayable
    // authority-produced byte snapshot, so Groove's test-only constructor
    // supplies deterministic capabilities while the ordinary stage/finalize
    // and row-publication paths remain unchanged.
    let prepared = groove::large_values::prepare_with_fixture_locators(
        groove::large_values::LargeValueKind::Bytes,
        &native_corpus_large_attachment(),
        b"jazz-storage-epoch-1-native-corpus",
    )
    .expect("fixture large value prepares");
    let upload_id = groove::large_values::StagedLargeValueId([0xc5; 16]);
    crate::db::block_on(node.begin_streaming_large_value_upload(
        upload_id,
        groove::large_values::LargeValueKind::Bytes,
    ))
    .expect("fixture upload establishes its normal pending journal");
    crate::db::block_on(node.stage_large_value_chunk_batch(
        upload_id,
        groove::large_values::LargeValueKind::Bytes,
        prepared.staged_chunks,
    ))
    .expect("fixture chunks stage through the normal node admission path");
    let staged = crate::db::block_on(node.finalize_large_value_upload(upload_id, prepared.value_ref))
        .expect("fixture root finalizes through the normal node admission path");
    first_commit
        .cells
        .insert("attachment".to_owned(), Value::Large(staged.value_ref));
    first_commit
        .prepared_large_columns
        .insert("attachment".to_owned());
    first_commit.staged_large_values.push(staged.id);
    let first = node
        .commit_mergeable_settled(first_commit)
        .expect("seed branch/history/current transaction");
    let second = node
        .commit_mergeable_settled(
            MergeableCommit::new("todos", row_uuid, 101)
                .branch(branch)
                .parents(vec![first])
                .cells(BTreeMap::from([
                    ("title".to_owned(), v("mixed-write predecessor")),
                    ("attachment".to_owned(), Value::Bytes(vec![3, 4, 5, 6])),
                ])),
        )
        .expect("seed second historical version");
    node.accept_global_for_test(first)
        .expect("settle first history version globally");
    node.accept_global_for_test(second)
        .expect("settle second history version globally");
    node.commit_mergeable_settled(
        MergeableCommit::new("notes", row(0xc3), 102)
            .cells(BTreeMap::from([("body".to_owned(), v(note_body))])),
    )
    .expect("seed independent current row");
    let deletion = node
        .commit_mergeable_settled(
            MergeableCommit::new("notes", row(0xc6), 103)
                .deletion(DeletionEvent::Deleted),
        )
        .expect("seed an independent deletion history entry");
    node.accept_global_for_test(deletion)
        .expect("settle deletion history globally");
    (row_uuid, second)
}

fn assert_native_corpus_semantics<S>(node: &mut NodeState<S>, row_uuid: RowUuid)
where
    S: OrderedKvStorage,
{
    let versions = node.query_table_versions("todos").expect("history reads");
    assert_eq!(versions.len(), 2, "both immutable history versions survive");
    let source_schema = native_corpus_schema();
    let source_todos = source_schema
        .tables()
        .iter()
        .find(|table| table.name == "todos")
        .expect("native corpus source todos schema");
    assert_eq!(
        versions[0].cell(source_todos, "title").expect("decode first title"),
        Some(v("settlement baseline")),
        "the first historical title survives reopening exactly"
    );
    assert_eq!(
        versions[1].cell(source_todos, "title").expect("decode second title"),
        Some(v("mixed-write predecessor")),
        "the later historical title survives reopening exactly"
    );
    let latest = node.version_tx_id(&versions[1]).expect("latest history tx id");
    assert_eq!(node.version_tx_id(&versions[1]).unwrap(), latest);
    assert_eq!(
        node.transaction_record(latest)
            .expect("latest transaction is durable")
            .tx_id,
        latest
    );
    let rows = node
        .current_rows("todos", DurabilityTier::Local)
        .expect("current rows reopen");
    assert_eq!(rows.len(), 0, "branch rows stay out of the shared read view");
    let note_versions = node
        .query_table_versions("notes")
        .expect("independent table history");
    let source_notes = source_schema
        .tables()
        .iter()
        .find(|table| table.name == "notes")
        .expect("native corpus source notes schema")
        .clone();
    let historical_note = note_versions
        .iter()
        .find(|version| version.row_uuid() == row(0xc3))
        .expect("independent note history survives");
    assert_eq!(
        historical_note.cell(&source_notes, "body").expect("decode historical note body"),
        Some(v("independent table")),
        "the old authored note body survives reopening exactly"
    );
    assert!(versions.iter().all(|version| version.row_uuid() == row_uuid));

    let active_schema = native_corpus_evolved_schema();
    let active_shape = Query::from("notes")
        .validate(&active_schema)
        .expect("active notes query validates after reopen");
    let active_binding = active_shape
        .bind(BTreeMap::new())
        .expect("active notes query binds after reopen");
    let current_notes = node
        .query_rows(&active_shape, &active_binding, DurabilityTier::Local)
        .expect("current note projection reopens through NodeState");
    let active_notes = active_schema
        .tables()
        .iter()
        .find(|table| table.name == "notes")
        .expect("active notes schema");
    let visible_note = current_notes
        .iter()
        .find(|current| current.row_uuid() == row(0xc3))
        .expect("settled note remains visible in the active projection");
    assert_eq!(
        visible_note.cell(&active_notes, "body"),
        Some(v("independent table")),
        "active projection retains the old body"
    );
    assert_eq!(
        visible_note.cell(&active_notes, "genre"),
        Some(v("instrumental")),
        "active migration lens supplies its durable default"
    );
    assert!(
        current_notes.iter().all(|current| current.row_uuid() != row(0xc6)),
        "a globally settled deletion remains invisible from normal current reads after reopen"
    );
    let active = node.current_write_schema().expect("current write schema reopens");
    assert_eq!(active.revision, 1, "active write-schema revision survives reopen");
    assert_eq!(
        active.schema,
        active_schema.version_id(),
        "active write-schema pointer targets the published lineage descendant"
    );
    assert_eq!(node.catalogue_schemas().len(), 2, "genesis and descendant schemas reopen");
    assert_eq!(node.catalogue_lenses().len(), 1, "active lineage lens reopens");
    assert_eq!(
        node.settled_authoritative_receipt_counts_for_test(),
        (1, 1),
        "settled result membership and program facts are recovered as NodeState query state"
    );

    // The receipt above deliberately records the row descriptor, not the
    // chunk backend's private install receipt.  Prove the complementary
    // durable contract directly: reopening the current node materializes the
    // whole indirect value through Groove's ordered chunk plane.
    let table = node.table("todos").expect("todos table remains known").clone();
    let attachment = versions[0]
        .cell(&table, "attachment")
        .expect("history attachment decodes")
        .expect("first version carries the indirect attachment");
    let Value::Large(value_ref) = attachment else {
        panic!("first history attachment must retain its large-value descriptor");
    };
    assert_eq!(
        crate::db::block_on(node.read_large_value_range(&value_ref, 0..value_ref.byte_length))
            .expect("reopened large tree materializes"),
        native_corpus_large_attachment(),
        "the indirect byte tree survives the native reopen"
    );
}

fn exercise_native_corpus<S>(
    schema: JazzSchema,
    snapshot: &crate::protocol::CatalogueSnapshot,
    open: impl Fn() -> S,
    open_with_incomplete_profile: impl Fn() -> Result<S, groove::storage::Error>,
    archive_historical: impl Fn(),
    verify_exported_historical: impl Fn(),
    publish_verified_historical: impl Fn(),
) -> NativeCorpusReceipt
where
    S: OrderedKvStorage + ReopenableStorage + 'static,
{
    // The physical manifest is authority-owned state.  Installing the same
    // published snapshot into the independent SQLite and RocksDB roots makes
    // their logical packs comparable without pretending local integer aliases
    // or freshly minted UUIDs are an interchange format.
    let mut producer = crate::db::block_on(NodeState::new_catalogue_uninitialized(node(0xc0), open()))
        .expect("open uninitialized settlement-baseline producer");
    producer
        .apply_trusted_catalogue_snapshot_settled(snapshot.clone())
        .expect("install the one authority snapshot before corpus writes");
    let (row_uuid, _latest) = seed_native_corpus(
        &mut producer,
        "settlement baseline",
        "independent table",
    );
    publish_native_corpus_lineage(&mut producer, snapshot);
    seed_native_corpus_settled_query_state(&mut producer);
    let before_close = native_corpus_receipt(&producer, &schema);
    assert_native_corpus_has_required_families(&mut producer, &before_close);
    drop(producer);
    archive_historical();
    // Do not let the live producer root stand in for a checked-in physical
    // candidate.  Its export must itself survive a fresh materialize/unpack
    // and the complete historical compatibility contract before later writes
    // mutate the source root.
    verify_exported_historical();
    publish_verified_historical();

    // A profile that omits Jazz's own codec IDs must be rejected at the
    // adapter manifest boundary.  Reopening the right profile immediately
    // afterwards proves that the failed admission did not reinterpret or
    // rewrite any producer bytes before reporting the incompatibility.
    assert!(
        open_with_incomplete_profile().is_err(),
        "a native store must reject an incomplete codec profile before opening Jazz data"
    );
    let unchanged_after_rejection =
        crate::db::block_on(NodeState::new(node(0xc0), schema.clone(), open()))
            .expect("correct profile reopens after rejected admission");
    assert_eq!(
        native_corpus_receipt(&unchanged_after_rejection, &schema),
        before_close,
        "rejected codec admission must not mutate the historical corpus"
    );
    drop(unchanged_after_rejection);

    // This open performs no application writes.  It proves that the current
    // runtime reads a separately constructed durable root before the mixed
    // current-format write below changes any physical family.
    let mut reopened = crate::db::block_on(NodeState::new(node(0xc0), schema.clone(), open()))
        .expect("open historical native corpus without mutation");
    assert_eq!(native_corpus_receipt(&reopened, &schema), before_close);
    assert_native_corpus_semantics(&mut reopened, row_uuid);

    reopened
        .commit_mergeable_settled(
            MergeableCommit::new("notes", row(0xc4), 104)
                .cells(BTreeMap::from([("body".to_owned(), v("current writer"))])),
        )
        .expect("mixed current write");
    drop(reopened);

    let mut after_mixed_write =
        crate::db::block_on(NodeState::new(node(0xc0), schema.clone(), open()))
            .expect("reopen mixed store");
    assert_native_corpus_semantics(&mut after_mixed_write, row_uuid);
    assert!(
        after_mixed_write
            .query_table_versions("notes")
            .expect("mixed write history")
            .iter()
        .any(|version| version.row_uuid() == row(0xc4)),
        "new writer data survives without rewriting historical transaction bytes"
    );
    assert_ne!(
        native_corpus_checksum(&native_corpus_receipt(&after_mixed_write, &schema)),
        native_corpus_checksum(&before_close),
        "a real application-row write must change the corpus digest"
    );
    before_close
}

/// Open a committed historical physical fixture with current Jazz, without
/// giving the verifier any producer-only state. The fixture itself carries the
/// catalogue snapshot, physical IDs, row histories, current registers, and
/// large-value descriptor; current code must recover all of those before it
/// is allowed to add a new row.
fn verify_historical_native_corpus<S>(
    schema: JazzSchema,
    expected_pack: fn() -> String,
    open: impl Fn() -> S,
)
where
    S: OrderedKvStorage + ReopenableStorage + 'static,
{
    let mut reader = crate::db::block_on(NodeState::new(node(0xc0), schema.clone(), open()))
        .expect("current Jazz opens committed native corpus");
    let before_write = native_corpus_receipt(&reader, &schema);
    assert_native_corpus_has_required_families(&mut reader, &before_write);
    if std::env::var_os("JAZZ_NATIVE_CORPUS_PACK_OUT").is_none() {
        assert_eq!(
            native_corpus_pack(&before_write),
            expected_pack(),
            "current Jazz reads every retained historical family and entry"
        );
    }
    assert_native_corpus_semantics(&mut reader, row(0xc1));
    reader
        .commit_mergeable_settled(
            MergeableCommit::new("notes", row(0xc4), 104)
                .cells(BTreeMap::from([("body".to_owned(), v("current writer"))])),
        )
        .expect("current Jazz writes alongside committed history");
    drop(reader);

    let mut reopened = crate::db::block_on(NodeState::new(node(0xc0), schema, open()))
        .expect("current Jazz reopens mixed native corpus");
    assert_native_corpus_semantics(&mut reopened, row(0xc1));
    assert!(
        reopened
            .query_table_versions("notes")
            .expect("mixed-write notes history")
            .iter()
            .any(|version| version.row_uuid() == row(0xc4)),
        "current write survives a third-process reopen"
    );
}

fn in_memory_native_corpus_receipt(first_title: &str, note_body: &str) -> NativeCorpusReceipt {
    let schema = native_corpus_schema();
    let families = schema.column_families();
    let refs = families.iter().map(String::as_str).collect::<Vec<_>>();
    let storage = MemoryStorage::new(&refs).expect("open in-memory sensitivity store");
    let mut node = crate::db::block_on(NodeState::new(node(0xc0), schema.clone(), storage))
        .expect("open in-memory sensitivity node");
    seed_native_corpus(&mut node, first_title, note_body);
    native_corpus_receipt(&node, &schema)
}

/// Proves that both production native adapters share the same full Jazz
/// producer/reopen/mixed-write semantics under the closed epoch-one profile.
///
/// alice creates a branch-local row with two immutable versions and a byte
/// scalar, then closes the native store.  A fresh process reads the old state,
/// writes a new independent row, and a third process verifies both generations.
///
/// ```text
/// producer ──history + branch──► native store ──reopen──► reader
///                                                    │
///                                            current write
///                                                    ▼
///                                            third-process reopen
/// ```
#[test]
fn settlement_baseline_native_jazz_corpus_reopens_and_accepts_mixed_writes() {
    let schema = native_corpus_schema();
    let snapshot = native_corpus_authority_snapshot(&schema);
    let profile = epoch_1_storage_codec_profile().expect("closed Jazz profile");

    let rocks_directory = tempfile::tempdir().expect("create RocksDB corpus directory");
    let rocks_path = rocks_directory.path().to_path_buf();
    let rocks_schema = schema.clone();
    let rocks_profile = profile.clone();
    let rocks_open_path = rocks_path.clone();
    let rocks_wrong_path = rocks_path.clone();
    let rocks_live_path_for_verification = rocks_path.clone();
    let rocks_live_path_for_publish = rocks_path.clone();
    let rocks_wrong_schema = rocks_schema.clone();
    // The candidate root is implementation-owned.  A maintainer may choose
    // only a final publication path, never a location that could alias the
    // live RocksDB tree while it is being exported.
    let rocks_candidate_directory = private_native_corpus_staging_root("rocksdb");
    let rocks_candidate_archive = rocks_candidate_directory.path().join("epoch-1-native-jazz-rocksdb.tar.gz");
    let requested_rocks_archive = std::env::var_os("JAZZ_NATIVE_CORPUS_ROCKS_ARCHIVE_OUT")
        .map(std::path::PathBuf::from);
    let rocks_archive_output = rocks_candidate_archive.clone();
    let rocks_candidate_verify_archive = rocks_candidate_archive.clone();
    let rocks_candidate_schema = rocks_schema.clone();
    let rocks_candidate_profile = profile.clone();
    let rocks_receipt = exercise_native_corpus(rocks_schema.clone(), &snapshot, move || {
        let families = rocks_schema.column_families();
        let refs = families.iter().map(String::as_str).collect::<Vec<_>>();
        YieldingStorage::wrap(
            ImmediateRocksDbStorage::open_with_durability_and_codec_profile(
                &rocks_open_path,
                &refs,
                RocksDurability::FullSync,
                &rocks_profile,
            )
            .expect("open RocksDB corpus storage"),
        )
    }, move || {
        let families = rocks_wrong_schema.column_families();
        let refs = families.iter().map(String::as_str).collect::<Vec<_>>();
        ImmediateRocksDbStorage::open_with_durability_and_codec_profile(
            &rocks_wrong_path,
            &refs,
            RocksDurability::FullSync,
            &groove::storage::StorageCodecProfile::groove_epoch_1(),
        )
        .map(YieldingStorage::wrap)
    }, move || {
        assert_ne!(
            rocks_archive_output.parent(),
            rocks_path.parent(),
            "RocksDB candidate archive must be staged outside the live producer root"
        );
        let output_file = std::fs::File::create(&rocks_archive_output)
            .expect("create RocksDB candidate archive");
        let encoder = flate2::write::GzEncoder::new(output_file, flate2::Compression::best());
        let mut archive = tar::Builder::new(encoder);
        archive
            .append_dir_all("rocksdb-epoch-1", &rocks_path)
            .expect("archive requested RocksDB corpus store");
        archive
            .into_inner()
            .expect("finish RocksDB tar archive")
            .finish()
            .expect("finish RocksDB gzip archive");
    }, move || {
        assert_native_corpus_candidate_is_staged(
            &rocks_live_path_for_verification,
            &rocks_candidate_verify_archive,
            "RocksDB archive",
        );
        let verification_root = tempfile::tempdir()
            .expect("create fresh RocksDB candidate verification root");
        let archive = std::fs::read(&rocks_candidate_verify_archive)
            .expect("read exported RocksDB candidate archive");
        let candidate_root = unpack_native_rocksdb_archive(verification_root.path(), &archive)
            .expect("unpack exported RocksDB candidate into fresh root");
        inspect_native_rocksdb_candidate(&candidate_root)
            .expect("exported RocksDB candidate has readable durable rows");
        let candidate_schema = rocks_candidate_schema.clone();
        let candidate_profile = rocks_candidate_profile.clone();
        verify_historical_native_corpus(candidate_schema.clone(), current_producer_native_corpus_pack, move || {
            let families = candidate_schema.column_families();
            let refs = families.iter().map(String::as_str).collect::<Vec<_>>();
            YieldingStorage::wrap(
                ImmediateRocksDbStorage::open_with_durability_and_codec_profile(
                    &candidate_root,
                    &refs,
                    RocksDurability::FullSync,
                    &candidate_profile,
                )
                .expect("current RocksDB adapter opens exported candidate corpus"),
            )
        });
    }, move || {
        assert_native_corpus_candidate_is_staged(
            &rocks_live_path_for_publish,
            &rocks_candidate_archive,
            "RocksDB archive",
        );
        if let Some(requested) = &requested_rocks_archive {
            publish_verified_native_corpus_candidate(&rocks_candidate_archive, requested)
                .expect("atomically publish verified RocksDB candidate archive");
        }
    });

    let sqlite_directory = tempfile::tempdir().expect("create SQLite corpus directory");
    let sqlite_path = sqlite_directory.path().join("jazz.sqlite");
    let sqlite_schema = schema;
    let sqlite_open_path = sqlite_path.clone();
    let sqlite_wrong_path = sqlite_path.clone();
    let sqlite_live_path_for_verification = sqlite_path.clone();
    let sqlite_live_path_for_publish = sqlite_path.clone();
    let sqlite_wrong_schema = sqlite_schema.clone();
    let sqlite_candidate_directory = private_native_corpus_staging_root("sqlite");
    let sqlite_candidate_path = sqlite_candidate_directory.path().join("epoch-1-native-jazz.sqlite");
    let requested_sqlite_fixture_path = std::env::var_os("JAZZ_NATIVE_CORPUS_SQLITE_OUT")
        .map(std::path::PathBuf::from);
    let sqlite_candidate_output = sqlite_candidate_path.clone();
    let sqlite_candidate_verify_path = sqlite_candidate_path.clone();
    let sqlite_candidate_schema = sqlite_schema.clone();
    let sqlite_candidate_profile = profile.clone();
    let sqlite_receipt = exercise_native_corpus(sqlite_schema.clone(), &snapshot, move || {
        let families = sqlite_schema.column_families();
        let refs = families.iter().map(String::as_str).collect::<Vec<_>>();
        YieldingStorage::wrap(
            ImmediateSqliteStorage::open_with_durability_and_codec_profile(
                &sqlite_open_path,
                &refs,
                SqliteDurability::FullSync,
                &profile,
            )
            .expect("open SQLite corpus storage"),
        )
    }, move || {
        let families = sqlite_wrong_schema.column_families();
        let refs = families.iter().map(String::as_str).collect::<Vec<_>>();
        ImmediateSqliteStorage::open_with_durability_and_codec_profile(
            &sqlite_wrong_path,
            &refs,
            SqliteDurability::FullSync,
            &groove::storage::StorageCodecProfile::groove_epoch_1(),
        )
        .map(YieldingStorage::wrap)
    }, move || {
        assert_ne!(
            sqlite_candidate_output.parent(),
            sqlite_path.parent(),
            "SQLite candidate must be staged outside the live producer root"
        );
        std::fs::copy(&sqlite_path, &sqlite_candidate_output)
            .expect("copy SQLite candidate corpus store");
    }, move || {
        assert_native_corpus_candidate_is_staged(
            &sqlite_live_path_for_verification,
            &sqlite_candidate_verify_path,
            "SQLite image",
        );
        let verification_directory = tempfile::tempdir()
            .expect("create fresh SQLite candidate verification directory");
        let verification_path = verification_directory.path().join("candidate.sqlite");
        let bytes = std::fs::read(&sqlite_candidate_verify_path)
            .expect("read exported SQLite candidate");
        materialize_native_sqlite_bytes(&verification_path, &bytes)
            .expect("materialize exported SQLite candidate at fresh path");
        inspect_native_sqlite_candidate(&verification_path)
            .expect("exported SQLite candidate has readable durable rows");
        let candidate_schema = sqlite_candidate_schema.clone();
        let candidate_profile = sqlite_candidate_profile.clone();
        verify_historical_native_corpus(candidate_schema.clone(), current_producer_native_corpus_pack, move || {
            let families = candidate_schema.column_families();
            let refs = families.iter().map(String::as_str).collect::<Vec<_>>();
            YieldingStorage::wrap(
                ImmediateSqliteStorage::open_with_durability_and_codec_profile(
                    &verification_path,
                    &refs,
                    SqliteDurability::FullSync,
                    &candidate_profile,
                )
                .expect("current SQLite adapter opens exported candidate corpus"),
            )
        });
    }, move || {
        assert_native_corpus_candidate_is_staged(
            &sqlite_live_path_for_publish,
            &sqlite_candidate_path,
            "SQLite image",
        );
        if let Some(requested) = &requested_sqlite_fixture_path {
            publish_verified_native_corpus_candidate(&sqlite_candidate_path, requested)
                .expect("atomically publish verified SQLite candidate corpus store");
        }
    });

    assert_eq!(
        rocks_receipt.stores.get(groove::db::LARGE_VALUE_METADATA_CF),
        sqlite_receipt.stores.get(groove::db::LARGE_VALUE_METADATA_CF),
        "SQLite and RocksDB agree on the canonical indirect-tree and lifecycle metadata; raw chunk-plane bytes remain backend-owned physical fixture data"
    );
    assert_same_native_corpus(
        &rocks_receipt,
        &sqlite_receipt,
        "the native adapters must preserve the same canonical Jazz logical pack",
    );
    if let Some(path) = std::env::var_os("JAZZ_NATIVE_CORPUS_PACK_OUT") {
        // The logical pack is also a candidate output: keep it private until
        // this complete producer receipt has finished, and never overwrite a
        // previously reviewed pack by accident.
        let staging_root = private_native_corpus_staging_root("logical-pack");
        let candidate = staging_root.path().join("epoch-1-native-jazz-corpus.pack");
        std::fs::write(&candidate, native_corpus_pack(&rocks_receipt))
            .expect("stage requested native corpus logical pack");
        publish_verified_native_corpus_candidate(&candidate, std::path::Path::new(&path))
            .expect("publish verified native corpus logical pack without overwrite");
    }
    if std::env::var_os("JAZZ_NATIVE_CORPUS_PACK_OUT").is_none() {
        assert_eq!(
            native_corpus_checksum(&rocks_receipt),
            CURRENT_PRODUCER_NATIVE_CORPUS_RECEIPT_SHA256,
            "a producer/codecs change must explicitly update the reviewed current-producer receipt"
        );
        assert_eq!(
            native_corpus_pack(&rocks_receipt),
            current_producer_native_corpus_pack(),
            "the current producer must reproduce its reviewed backend-neutral logical receipt"
        );
    }
}

/// The committed SQLite and RocksDB byte fixtures are deliberately verified
/// independently from the live producer above. This is the compatibility
/// direction that matters at a later epoch: current code must open a store
/// created by the pinned producer, not merely agree with a store it just made.
#[test]
fn committed_native_jazz_physical_corpus_reopens_and_accepts_current_writes() {
    let schema = native_corpus_schema();
    let profile = epoch_1_storage_codec_profile().expect("closed Jazz profile");

    let sqlite_directory = tempfile::tempdir().expect("create SQLite fixture directory");
    let sqlite_path = sqlite_directory.path().join("epoch-1-native-jazz.sqlite");
    materialize_native_sqlite_fixture_with_hashes(&sqlite_path, CURRENT_NATIVE_SQLITE_BASE64, CURRENT_NATIVE_SQLITE_ARCHIVE_SHA256, CURRENT_NATIVE_SQLITE_SHA256)
        .expect("materialize checksum-guarded SQLite corpus");
    {
        // This first physical inspection is read-only and intentionally below
        // the Jazz/Groove adapter. It proves the committed file is a SQLite
        // store with data before current code gets an opportunity to create a
        // journal or a metadata marker.
        let connection = rusqlite::Connection::open_with_flags(
            &sqlite_path,
            rusqlite::OpenFlags::SQLITE_OPEN_READ_ONLY,
        )
        .expect("open committed SQLite corpus read-only");
        let rows: u64 = connection
            .query_row("SELECT COUNT(*) FROM kv", [], |row| row.get(0))
            .expect("read committed SQLite key/value rows");
        assert!(rows > 0, "committed SQLite corpus contains durable rows");
    }
    let sqlite_schema = schema.clone();
    let sqlite_profile = profile.clone();
    let sqlite_open_path = sqlite_path.clone();
    verify_historical_native_corpus(sqlite_schema.clone(), current_producer_native_corpus_pack, move || {
        let families = sqlite_schema.column_families();
        let refs = families.iter().map(String::as_str).collect::<Vec<_>>();
        YieldingStorage::wrap(
            ImmediateSqliteStorage::open_with_durability_and_codec_profile(
                &sqlite_open_path,
                &refs,
                SqliteDurability::FullSync,
                &sqlite_profile,
            )
            .expect("current SQLite adapter opens committed native corpus"),
        )
    });

    let rocks_directory = tempfile::tempdir().expect("create RocksDB fixture directory");
    let rocks_path = unpack_native_rocksdb_archive(rocks_directory.path(), &decode_native_physical_fixture(CURRENT_NATIVE_ROCKSDB_BASE64, CURRENT_NATIVE_ROCKSDB_SHA256, "current RocksDB").unwrap())
    .expect("extract checksum-guarded RocksDB corpus");
    {
        let options = rocksdb::Options::default();
        let families = rocksdb::DB::list_cf(&options, &rocks_path)
            .expect("list committed RocksDB column families");
        let read_only = rocksdb::DB::open_cf_for_read_only(&options, &rocks_path, &families, false)
            .expect("open committed RocksDB corpus read-only");
        assert!(
            families.iter().any(|family| family == "__groove_storage_internal_v1"),
            "committed RocksDB corpus retains Groove's immutable internal family"
        );
        let rows = families
            .iter()
            .filter_map(|family| read_only.cf_handle(family))
            .map(|family| {
                read_only
                    .iterator_cf(family, rocksdb::IteratorMode::Start)
                    .count()
            })
            .sum::<usize>();
        assert!(rows > 0, "committed RocksDB corpus contains durable rows");
    }
    let rocks_schema = schema;
    let rocks_open_path = rocks_path.clone();
    verify_historical_native_corpus(rocks_schema.clone(), current_producer_native_corpus_pack, move || {
        let families = rocks_schema.column_families();
        let refs = families.iter().map(String::as_str).collect::<Vec<_>>();
        YieldingStorage::wrap(
            ImmediateRocksDbStorage::open_with_durability_and_codec_profile(
                &rocks_open_path,
                &refs,
                RocksDurability::FullSync,
                &profile,
            )
            .expect("current RocksDB adapter opens committed native corpus"),
        )
    });
}

#[test]
fn retired_result_codec_profiles_reject_historical_native_roots() {
    // Internal physical admission receipt: no fake historical codec profile.
    let historical = epoch_1_native_corpus_pack();
    assert!(historical.contains("store\tjazz_settled_result_members\n"));
    let schema = native_corpus_schema();
    let profile = epoch_1_storage_codec_profile().unwrap();
    let families = schema.column_families();
    let refs = families.iter().map(String::as_str).collect::<Vec<_>>();
    let sqlite_dir = tempfile::tempdir().unwrap();
    let sqlite_path = sqlite_dir.path().join("historical.sqlite");
    materialize_native_sqlite_fixture(&sqlite_path, EPOCH_1_NATIVE_SQLITE_BASE64).unwrap();
    let sqlite_before = std::fs::read(&sqlite_path).unwrap();
    let sqlite_error = ImmediateSqliteStorage::open_with_durability_and_codec_profile(&sqlite_path, &refs, SqliteDurability::FullSync, &profile).err().expect("retired SQLite profile must reject");
    assert!(
        matches!(sqlite_error, groove::storage::Error::InvalidStorageLayout(ref message) if message.contains("storage manifest is inconsistent")),
        "historical SQLite root must fail closed during manifest admission: {sqlite_error}"
    );
    assert_eq!(std::fs::read(&sqlite_path).unwrap(), sqlite_before);
    let rocks_dir = tempfile::tempdir().unwrap();
    let rocks_path = unpack_native_rocksdb_fixture(rocks_dir.path(), EPOCH_1_NATIVE_ROCKSDB_BASE64).unwrap();
    let rocks_error = ImmediateRocksDbStorage::open_with_durability_and_codec_profile(&rocks_path, &refs, RocksDurability::FullSync, &profile).err().expect("retired RocksDB profile must reject");
    assert!(
        matches!(rocks_error, groove::storage::Error::InvalidStorageLayout(ref message) if message.contains("unmarked non-empty RocksDB store cannot be opened as raw-v1")),
        "historical RocksDB root must fail closed before ordinary data admission: {rocks_error}"
    );
}

#[test]
fn committed_native_jazz_physical_corpus_rejects_corruption_before_materialization() {
    let sqlite_root = tempfile::tempdir().expect("create SQLite corruption root");
    let sqlite_target = sqlite_root.path().join("must-not-exist.sqlite");
    let corrupt_sqlite = EPOCH_1_NATIVE_SQLITE_BASE64.replacen('A', "B", 1);
    assert!(
        materialize_native_sqlite_fixture(&sqlite_target, &corrupt_sqlite).is_err(),
        "a corrupt authoritative SQLite payload is rejected"
    );
    assert!(
        !sqlite_target.exists(),
        "SQLite checksum rejection precedes fixture materialization"
    );

    let rocks_root = tempfile::tempdir().expect("create RocksDB corruption root");
    let rocks_target = rocks_root.path().join("must-not-exist");
    let corrupt_rocks = EPOCH_1_NATIVE_ROCKSDB_BASE64.replacen('A', "B", 1);
    assert!(
        unpack_native_rocksdb_fixture(&rocks_target, &corrupt_rocks).is_err(),
        "a corrupt authoritative RocksDB payload is rejected"
    );
    assert!(
        !rocks_target.exists(),
        "RocksDB checksum rejection precedes archive extraction"
    );
}

/// The regeneration path must validate physical *candidates*, not just compare
/// an output checksum or reopen the live producer root.  These planted broken,
/// truncated, and wrongly-rooted exports exercise the exact fresh-copy/unpack
/// admission boundary used by the producer above.
#[test]
fn native_jazz_corpus_candidate_roundtrip_rejects_broken_exports() {
    let output_root = tempfile::tempdir().expect("create requested-output root");
    let requested_output = output_root.path().join("must-not-publish.sqlite");
    let sqlite_root = tempfile::tempdir().expect("create broken SQLite candidate root");
    let sqlite_path = sqlite_root.path().join("broken.sqlite");
    materialize_native_sqlite_bytes(&sqlite_path, b"not a SQLite database")
        .expect("write deliberately broken SQLite candidate");
    assert!(
        verify_then_publish_native_corpus_candidate(
            || inspect_native_sqlite_candidate(&sqlite_path),
            &sqlite_path,
            &requested_output,
        )
        .is_err(),
        "a broken SQLite export must fail before Jazz could create a replacement store"
    );
    assert!(
        !requested_output.exists(),
        "a broken SQLite candidate is never published to a requested output"
    );

    let archive = decode_native_physical_fixture(
        EPOCH_1_NATIVE_ROCKSDB_BASE64,
        EPOCH_1_NATIVE_ROCKSDB_SHA256,
        "RocksDB",
    )
    .expect("decode pinned archive for truncation sensitivity");
    let truncated_root = tempfile::tempdir().expect("create truncated archive root");
    let truncated_candidate = truncated_root.path().join("truncated-candidate");
    std::fs::write(&truncated_candidate, &archive[..archive.len() / 2])
        .expect("stage truncated archive bytes");
    assert!(
        verify_then_publish_native_corpus_candidate(
            || {
                unpack_native_rocksdb_archive(
                    truncated_root.path(),
                    &std::fs::read(&truncated_candidate).map_err(|error| error.to_string())?,
                )
                .map(|_| ())
            },
            &truncated_candidate,
            &requested_output,
        )
        .is_err(),
        "a truncated RocksDB export must not be accepted as a candidate"
    );
    assert!(
        !requested_output.exists(),
        "a truncated candidate is never published to a requested output"
    );

    let mut wrong_archive = Vec::new();
    {
        let encoder = flate2::write::GzEncoder::new(&mut wrong_archive, flate2::Compression::fast());
        let mut tar = tar::Builder::new(encoder);
        let mut header = tar::Header::new_gnu();
        header.set_size(4);
        header.set_mode(0o644);
        header.set_cksum();
        tar.append_data(&mut header, "wrong-root/not-a-rocksdb", &b"nope"[..])
            .expect("build deliberately wrong-root candidate archive");
        tar.into_inner()
            .expect("finish wrong-root candidate tar")
            .finish()
            .expect("finish wrong-root candidate gzip");
    }
    let wrong_root = tempfile::tempdir().expect("create wrong-root archive target");
    let wrong_candidate = wrong_root.path().join("wrong-root-candidate");
    std::fs::write(&wrong_candidate, &wrong_archive).expect("stage wrong-root archive bytes");
    assert!(
        verify_then_publish_native_corpus_candidate(
            || {
                unpack_native_rocksdb_archive(
                    wrong_root.path(),
                    &std::fs::read(&wrong_candidate).map_err(|error| error.to_string())?,
                )
                .map(|_| ())
            },
            &wrong_candidate,
            &requested_output,
        )
        .is_err(),
        "an archive with the wrong database root must not be accepted as a candidate"
    );
    assert!(
        !requested_output.exists(),
        "a wrong-root candidate is never published to a requested output"
    );

    let candidate = output_root.path().join("verified-candidate");
    std::fs::write(&candidate, b"verified bytes").expect("stage a verified candidate");
    verify_then_publish_native_corpus_candidate(|| Ok(()), &candidate, &requested_output)
        .expect("publish only after the independent verifier succeeded");
    assert_eq!(
        std::fs::read(&requested_output).expect("read atomically published output"),
        b"verified bytes",
        "the requested output is populated only by a staged verified candidate"
    );
}

/// Staging is a physical boundary, not just a different spelling of the live
/// path.  In particular, a future candidate may not be placed below a live
/// root before it exists, and existing dot, symlink, and hard-link aliases all
/// fail before a verifier could accidentally reopen the producer.
#[test]
fn native_jazz_corpus_staging_rejects_normalized_and_physical_aliases() {
    let root = tempfile::tempdir().expect("create corpus alias root");
    let live_root = root.path().join("live-root");
    let staging_root = root.path().join("staging-root");
    std::fs::create_dir_all(&live_root).expect("create live root");
    std::fs::create_dir(&staging_root).expect("create staging root");
    let live = live_root.join("live.sqlite");
    std::fs::write(&live, b"live corpus bytes").expect("create live SQLite image");

    assert_staged_path_is_distinct(&live, &staging_root.join("not-yet-created.sqlite"), "SQLite")
        .expect("a nonexistent direct child of an independent staging root is safe");
    assert!(
        assert_staged_path_is_distinct(&live, &live_root.join("not-yet-created.sqlite"), "SQLite")
            .is_err(),
        "a not-yet-created candidate below the live root is rejected"
    );
    assert!(
        assert_staged_path_is_distinct(
            &live,
            &live_root.join(".").join("live.sqlite"),
            "SQLite",
        )
        .is_err(),
        "a dot-path spelling of the live image is rejected"
    );

    let rocks_live = live_root.join("rocksdb-live");
    std::fs::create_dir(&rocks_live).expect("create live RocksDB root");
    let live_sst = rocks_live.join("000001.sst");
    std::fs::write(&live_sst, b"live RocksDB SST bytes").expect("create live SST member");

    #[cfg(unix)]
    {
        use std::os::unix::fs::symlink;
        let symlink_alias = staging_root.join("symlink.sqlite");
        symlink(&live, &symlink_alias).expect("create SQLite symlink alias");
        assert!(
            assert_staged_path_is_distinct(&live, &symlink_alias, "SQLite").is_err(),
            "a SQLite symlink alias is rejected"
        );

        let hardlink_alias = staging_root.join("hardlink.sqlite");
        std::fs::hard_link(&live, &hardlink_alias).expect("create SQLite hard-link alias");
        assert!(
            assert_staged_path_is_distinct(&live, &hardlink_alias, "SQLite").is_err(),
            "a SQLite hard-link alias is rejected by file identity"
        );

        let rocks_alias_root = root.path().join("rocksdb-alias-root");
        symlink(&rocks_live, &rocks_alias_root).expect("create RocksDB root symlink alias");
        assert!(
            assert_staged_path_is_distinct(
                &rocks_live,
                &rocks_alias_root.join("candidate.tar.gz"),
                "RocksDB",
            )
            .is_err(),
            "a candidate below a symlink alias of the live RocksDB root is rejected"
        );

    }

    #[cfg(any(unix, windows))]
    {
        let hardlinked_sst_candidate = staging_root.join("candidate-000001.sst");
        std::fs::hard_link(&live_sst, &hardlinked_sst_candidate)
            .expect("plant a staged file linked to a live RocksDB SST");
        assert!(
            assert_staged_path_is_distinct(&rocks_live, &hardlinked_sst_candidate, "RocksDB").is_err(),
            "a candidate hard-linked to any live RocksDB member is rejected, not only an alias of the root"
        );
    }
}

/// Publication is create-new only.  A regeneration never overwrites an old
/// reviewed artifact; a maintainer explicitly chooses a fresh path or removes
/// the old one.  A failed copy also leaves no partial private file behind.
#[test]
fn native_jazz_corpus_publication_rejects_existing_output_and_preserves_it() {
    let root = tempfile::tempdir().expect("create publication failure root");
    let candidate = root.path().join("candidate.sqlite");
    let requested = root.path().join("published.sqlite");
    std::fs::write(&candidate, b"complete verified candidate").expect("write candidate");
    std::fs::write(&requested, b"previous published corpus").expect("write old destination");

    let error = publish_verified_native_corpus_candidate_with_copy(
        &candidate,
        &requested,
        |_candidate, _temporary| panic!("an existing output must reject before copying"),
    )
    .expect_err("an existing output must reject before any staged copy");
    assert!(error.contains("already exists"));
    assert_eq!(
        std::fs::read(&requested).expect("read existing destination after failed publication"),
        b"previous published corpus",
        "a rejected regeneration leaves the pre-existing destination byte-for-byte intact"
    );
    let temporary_prefix = ".published.sqlite.native-corpus-staging-";
    assert!(
        std::fs::read_dir(root.path())
            .expect("list publication root")
            .all(|entry| {
                !entry
                    .expect("read publication-root entry")
                    .file_name()
                    .to_string_lossy()
                    .starts_with(temporary_prefix)
            }),
        "rejected publication does not create a private output file"
    );

    assert!(
        publish_verified_native_corpus_candidate(&candidate, &candidate).is_err(),
        "a requested output cannot be the staged candidate itself"
    );

    #[cfg(unix)]
    {
        use std::os::unix::fs::symlink;
        let symlink_destination = root.path().join("candidate-symlink.sqlite");
        symlink(&candidate, &symlink_destination)
            .expect("create publication destination symlink alias");
        assert!(
            publish_verified_native_corpus_candidate(&candidate, &symlink_destination).is_err(),
            "a symlink alias cannot be used as the publication destination"
        );

        let alias_destination = root.path().join("candidate-hardlink.sqlite");
        std::fs::hard_link(&candidate, &alias_destination)
            .expect("create publication destination hard-link alias");
        assert!(
            publish_verified_native_corpus_candidate(&candidate, &alias_destination).is_err(),
            "a physical hard-link alias cannot be used as the publication destination"
        );
    }
}

#[test]
fn native_jazz_corpus_publication_creates_a_fresh_output_without_overwrite() {
    let root = tempfile::tempdir().expect("create publication root");
    let candidate = root.path().join("candidate.sqlite");
    let requested = root.path().join("fresh.sqlite");
    std::fs::write(&candidate, b"complete verified candidate").expect("write candidate");

    publish_verified_native_corpus_candidate(&candidate, &requested)
        .expect("a fresh requested output is atomically created");
    assert_eq!(
        std::fs::read(&requested).expect("read fresh requested output"),
        b"complete verified candidate"
    );
    assert!(
        publish_verified_native_corpus_candidate(&candidate, &requested).is_err(),
        "a second regeneration must not silently overwrite the first output"
    );
}

/// The regeneration verifier must not be able to fall back to the still-live
/// producer.  This mirrors an export/stage workflow, removes the original
/// source, and then runs the full current-code historical receipt solely from
/// the staged SQLite bytes.
#[test]
fn native_jazz_corpus_staged_candidate_survives_live_producer_removal() {
    let source_root = tempfile::tempdir().expect("create live producer root");
    let source = source_root.path().join("live.sqlite");
    materialize_native_sqlite_fixture_with_hashes(&source, CURRENT_NATIVE_SQLITE_BASE64, CURRENT_NATIVE_SQLITE_ARCHIVE_SHA256, CURRENT_NATIVE_SQLITE_SHA256)
        .expect("materialize an independent live producer fixture");
    let staging_root = tempfile::tempdir().expect("create private staging root");
    let candidate = staging_root.path().join("candidate.sqlite");
    std::fs::copy(&source, &candidate).expect("stage SQLite candidate outside live root");
    assert_native_corpus_candidate_is_staged(&source, &candidate, "SQLite image");
    std::fs::remove_file(&source).expect("remove live producer after staging");

    let verification_root = tempfile::tempdir().expect("create fresh verifier root");
    let verification_path = verification_root.path().join("verified.sqlite");
    let candidate_bytes = std::fs::read(&candidate).expect("read staged candidate only");
    materialize_native_sqlite_bytes(&verification_path, &candidate_bytes)
        .expect("materialize staged candidate into a new root");
    inspect_native_sqlite_candidate(&verification_path)
        .expect("staged candidate remains physically valid after live source removal");
    let schema = native_corpus_schema();
    let profile = epoch_1_storage_codec_profile().expect("closed Jazz profile");
    verify_historical_native_corpus(schema.clone(), current_producer_native_corpus_pack, move || {
        let families = schema.column_families();
        let refs = families.iter().map(String::as_str).collect::<Vec<_>>();
        YieldingStorage::wrap(
            ImmediateSqliteStorage::open_with_durability_and_codec_profile(
                &verification_path,
                &refs,
                SqliteDurability::FullSync,
                &profile,
            )
            .expect("current Jazz opens staged candidate without the producer"),
        )
    });
}

/// Proves the frozen digest actually observes authored application content.
///
/// alice repeats the deterministic producer twice, changing only one branch
/// row's title, then repeats it again changing only an independent note body.
/// Both changes must perturb the logical pack; otherwise the receipt has
/// accidentally fallen back to system metadata only.
#[test]
fn native_jazz_corpus_digest_is_sensitive_to_application_row_bytes() {
    let baseline = in_memory_native_corpus_receipt("settlement baseline", "independent table");
    let changed_branch = in_memory_native_corpus_receipt("changed branch title", "independent table");
    let changed_note = in_memory_native_corpus_receipt("settlement baseline", "changed note body");

    assert_ne!(native_corpus_checksum(&baseline), native_corpus_checksum(&changed_branch));
    assert_ne!(native_corpus_checksum(&baseline), native_corpus_checksum(&changed_note));
}

/// The system transaction records also contain authored values, so a checksum
/// change alone cannot prove that the independent physical application scan is
/// still present.  Removing that entire scan must fail the authority-manifest
/// closure assertion before any digest comparison can accidentally pass.
#[test]
fn native_jazz_corpus_rejects_a_receipt_omitting_all_physical_application_families() {
    let schema = native_corpus_schema();
    let families = schema.column_families();
    let refs = families.iter().map(String::as_str).collect::<Vec<_>>();
    let storage = MemoryStorage::new(&refs).expect("open omission-sensitivity store");
    let snapshot = native_corpus_authority_snapshot(&schema);
    let mut node = crate::db::block_on(NodeState::new_catalogue_uninitialized(node(0xc0), storage))
        .expect("open omission-sensitivity node");
    node.apply_trusted_catalogue_snapshot_settled(snapshot.clone())
        .expect("install omission-sensitivity authority snapshot");
    seed_native_corpus(&mut node, "settlement baseline", "independent table");
    publish_native_corpus_lineage(&mut node, &snapshot);
    seed_native_corpus_settled_query_state(&mut node);
    let receipt = native_corpus_receipt(&node, &schema);
    assert_native_corpus_has_required_families(&mut node, &receipt);

    let mut omitted = receipt.clone();
    for store in native_corpus_required_application_stores(&node) {
        omitted.stores.remove(&store);
    }
    omitted.stores.remove(groove::db::LARGE_VALUE_METADATA_CF);
    let omission = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        assert_native_corpus_has_required_families(&mut node, &omitted);
    }));
    assert!(
        omission.is_err(),
        "removing every physical application family and the engine-owned large-value metadata plane must fail even though transaction records remain"
    );
}
