// Generated by dev/artifacts/build.mjs.
export const EXPECTED_NATIVE_ARTIFACT_FINGERPRINTS = {
  napi: "1b4fe4f061cacd8fc54c5ada40b46774d561383b7efdfefeb688b6824ccccc4d",
  wasm: "99cc7766e55ddcf08ef1e3b3a0bf7179a47ba1b36349869e47babe05f73d2056",
} as const;
