name: Get and Build Source Code

inputs:
  cache:
    description: 'Enable caching'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Enable latestcorepack
      shell: bash
      run: |
        echo "Before: corepack version => $(corepack --version || echo 'not installed')"
        npm install -g corepack@latest
        echo "After : corepack version => $(corepack --version)"
        corepack enable
        pnpm --version

    - name: Install Node.js
      uses: useblacksmith/setup-node@v5
      with:
        node-version-file: '.node-version'
        cache: ${{ inputs.cache == 'true' && 'pnpm' || '' }}

    - name: Get pnpm store directory
      if: inputs.cache == 'true'
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: useblacksmith/cache@v5
      if: inputs.cache == 'true'
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
