config:
  jazz-cloud2:allowedAccountId: "327252143262"
  jazz-cloud2:containerImageRepository: 851454408348.dkr.ecr.us-east-2.amazonaws.com/jazz2-cloud-server
  jazz-cloud2:containerImageTag: "sha-28a2251"
  jazz-cloud2:dataVolumeSizeGiB: "100"
  jazz-cloud2:domainName: cloud2.aws.cloud.jazz.tools
  jazz-cloud2:instanceType: t3.large
  jazz-cloud2:internalApiSecret:
    secure: AAABAHHx42qFWIAchAmkc2rjaBn0weWzgSX7LzoVldGlQqbjA1ijwR65vkhW4wyrRBsTJ6eeJ/81TjBi8RfSCHRT90bvsWL4ypEmcWOia2xO0BxOKdV03r8QeDYD/tO/
  jazz-cloud2:region: us-east-2
  jazz-cloud2:route53DelegationRoleArn: arn:aws:iam::851454408348:role/jazz-route53-delegation-staging
  jazz-cloud2:secretHashKey:
    secure: AAABAK+wnr0DIWKclfTAqNmbwZkJlwVqGV1e+w3X6Qobi5Lk3xrJ/qAgz9plz/bA1KevIc7cWUIFNUhwcGEd9yw0W5mcFn7hkX/ff1cTnnePthGvmVuwWf3P5htQ8tr0
