package jazzgo

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"sort"
	"strings"
	"unicode"
)

type GenerateOptions struct {
	PackageName string
	Schema      Schema
}

type TableDefinition struct {
	Name    string
	Columns []ColumnDefinition
}

type ColumnDefinition struct {
	Name       string
	Type       string
	Nullable   bool
	References string
}

func Generate(opts GenerateOptions) (string, error) {
	if opts.PackageName == "" {
		return "", errors.New("package name is required")
	}
	if len(opts.Schema) == 0 {
		return "", errors.New("schema is required")
	}

	tableNames := make([]string, 0, len(opts.Schema))
	imports := map[string]struct{}{}
	for tableName, table := range opts.Schema {
		tableNames = append(tableNames, tableName)
		rowType := singularTypeName(tableName)
		for _, column := range table.Columns {
			if strings.Contains(goTypeForColumn(column, rowType, false), "json.RawMessage") {
				imports["encoding/json"] = struct{}{}
			}
		}
	}
	sort.Strings(tableNames)

	var out bytes.Buffer
	out.WriteString("// Code generated by jazzgo-gen. DO NOT EDIT.\n")
	out.WriteString("package " + opts.PackageName + "\n\n")

	if len(imports) > 0 {
		importList := make([]string, 0, len(imports))
		for path := range imports {
			importList = append(importList, path)
		}
		sort.Strings(importList)
		out.WriteString("import (\n")
		for _, path := range importList {
			out.WriteString(fmt.Sprintf("\t%q\n", path))
		}
		out.WriteString(")\n\n")
	}

	out.WriteString("type TableDefinition struct {\n")
	out.WriteString("\tName string\n")
	out.WriteString("\tColumns []ColumnDefinition\n")
	out.WriteString("}\n\n")
	out.WriteString("type ColumnDefinition struct {\n")
	out.WriteString("\tName string\n")
	out.WriteString("\tType string\n")
	out.WriteString("\tNullable bool\n")
	out.WriteString("\tReferences string\n")
	out.WriteString("}\n\n")

	for _, tableName := range tableNames {
		table := opts.Schema[tableName]
		rowType := singularTypeName(tableName)
		insertType := rowType + "Insert"

		for _, column := range table.Columns {
			if column.ColumnType.Type == "Enum" {
				writeEnum(&out, rowType, column)
			}
		}

		out.WriteString(fmt.Sprintf("type %s struct {\n", rowType))
		out.WriteString("\tID string `json:\"id\"`\n")
		for _, column := range table.Columns {
			out.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n",
				fieldName(column.Name),
				goTypeForColumn(column, rowType, false),
				column.Name,
			))
		}
		out.WriteString("}\n\n")

		out.WriteString(fmt.Sprintf("type %s struct {\n", insertType))
		for _, column := range table.Columns {
			out.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n",
				fieldName(column.Name),
				goTypeForColumn(column, rowType, true),
				column.Name,
			))
		}
		out.WriteString("}\n\n")

		out.WriteString(fmt.Sprintf("var %sTable = TableDefinition{\n", pluralTypeName(tableName)))
		out.WriteString(fmt.Sprintf("\tName: %q,\n", tableName))
		out.WriteString("\tColumns: []ColumnDefinition{\n")
		for _, column := range table.Columns {
			out.WriteString("\t\t{\n")
			out.WriteString(fmt.Sprintf("\t\t\tName: %q,\n", column.Name))
			out.WriteString(fmt.Sprintf("\t\t\tType: %q,\n", column.ColumnType.Type))
			out.WriteString(fmt.Sprintf("\t\t\tNullable: %t,\n", column.Nullable))
			out.WriteString(fmt.Sprintf("\t\t\tReferences: %q,\n", column.References))
			out.WriteString("\t\t},\n")
		}
		out.WriteString("\t},\n")
		out.WriteString("}\n\n")
	}

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return "", fmt.Errorf("format generated code: %w\n%s", err, out.String())
	}
	return string(formatted), nil
}

func writeEnum(out *bytes.Buffer, rowType string, column ColumnDescriptor) {
	typeName := rowType + fieldName(column.Name)
	out.WriteString(fmt.Sprintf("type %s string\n\n", typeName))
	out.WriteString("const (\n")
	for _, variant := range column.ColumnType.Variants {
		out.WriteString(fmt.Sprintf("\t%s%s %s = %q\n",
			typeName,
			fieldName(variant),
			typeName,
			variant,
		))
	}
	out.WriteString(")\n\n")
}

func goTypeForColumn(column ColumnDescriptor, rowType string, insert bool) string {
	return resolveGeneratedType(column, rowType, insert)
}

func resolveGeneratedType(column ColumnDescriptor, rowType string, insert bool) string {
	var base string
	switch column.ColumnType.Type {
	case "Text", "Uuid":
		base = "string"
	case "Integer", "BigInt", "Timestamp":
		base = "int64"
	case "Double":
		base = "float64"
	case "Boolean":
		base = "bool"
	case "Bytea":
		base = "[]byte"
	case "Json", "Row":
		base = "json.RawMessage"
	case "Enum":
		base = rowType + fieldName(column.Name)
	case "Array":
		element := ColumnDescriptor{Name: column.Name, ColumnType: *column.ColumnType.Element}
		base = "[]" + resolveGeneratedType(element, rowType, insert)
	default:
		base = "any"
	}
	if column.Nullable && !strings.HasPrefix(base, "[]") {
		return "*" + base
	}
	return base
}

func singularTypeName(tableName string) string {
	trimmed := strings.TrimSpace(tableName)
	trimmed = strings.TrimSuffix(trimmed, "s")
	return toExported(trimmed)
}

func pluralTypeName(tableName string) string {
	return toExported(tableName)
}

func fieldName(column string) string {
	return toExported(column)
}

func toExported(value string) string {
	parts := splitIdentifier(value)
	var out strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		lower := strings.ToLower(part)
		switch lower {
		case "id":
			out.WriteString("ID")
		case "url":
			out.WriteString("URL")
		case "ws":
			out.WriteString("WS")
		case "http":
			out.WriteString("HTTP")
		case "json":
			out.WriteString("JSON")
		default:
			runes := []rune(lower)
			runes[0] = unicode.ToUpper(runes[0])
			out.WriteString(string(runes))
		}
	}
	return out.String()
}

func splitIdentifier(value string) []string {
	var parts []string
	var current []rune

	flush := func() {
		if len(current) == 0 {
			return
		}
		parts = append(parts, string(current))
		current = current[:0]
	}

	for i, r := range value {
		if r == '_' || r == '-' || unicode.IsSpace(r) {
			flush()
			continue
		}
		if i > 0 && unicode.IsUpper(r) && len(current) > 0 {
			prev := current[len(current)-1]
			if unicode.IsLower(prev) || unicode.IsDigit(prev) {
				flush()
			}
		}
		current = append(current, r)
	}
	flush()
	return parts
}
