-- Generated by @jazz/schema
-- DO NOT EDIT MANUALLY

CREATE TABLE User (
    name STRING NOT NULL,
    email STRING NOT NULL,
    avatar STRING
);

CREATE TABLE Folder (
    name STRING NOT NULL,
    owner REFERENCES User NOT NULL,
    parent REFERENCES Folder
);

CREATE TABLE Note (
    title STRING NOT NULL,
    content STRING NOT NULL,
    author REFERENCES User NOT NULL,
    folder REFERENCES Folder,
    createdAt I64 NOT NULL,
    updatedAt I64 NOT NULL
);

CREATE TABLE Tag (
    name STRING NOT NULL,
    color STRING NOT NULL
);
