// Generated by @jazz/schema
// DO NOT EDIT MANUALLY

/** ObjectId is a 128-bit unique identifier (UUIDv7) represented as a Base32 string */
export type ObjectId = string;

/** Base interface for all Groove rows */
export interface GrooveRow {
  id: ObjectId;
}

// === Depth types (specify which refs to load) ===

export type UserDepth = {};

export type FolderDepth = {
  owner?: true | UserDepth;
  parent?: true | FolderDepth;
};

export type NoteDepth = {
  author?: true | UserDepth;
  folder?: true | FolderDepth;
};

export type TagDepth = {};

// === Row types ===

/** User row from the User table */
export interface User extends GrooveRow {
  name: string;
  email: string;
  avatar: string | null;
}

/** Data for inserting a new User */
export interface UserInsert {
  name: string;
  email: string;
  avatar?: string | null;
}

/** User has no refs, so Loaded is the same as base type */
export type UserLoaded<D extends UserDepth = {}> = User;

/** Folder row from the Folder table */
export interface Folder extends GrooveRow {
  name: string;
  owner: ObjectId;
  parent: ObjectId | null;
}

/** Data for inserting a new Folder */
export interface FolderInsert {
  name: string;
  owner: ObjectId | User;
  parent?: ObjectId | Folder | null;
}

/** Folder with refs resolved based on depth parameter D */
export type FolderLoaded<D extends FolderDepth = {}> = {
  id: ObjectId;
  name: string;
  owner: 'owner' extends keyof D
    ? D['owner'] extends true
      ? User
      : D['owner'] extends object
        ? User
        : ObjectId
    : ObjectId;
  parent: 'parent' extends keyof D
    ? D['parent'] extends true
      ? Folder | null
      : D['parent'] extends object
        ? FolderLoaded<D['parent'] & FolderDepth> | null
        : ObjectId | null
    : ObjectId | null;
};

/** Note row from the Note table */
export interface Note extends GrooveRow {
  title: string;
  content: string;
  author: ObjectId;
  folder: ObjectId | null;
  createdAt: bigint;
  updatedAt: bigint;
}

/** Data for inserting a new Note */
export interface NoteInsert {
  title: string;
  content: string;
  author: ObjectId | User;
  folder?: ObjectId | Folder | null;
  createdAt: bigint;
  updatedAt: bigint;
}

/** Note with refs resolved based on depth parameter D */
export type NoteLoaded<D extends NoteDepth = {}> = {
  id: ObjectId;
  title: string;
  content: string;
  author: 'author' extends keyof D
    ? D['author'] extends true
      ? User
      : D['author'] extends object
        ? User
        : ObjectId
    : ObjectId;
  folder: 'folder' extends keyof D
    ? D['folder'] extends true
      ? Folder | null
      : D['folder'] extends object
        ? FolderLoaded<D['folder'] & FolderDepth> | null
        : ObjectId | null
    : ObjectId | null;
  createdAt: bigint;
  updatedAt: bigint;
};

/** Tag row from the Tag table */
export interface Tag extends GrooveRow {
  name: string;
  color: string;
}

/** Data for inserting a new Tag */
export interface TagInsert {
  name: string;
  color: string;
}

/** Tag has no refs, so Loaded is the same as base type */
export type TagLoaded<D extends TagDepth = {}> = Tag;
