CREATE TABLE projects (
    name TEXT NOT NULL
);
ALTER TABLE todos ADD COLUMN parent UUID DEFAULT NULL;
ALTER TABLE todos ADD COLUMN project UUID DEFAULT NULL;
ALTER TABLE todos ADD COLUMN owner_id TEXT DEFAULT '';