packages:
  - "packages/*"
  - "examples/*"
  - "starters/*"
  - "tests/*"

catalog:
  "@biomejs/biome": 1.9.4
  typescript: 5.6.2
  vite: 6.3.5
  vitest: 3.1.3
  "@vitest/browser": 3.1.3
  "@vitest/coverage-istanbul": 3.1.3
  "@vitest/coverage-v8": 3.1.3
  "@vitest/ui": 3.1.3
