packages:
  - docs
  - packages/*
  - examples/*
  - examples/docs/*
  - crates
  - crates/groove-wasm
  - crates/groove-napi

ignoredBuiltDependencies:
  - blake3
  - lefthook

catalogs:
  default:
    vitest: 4.0.18
    "@vitest/browser": 4.0.18
    "@vitest/browser-playwright": 4.0.18
