packages:
  - docs
  - packages/*
  - examples/*
  - examples/docs/*
  - stress-tests/*
  - crates
  - crates/jazz-wasm
  - crates/jazz-napi
  - crates/jazz-rn

catalogs:
  default:
    "@sveltejs/vite-plugin-svelte": 7.0.0
    "@vitest/browser": 4.1.0
    "@vitest/browser-playwright": 4.1.0
    "@vitejs/plugin-react": 6.0.1
    "@vitejs/plugin-vue": 6.0.4
    typescript: 5.9.3
    vite: 8.0.1
    "vite-plugin-top-level-await": 1.6.0
    "vite-plugin-wasm": 3.6.0
    vitest: 4.1.0

ignoredBuiltDependencies:
  - blake3
  - lefthook
