packages:
  - 'packages/*'
  - 'examples/*'
  - 'starters/*'
  - 'tests/*'
  - 'crates/*'
  - 'crates/cojson-core-napi/npm/*'
  - 'crates/cojson-core-rn'
  - 'bench'

minimumReleaseAge: 1440 # 24 hours
catalogs:
  default:
    "@biomejs/biome": 2.1.3
    typescript: 5.6.2
    vite: 6.3.5
    vitest: 4.0.16
    "@vitest/browser-playwright":  4.0.16
    "@vitest/coverage-v8": 4.0.16
    "@vitest/ui": 4.0.16
  react:
    "react": "19.1.0"
    "react-dom": "19.1.0"
    "@types/react": "19.1.0"
    "@types/react-dom": "19.1.0"
  rn:
    "react-native": "0.81.5"
    "react": "19.1.0"
    "@react-native-community/cli": "19.1.0"
    "@react-native-community/cli-platform-android": "19.1.0"
    "@react-native-community/cli-platform-ios": "19.1.0"
    "@react-native/babel-preset": "0.81.5"
    "@react-native/eslint-config": "0.81.5"
    "@react-native/metro-config": "0.81.5"
    "@react-native/typescript-config": "0.81.5"
    "@types/react": "19.1.0"
  expo:
    "expo": "54.0.23"
    "react": "19.1.0"
  svelte:
    "@sveltejs/kit": "2.49.5"
    "@sveltejs/adapter-node": "5.5.1"
    "@sveltejs/vite-plugin-svelte": "^5.1.1"
    "svelte": "5.46.4"
    "svelte-check": "4.3.1"
onlyBuiltDependencies:
  - esbuild
  - '@tailwindcss/oxide'
