packages:
  - "packages/*"
  - "examples/*"
  - "starters/*"
  - "tests/*"

catalogs:
  default:
    "@biomejs/biome": 2.1.3
    typescript: 5.6.2
    vite: 6.3.5
    vitest: 3.2.4
    "@vitest/browser": 3.2.4
    "@vitest/coverage-istanbul": 3.2.4
    "@vitest/coverage-v8": 3.2.4
    "@vitest/ui": 3.2.4
  react:
    "react": "19.1.0"
    "react-dom": "19.1.0"
    "@types/react": "19.1.0"
    "@types/react-dom": "19.1.0"
  rn:
    "react-native": "0.80.0"
    "react": "19.1.0"
    "@react-native-community/cli": "19.0.0"
    "@react-native-community/cli-platform-android": "19.0.0"
    "@react-native-community/cli-platform-ios": "19.0.0"
    "@react-native/babel-preset": "0.80.0"
    "@react-native/eslint-config": "0.80.0"
    "@react-native/metro-config": "0.80.0"
    "@react-native/typescript-config": "0.80.0"
    "@types/react": "^19.1.0"
  expo:
    "expo": "54.0.0-canary-20250701-6a945c5"
    "expo-clipboard": "^7.1.4"
    "expo-crypto": "~14.1.5"
    "expo-linking": "~7.1.5"
    "expo-secure-store": "~14.2.3"
    "expo-sqlite": "~15.2.10"
    "expo-web-browser": "~14.2.0"
    "react-native": "0.80.0"
    "react": "19.1.0"
    "@types/react": "^19.0.10"
