/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class JazzServer {
  static start(options: { appId: string; backendSecret: string; adminSecret: string; port?: number; dataDir?: string; inMemory?: boolean; jwksUrl?: string; allowLocalFirstAuth?: boolean; upstreamUrl?: string; telemetryCollectorUrl?: string; schema?: Buffer | Uint8Array | number[] }): Promise<JazzServer>
  get appId(): string
  get url(): string
  get port(): number
  get dataDir(): string
  get backendSecret(): string
  get adminSecret(): string
  stop(): Promise<void>
}

export declare class NapiDb {
  static openMemory(schema: Uint8Array, config: Uint8Array): NapiDb
  static openPersistent(dataPath: string, schema: Uint8Array, config: Uint8Array): NapiDb
  /** Register and return a typed view backed by this same runtime owner. */
  registerSchema(schema: Uint8Array): NapiDb
  /**
   * Attach a schema view to an owner-wide mergeable batch without opening,
   * committing, or abandoning that batch.
   */
  attachMergeableTx(openBatchId: string): Tx
  /** Attach a schema view to an existing owner-wide exclusive batch. */
  attachExclusiveTx(openBatchId: string): Tx
  /** Begin one owner-wide batch without creating an owning per-schema Tx. */
  beginTransaction(openBatchId: string, kind: string, author?: Uint8Array | undefined | null): void
  /** Commit an owner-wide batch by id and optional kind. */
  commitTransaction(openBatchId: string, kind?: string | undefined | null): Write
  /** Roll back an owner-wide open batch by id. */
  rollbackTransaction(openBatchId: string): void
  setTickScheduler(callback: ((err: Error | null, arg: string) => void)): void
  onMutationError(callback: (event: any) => void): void
  prepareQuery(query: Uint8Array): PreparedQuery
  all(query: PreparedQuery, opts?: { tier?: string; local_updates?: string; propagation?: string; include_deleted?: boolean } | undefined | null): Uint8Array
  setIdentityClaims(author: Uint8Array, claims?: Record<string, unknown> | undefined | null): void
  allForIdentity(query: PreparedQuery, author: Uint8Array, opts?: { tier?: string; local_updates?: string; propagation?: string; include_deleted?: boolean } | undefined | null): Uint8Array
  allRelationSnapshot(query: PreparedQuery, opts?: { tier?: string; local_updates?: string; propagation?: string; include_deleted?: boolean } | undefined | null): Uint8Array
  allRelationSnapshotForIdentity(query: PreparedQuery, author: Uint8Array, opts?: { tier?: string; local_updates?: string; propagation?: string; include_deleted?: boolean } | undefined | null): Uint8Array
  allRelationQuery(queryJson: string, opts?: { tier?: string; local_updates?: string; propagation?: string; include_deleted?: boolean } | undefined | null): Uint8Array
  allRelationQueryForIdentity(queryJson: string, author: Uint8Array, opts?: { tier?: string; local_updates?: string; propagation?: string; include_deleted?: boolean } | undefined | null): Uint8Array
  localCurrentRow(table: string, rowId: Uint8Array): Uint8Array
  attachQuery(query: PreparedQuery, opts?: any | undefined | null): QueryAttachment
  attachQueryForIdentity(query: PreparedQuery, author: Uint8Array, opts?: any | undefined | null): QueryAttachment
  queryAttachmentIsCovered(attachment: QueryAttachment): boolean
  detachQuery(attachment: QueryAttachment): void
  subscribe(query: PreparedQuery, opts?: { tier?: string; local_updates?: string; propagation?: string; include_deleted?: boolean } | undefined | null): Subscription
  subscribeForIdentity(query: PreparedQuery, author: Uint8Array, opts?: { tier?: string; local_updates?: string; propagation?: string; include_deleted?: boolean } | undefined | null): Subscription
  subscribeRelationQuery(queryJson: string, opts?: { tier?: string; local_updates?: string; propagation?: string; include_deleted?: boolean } | undefined | null): Subscription
  subscribeRelationQueryForIdentity(queryJson: string, author: Uint8Array, opts?: { tier?: string; local_updates?: string; propagation?: string; include_deleted?: boolean } | undefined | null): Subscription
  insertWithIdEncoded(table: string, rowId: Uint8Array, cells: Uint8Array, updatedAtMs?: number | undefined | null): Write
  insertWithIdEncodedForIdentity(table: string, rowId: Uint8Array, cells: Uint8Array, author: Uint8Array, updatedAtMs?: number | undefined | null): Write
  updateEncoded(table: string, rowId: Uint8Array, patch: Uint8Array, updatedAtMs?: number | undefined | null): Write
  updateEncodedForIdentity(table: string, rowId: Uint8Array, patch: Uint8Array, author: Uint8Array, updatedAtMs?: number | undefined | null): Write
  upsertEncoded(table: string, rowId: Uint8Array, cells: Uint8Array, updatedAtMs?: number | undefined | null): Write
  upsertEncodedForIdentity(table: string, rowId: Uint8Array, cells: Uint8Array, author: Uint8Array, updatedAtMs?: number | undefined | null): Write
  delete(table: string, rowId: Uint8Array, updatedAtMs?: number | undefined | null): Write
  deleteForIdentity(table: string, rowId: Uint8Array, author: Uint8Array, updatedAtMs?: number | undefined | null): Write
  restoreEncoded(table: string, rowId: Uint8Array, cells: Uint8Array, updatedAtMs?: number | undefined | null): Write
  restoreEncodedForIdentity(table: string, rowId: Uint8Array, cells: Uint8Array, author: Uint8Array, updatedAtMs?: number | undefined | null): Write
  tick(): void
  connectUpstream(): Transport
  connectUpstreamWithSession(protocolVersion: number, features: number, remoteNode: Buffer, remoteEpoch: bigint, localNode: Buffer, localEpoch: bigint): Transport
  mergeableTx(openBatchId: string): Tx
  mergeableTxForIdentity(openBatchId: string, author: Uint8Array): Tx
  close(): void
}

export declare class PreparedQuery {

}

export declare class QueryAttachment {

}

export declare class Subscription {
  readAll(): Array<SubscriptionEvent>
  drain(): Array<SubscriptionEvent>
  close(): boolean
}

export declare class TestJwtIssuer {
  static start(): Promise<TestJwtIssuer>
  get jwksUrl(): string
  jwtForUser(userId: string, claims?: Record<string, unknown> | undefined, options?: { expiresInSeconds?: number; issuer?: string } | undefined): string
  stop(): Promise<void>
}

export declare class Transport {
  sendWireFrame(frame: Uint8Array): void
  sendWireFrames(frames: Array<Uint8Array>): void
  recvWireFrames(): Array<Uint8Array>
  tick(): number
  close(): boolean
}

export declare class Tx {
  insertWithIdEncoded(table: string, rowId: Uint8Array, cells: Uint8Array, updatedAtMs?: number | undefined | null): void
  updateEncoded(table: string, rowId: Uint8Array, patch: Uint8Array, updatedAtMs?: number | undefined | null): void
  upsertEncoded(table: string, rowId: Uint8Array, cells: Uint8Array, updatedAtMs?: number | undefined | null): void
  delete(table: string, rowId: Uint8Array, updatedAtMs?: number | undefined | null): void
  restoreEncoded(table: string, rowId: Uint8Array, cells: Uint8Array, updatedAtMs?: number | undefined | null): void
  commit(): Write
  rollback(): void
}

export declare class Write {
  get batchId(): string
  get payload(): Uint8Array
  writeState(): any
  wait(tier: string): Promise<undefined>
  close(): boolean
}

export declare function mintLocalFirstToken(seedB64: string, audience: string, ttlSeconds: number): string

export interface SubscriptionClosedEvent {
  type: 'closed'
}

export interface SubscriptionDeltaEvent {
  type: 'delta'
  reset: boolean
  delta: Uint8Array
  terminalOperations: Array<SubscriptionTerminalOperation>
  terminalLayouts: Array<SubscriptionTerminalLayout>
  settled: boolean
  tier: 'None' | 'Local' | 'Edge' | 'Global'
}

export type SubscriptionEvent =
  SubscriptionDeltaEvent | SubscriptionRejectedEvent | SubscriptionClosedEvent

export interface SubscriptionRejectedEvent {
  type: 'rejected'
  reason: SubscriptionRejectionReason
}

export type SubscriptionRejectionReason =
  SubscriptionUnsupportedShapeCapabilityReason | SubscriptionShapeRegistrationPendingReason | SubscriptionServerFailureReason

export interface SubscriptionServerFailureReason {
  type: 'ServerFailure'
  code: 'TableNotFound' | 'SchemaResolution' | 'QueryValidation' | 'QueryLowering' | 'PolicyEvaluation' | 'Internal'
}

export interface SubscriptionShapeRegistrationPendingReason {
  type: 'ShapeRegistrationPendingCatalogueAdmission'
}

export interface SubscriptionTerminalCollectionPathSegment {
  Collection: string
}

export type SubscriptionTerminalEdit =
  SubscriptionTerminalInsertEdit | SubscriptionTerminalUpdateEdit | SubscriptionTerminalRemoveEdit | SubscriptionTerminalMoveEdit

export interface SubscriptionTerminalInsert {
  index: number
  key: Array<number>
  value: Array<number>
}

export interface SubscriptionTerminalInsertEdit {
  Insert: SubscriptionTerminalInsert
}

export interface SubscriptionTerminalKeyPathSegment {
  Key: Array<number>
}

/**
 * Immutable producer-owned root record contract.  The descriptor and public
 * slots are published once per NAPI subscription, before an operation may
 * reference `id`; TypeScript never has to infer a CurrentRow/layout family.
 */
export interface SubscriptionTerminalLayout {
  id: string
  rootDescriptor: Array<number>
  rootKeySlot: number
  rootKeyFieldName: string
  publicFields: Array<SubscriptionTerminalPublicField>
  carrier: string
}

export interface SubscriptionTerminalMove {
  key: Array<number>
  index: number
}

export interface SubscriptionTerminalMoveEdit {
  Move: SubscriptionTerminalMove
}

export interface SubscriptionTerminalOperation {
  rootLayoutId: string
  root_key: Array<number>
  path: Array<SubscriptionTerminalPathSegment>
  edit: SubscriptionTerminalEdit
}

export type SubscriptionTerminalPathSegment =
  SubscriptionTerminalCollectionPathSegment | SubscriptionTerminalKeyPathSegment

export interface SubscriptionTerminalPublicField {
  name: string
  descriptorFieldName: string
  slot: number
  carrier: string
}

export interface SubscriptionTerminalRemove {
  key: Array<number>
}

export interface SubscriptionTerminalRemoveEdit {
  Remove: SubscriptionTerminalRemove
}

export interface SubscriptionTerminalUpdate {
  key: Array<number>
  value: Array<number>
}

export interface SubscriptionTerminalUpdateEdit {
  Update: SubscriptionTerminalUpdate
}

export interface SubscriptionUnsupportedShapeCapabilityReason {
  type: 'UnsupportedShapeCapability'
  detail: string
}

export declare function verifyLocalFirstIdentityProof(token: string | undefined | null, expectedAudience: string): VerifyTokenResult

export interface VerifyTokenResult {
  ok: boolean
  id: string
  error?: string
}
