/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class JazzServer {
  static start(options: { appId: string; backendSecret: string; adminSecret: string; port?: number; dataDir?: string; inMemory?: boolean; jwksUrl?: string; allowLocalFirstAuth?: boolean; upstreamUrl?: string; telemetryCollectorUrl?: string; schema?: Buffer | Uint8Array | number[] }): Promise<JazzServer>
  get appId(): string
  get url(): string
  get port(): number
  get dataDir(): string
  get backendSecret(): string
  get adminSecret(): string
  stop(): Promise<void>
}

export declare class NapiDb {
  insertEncoded(table: string, cells: Uint8Array, options?: InsertOptions | undefined | null): Write
  updateEncoded(table: string, rowId: Uint8Array, patch: Uint8Array, options?: UpdateOptions | undefined | null): Write
  upsertEncoded(table: string, rowId: Uint8Array, cells: Uint8Array, options?: UpsertOptions | undefined | null): Write
  deleteEncoded(table: string, rowId: Uint8Array, options?: DeleteOptions | undefined | null): Write
  restoreEncoded(table: string, rowId: Uint8Array, cells?: Uint8Array | undefined | null, options?: RestoreOptions | undefined | null): Write
  /**
   * Backend-only root mutation entrypoints. They deliberately do not take
   * branch selectors: attributed branch writes fail closed until #1881's
   * split transaction/branch representation is designed.
   */
  insertWithIdEncodedAttributed(table: string, rowId: Uint8Array, cells: Uint8Array, author: Uint8Array): Write
  updateEncodedAttributed(table: string, rowId: Uint8Array, patch: Uint8Array, author: Uint8Array): Write
  upsertEncodedAttributed(table: string, rowId: Uint8Array, cells: Uint8Array, author: Uint8Array): Write
  deleteAttributed(table: string, rowId: Uint8Array, author: Uint8Array): Write
  restoreEncodedAttributed(table: string, rowId: Uint8Array, cells: Uint8Array, author: Uint8Array): Write
  beginStreamingMutationEncoded(table: string, rowId: Uint8Array, cells: Uint8Array, column: string, mutation?: string | undefined | null, author?: Uint8Array | undefined | null, updatedAtMs?: number | undefined | null, head?: JsonValue | undefined | null, base?: JsonValue | undefined | null): StreamingMutation
  /**
   * Trusted-backend streaming counterpart: SYSTEM remains the admission
   * identity and `attribution` is retained only for final row provenance.
   * Branch streaming is intentionally unsupported until its split state is
   * designed, so it fails closed rather than silently losing attribution.
   */
  beginStreamingMutationAttributedEncoded(table: string, rowId: Uint8Array, cells: Uint8Array, column: string, mutation: string | undefined | null, author: Uint8Array | undefined | null, attribution: Uint8Array, updatedAtMs?: number | undefined | null, head?: JsonValue | undefined | null, base?: JsonValue | undefined | null): StreamingMutation
  static openMemory(schema: Uint8Array, config: Uint8Array): NapiDb
  /**
   * Open a deliberate backend runtime. Unlike the public raw-open entrypoint,
   * this explicit ABI derives the canonical system author.
   */
  static openMemoryAsBackend(schema: Uint8Array, config: Uint8Array): NapiDb
  /**
   * Open with a verified Jazz self-signed client identity. This is a
   * separate ABI entrypoint deliberately: a new client cannot accidentally
   * hand proof bytes to an old constructor, and an old client cannot enter
   * the proof-bearing path.
   */
  static openMemoryWithSelfSignedProof(schema: Uint8Array, config: Uint8Array, token: string, appId: string, claimedAuthor: string): NapiDb
  static openPersistent(dataPath: string, schema: Uint8Array, config: Uint8Array): NapiDb
  /**
   * Open a deliberate persistent backend runtime. This is intentionally a
   * distinct ABI from the public raw-open entrypoint.
   */
  static openPersistentAsBackend(dataPath: string, schema: Uint8Array, config: Uint8Array): NapiDb
  static openPersistentWithSelfSignedProof(dataPath: string, schema: Uint8Array, config: Uint8Array, token: string, appId: string, claimedAuthor: string): NapiDb
  /** Register and return a typed view backed by this same runtime owner. */
  registerSchema(schema: Uint8Array): NapiDb
  /**
   * Attach a schema view to an owner-wide mergeable batch without opening,
   * committing, or abandoning that batch.
   */
  attachMergeableTx(openBatchId: string): Tx
  /** Attach a schema view to an existing owner-wide exclusive batch. */
  attachExclusiveTx(openBatchId: string): Tx
  /** Begin one owner-wide transaction without creating an owning per-schema Tx. */
  beginTransaction(openBatchId: string, kind: string, author?: Uint8Array | undefined | null): void
  /**
   * Begin the only supported attributed transaction shape. Keeping this a
   * distinct native ABI makes an older binding fail closed rather than
   * silently treating provenance as ordinary SYSTEM authorship.
   */
  beginTransactionAttributed(openBatchId: string, attribution: Uint8Array): void
  /** Commit an owner-wide transaction by id and optional kind. */
  commitTransaction(openBatchId: string, kind?: string | undefined | null): Write
  /** Roll back an owner-wide open transaction by id. */
  rollbackTransaction(openBatchId: string): void
  setTickScheduler(callback: ((err: Error | null, arg: string) => void)): void
  onMutationError(callback: (event: any) => void): void
  prepareQuery(query: Uint8Array): PreparedQuery
  all(query: PreparedQuery, opts?: { tier?: string; local_updates?: string; propagation?: string; include_deleted?: boolean } | undefined | null): Uint8Array | PendingNativeRead
  /** Read through an open transaction using the identity bound at begin. */
  allInTransaction(query: PreparedQuery, tx: Tx, opts?: { tier?: string; local_updates?: string; propagation?: string; include_deleted?: boolean } | undefined | null): Uint8Array | PendingNativeRead
  setIdentityClaims(author: Uint8Array, claims?: Record<string, unknown> | undefined | null): void
  allForIdentity(query: PreparedQuery, author: Uint8Array, opts?: { tier?: string; local_updates?: string; propagation?: string; include_deleted?: boolean } | undefined | null): Uint8Array | PendingNativeRead
  allRelationSnapshot(query: PreparedQuery, opts?: { tier?: string; local_updates?: string; propagation?: string; include_deleted?: boolean } | undefined | null): Uint8Array | PendingNativeRead
  allRelationSnapshotForIdentity(query: PreparedQuery, author: Uint8Array, opts?: { tier?: string; local_updates?: string; propagation?: string; include_deleted?: boolean } | undefined | null): Uint8Array | PendingNativeRead
  allRelationQuery(queryJson: string, opts?: { tier?: string; local_updates?: string; propagation?: string; include_deleted?: boolean } | undefined | null): Uint8Array | PendingNativeRead
  allRelationQueryForIdentity(queryJson: string, author: Uint8Array, opts?: { tier?: string; local_updates?: string; propagation?: string; include_deleted?: boolean } | undefined | null): Uint8Array | PendingNativeRead
  localCurrentRow(table: string, rowId: Uint8Array): Uint8Array
  attachQuery(query: PreparedQuery, opts?: any | undefined | null): QueryAttachment
  attachQueryForIdentity(query: PreparedQuery, author: Uint8Array, opts?: any | undefined | null): QueryAttachment
  queryAttachmentIsCovered(attachment: QueryAttachment): boolean
  detachQuery(attachment: QueryAttachment): void
  subscribe(query: PreparedQuery, opts?: { tier?: string; local_updates?: string; propagation?: string; include_deleted?: boolean } | undefined | null): Subscription
  subscribeForIdentity(query: PreparedQuery, author: Uint8Array, opts?: { tier?: string; local_updates?: string; propagation?: string; include_deleted?: boolean } | undefined | null): Subscription
  subscribeRelationQuery(queryJson: string, opts?: { tier?: string; local_updates?: string; propagation?: string; include_deleted?: boolean } | undefined | null): Subscription
  subscribeRelationQueryForIdentity(queryJson: string, author: Uint8Array, opts?: { tier?: string; local_updates?: string; propagation?: string; include_deleted?: boolean } | undefined | null): Subscription
  tick(): void
  /** Configure Jazz-owned upload ingress and unpublished-tree expiry limits. */
  setLargeValueStagingPolicy(incomingBytesPerWindow: number, windowMs: number, maxAgeMs?: number | undefined | null): void
  /** Run one idempotent expiry pass; native hosts normally call this on a timer. */
  evictExpiredStagedLargeValues(): number
  readValueRange(table: string, rowId: Uint8Array, column: string, start: number, end: number): Uint8Array | PendingNativeRead
  readTextUtf16Range(table: string, rowId: Uint8Array, column: string, start: number, end: number): string | PendingNativeRead
  readJsonPointer(table: string, rowId: Uint8Array, column: string, pointer: string): string | undefined | null | PendingNativeRead
  appendValue(table: string, rowId: Uint8Array, column: string, bytes: Uint8Array): Write | PendingNativeWrite
  spliceValue(table: string, rowId: Uint8Array, column: string, offset: number, deleteLength: number, insert: Uint8Array): Write | PendingNativeWrite
  setNonDurableClient(): void
  connectUpstream(): Transport
  connectUpstreamWithSession(protocolVersion: number, features: number, remoteNode: Buffer, remoteEpoch: bigint, localNode: Buffer, localEpoch: bigint): Transport
  mergeableTx(openBatchId: string): Tx
  mergeableTxForIdentity(openBatchId: string, author: Uint8Array): Tx
  close(): Promise<undefined>
}

/**
 * A JavaScript-thread-owned binding read which suspended on asynchronous
 * large-value storage. NAPI promises execute on a Send worker pool, whereas
 * a Jazz runtime is deliberately `Rc`/thread-affine. The adapter drives this
 * object after its peer transport makes progress instead of blocking Node.
 */
export declare class PendingNativeRead {
  poll(): Uint8Array | null
}

/**
 * Opaque marker returned while the next bounded native subscription batch is
 * waiting for chunk I/O. Call `readAll` again after transport progress.
 */
export declare class PendingNativeSubscriptionBatch {

}

/**
 * Thread-affine large-value mutation setup which is waiting for local or
 * routed chunks. The completed value is the ordinary write receipt.
 */
export declare class PendingNativeWrite {
  poll(): Write | null
}

export declare class PreparedQuery {

}

export declare class QueryAttachment {

}

/**
 * Native bounded-memory sink used by the TypeScript async streaming-mutation
 * adapter. Each push incrementally prepares and stages bounded Groove nodes,
 * using the same ingress policy and resumable construction as WASM.
 */
export declare class StreamingMutation {
  push(chunk: Uint8Array): void
  finish(): Write
  abort(): boolean
}

export declare class Subscription {
  readAll(): Array<SubscriptionEvent> | PendingNativeSubscriptionBatch
  drain(): Array<SubscriptionEvent> | PendingNativeSubscriptionBatch
  close(): boolean
}

export declare class TestJwtIssuer {
  static start(): Promise<TestJwtIssuer>
  get jwksUrl(): string
  jwtForUser(userId: string, claims?: Record<string, unknown> | undefined, options?: { expiresInSeconds?: number; issuer?: string } | undefined): string
  stop(): Promise<void>
}

export declare class Transport {
  routeAuxiliaryWireFrame(frame: Uint8Array): Uint8Array | null
  recvAuxiliaryWireFrames(): Array<Uint8Array>
  auxiliaryOutboundReady(): boolean
  sendWireFrame(frame: Uint8Array): void
  sendWireFrames(frames: Array<Uint8Array>): void
  recvWireFrames(): Array<Uint8Array>
  tick(): number
  close(): boolean
}

export declare class Tx {
  insertEncoded(table: string, cells: Uint8Array, options?: InsertOptions | undefined | null): Uint8Array
  updateEncoded(table: string, rowId: Uint8Array, patch: Uint8Array, options?: UpdateOptions | undefined | null): void
  upsertEncoded(table: string, rowId: Uint8Array, cells: Uint8Array, options?: UpsertOptions | undefined | null): void
  deleteEncoded(table: string, rowId: Uint8Array, options?: DeleteOptions | undefined | null): void
  restoreEncoded(table: string, rowId: Uint8Array, cells?: Uint8Array | undefined | null, options?: RestoreOptions | undefined | null): void
  commit(): Write
  rollback(): void
}

export declare class Write {
  get batchId(): string
  get payload(): Uint8Array
  get rowId(): Uint8Array
  writeState(): any
  wait(tier: string): Promise<undefined>
  close(): boolean
}

export interface DeleteOptions {
  author?: Uint8Array
  head?: JsonValue
  base?: JsonValue
  updatedAtMs?: number
}

export interface InsertOptions {
  rowId?: Uint8Array
  author?: Uint8Array
  branch?: JsonValue
  updatedAtMs?: number
}

/**
 * Any JSON-compatible value crossing the native JavaScript boundary.
 *
 * Keep this alias exported through napi-rs rather than relying on its Rust
 * import name: exported methods use `JsonValue` throughout their generated
 * declarations, so the package must define that name for TypeScript
 * consumers.
 */
export type JsonValue =
  any

export declare function mintLocalFirstToken(seedB64: string, audience: string, ttlSeconds: number): string

/** Exact build/ABI fingerprint for the generated native artifact. */
export declare function nativeArtifactFingerprint(): string

export interface RestoreOptions {
  author?: Uint8Array
  branch?: JsonValue
  updatedAtMs?: number
}

export interface SubscriptionClosedEvent {
  type: 'closed'
}

export interface SubscriptionDeltaEvent {
  type: 'delta'
  reset: boolean
  delta: Uint8Array
  orderedSuffixStart?: number
  terminalOperations: Array<SubscriptionTerminalOperation>
  terminalLayouts: Array<SubscriptionTerminalLayout>
  settled: boolean
  tier: 'None' | 'Local' | 'Edge' | 'Global'
}

export type SubscriptionEvent =
  SubscriptionDeltaEvent | SubscriptionRejectedEvent | SubscriptionClosedEvent

export interface SubscriptionRejectedEvent {
  type: 'rejected'
  reason: SubscriptionRejectionReason
}

export type SubscriptionRejectionReason =
  SubscriptionUnsupportedShapeCapabilityReason | SubscriptionShapeRegistrationPendingReason | SubscriptionServerFailureReason

export interface SubscriptionServerFailureReason {
  type: 'ServerFailure'
  code: 'TableNotFound' | 'SchemaResolution' | 'QueryValidation' | 'QueryLowering' | 'PolicyEvaluation' | 'Internal'
}

export interface SubscriptionShapeRegistrationPendingReason {
  type: 'ShapeRegistrationPendingCatalogueAdmission'
}

export interface SubscriptionTerminalCollectionPathSegment {
  Collection: string
}

export type SubscriptionTerminalEdit =
  SubscriptionTerminalInsertEdit | SubscriptionTerminalUpdateEdit | SubscriptionTerminalRemoveEdit | SubscriptionTerminalMoveEdit

export interface SubscriptionTerminalInsert {
  index: number
  key: Array<number>
  value: Array<number>
}

export interface SubscriptionTerminalInsertEdit {
  Insert: SubscriptionTerminalInsert
}

export interface SubscriptionTerminalKeyPathSegment {
  Key: Array<number>
}

/**
 * Immutable producer-owned root record contract.  The descriptor and public
 * slots are published once per NAPI subscription, before an operation may
 * reference `id`; TypeScript never has to infer a CurrentRow/layout family.
 */
export interface SubscriptionTerminalLayout {
  id: string
  rootDescriptor: Array<number>
  rootKeySlot: number
  rootKeyFieldName: string
  publicFields: Array<SubscriptionTerminalPublicField>
  carrier: string
}

export interface SubscriptionTerminalMove {
  key: Array<number>
  index: number
}

export interface SubscriptionTerminalMoveEdit {
  Move: SubscriptionTerminalMove
}

export interface SubscriptionTerminalOperation {
  rootLayoutId: string
  root_key: Array<number>
  path: Array<SubscriptionTerminalPathSegment>
  edit: SubscriptionTerminalEdit
}

export type SubscriptionTerminalPathSegment =
  SubscriptionTerminalCollectionPathSegment | SubscriptionTerminalKeyPathSegment

export interface SubscriptionTerminalPublicField {
  name: string
  descriptorFieldName: string
  slot: number
  carrier: string
}

export interface SubscriptionTerminalRemove {
  key: Array<number>
}

export interface SubscriptionTerminalRemoveEdit {
  Remove: SubscriptionTerminalRemove
}

export interface SubscriptionTerminalUpdate {
  key: Array<number>
  value: Array<number>
}

export interface SubscriptionTerminalUpdateEdit {
  Update: SubscriptionTerminalUpdate
}

export interface SubscriptionUnsupportedShapeCapabilityReason {
  type: 'UnsupportedShapeCapability'
  detail: string
}

export interface UpdateOptions {
  author?: Uint8Array
  head?: JsonValue
  base?: JsonValue
  updatedAtMs?: number
}

export interface UpsertOptions {
  author?: Uint8Array
  branch?: JsonValue
  updatedAtMs?: number
}

export declare function verifyLocalFirstIdentityProof(token: string | undefined | null, expectedAudience: string): VerifyTokenResult

export interface VerifyTokenResult {
  ok: boolean
  id: string
  error?: string
}
