/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function generateId(): string
export declare function currentTimestamp(): number
export declare function parseSchema(json: string): any
export declare class NapiRuntime {
  /** Create a new NapiRuntime with SurrealKV-backed persistent storage. */
  constructor(schemaJson: string, appId: string, jazzEnv: string, userBranch: string, dataPath: string, tier?: string | undefined | null)
  insert(table: string, values: any): string
  update(objectId: string, values: any): void
  delete(objectId: string): void
  query(queryJson: string, sessionJson?: string | undefined | null, settledTier?: string | undefined | null): Promise<any>
  subscribe(queryJson: string, onUpdate: (...args: any[]) => any, sessionJson?: string | undefined | null, settledTier?: string | undefined | null): number
  unsubscribe(handle: number): void
  insertWithAck(table: string, values: any, tier: string): Promise<string>
  updateWithAck(objectId: string, values: any, tier: string): Promise<void>
  deleteWithAck(objectId: string, tier: string): Promise<void>
  onSyncMessageReceived(messageJson: string): void
  /** Called by JS when a sync message arrives from a client (not a server). */
  onSyncMessageReceivedFromClient(clientId: string, messageJson: string): void
  onSyncMessageToSend(callback: (...args: any[]) => any): void
  addServer(): void
  removeServer(): void
  addClient(): string
  /** Set a client's role ("user", "admin", or "peer"). */
  setClientRole(clientId: string, role: string): void
  getSchema(): any
  getSchemaHash(): string
  flush(): void
  /** Flush and close the underlying storage, releasing filesystem locks. */
  close(): void
}
