//! Client cache classification and explicit cold-state eviction.

use std::collections::BTreeSet;

use groove::storage::OrderedKvStorage;

use crate::tx::{DurabilityTier, Fate, TxId};

use super::*;

const CLIENT_CACHE_LOW_WATER_NUMERATOR: u64 = 9;
const CLIENT_CACHE_LOW_WATER_DENOMINATOR: u64 = 10;

/// Conservative client-cache classification for cached state.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ClientCacheClass {
    /// State that may be dropped and regenerated by refetch.
    Evictable,
    /// State that must survive manual and future automatic eviction.
    Pinned,
}

/// Counts returned by [`NodeState::evict_cold`].
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct EvictColdReport {
    /// Number of stored row-version rows classified as evictable and removed.
    pub row_versions_evictable: usize,
    /// Number of stored row-version transactions classified as pinned.
    pub row_versions_pinned: usize,
    /// Number of parked family entries observed and preserved.
    pub parked_families_pinned: usize,
    /// Number of pending-fate transactions observed and preserved.
    pub fate_pending_txs_pinned: usize,
}

/// Explicit client-cache byte budget.
///
/// The caller decides when to run a pass. Core storage must never be treated as
/// a disposable client cache.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ClientCacheBudget {
    /// High-water byte budget. Eviction runs only when metered bytes exceed it.
    pub max_bytes: u64,
}

impl ClientCacheBudget {
    /// Construct a byte budget that triggers eviction above `max_bytes`.
    pub fn new(max_bytes: u64) -> Self {
        Self { max_bytes }
    }

    fn low_water_bytes(self) -> u64 {
        self.max_bytes
            .saturating_mul(CLIENT_CACHE_LOW_WATER_NUMERATOR)
            / CLIENT_CACHE_LOW_WATER_DENOMINATOR
    }
}

/// Report from one budget-triggered client-cache eviction pass.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ClientCacheBudgetReport {
    /// Metered bytes before eviction.
    pub before_bytes: u64,
    /// Metered bytes after eviction.
    pub after_bytes: u64,
    /// Hysteresis low-water target for the pass.
    pub low_water_bytes: u64,
    /// Entries removed or preserved during the pass.
    pub evicted: EvictColdReport,
}

#[derive(Clone)]
struct EvictableRowVersion {
    tx_id: TxId,
    version: VersionRow,
}

impl<S> NodeState<S>
where
    S: OrderedKvStorage,
{
    /// Return the conservative cache class for one stored row version.
    ///
    /// Globally accepted row versions can be fetched again. Pending or
    /// otherwise uncertain transactions stay pinned.
    pub async fn classify_row_version_for_eviction(
        &mut self,
        tx_id: TxId,
    ) -> Result<ClientCacheClass, Error> {
        let Some(tx) = self.query_transaction(tx_id).await? else {
            return Ok(ClientCacheClass::Pinned);
        };
        if matches!(tx.fate, Fate::Pending) {
            return Ok(ClientCacheClass::Pinned);
        }
        if matches!(tx.fate, Fate::Accepted) && tx.durability == DurabilityTier::Global {
            Ok(ClientCacheClass::Evictable)
        } else {
            Ok(ClientCacheClass::Pinned)
        }
    }

    /// Manually drop evictable cold client-cache state.
    ///
    /// This is intentionally not called by any automatic trigger. It preserves
    /// fate-pending rows and all parked families.
    pub async fn evict_cold(&mut self) -> Result<EvictColdReport, Error> {
        self.evict_cold_inner(None)
            .await
            .map(|report| report.evicted)
    }

    /// Enforce an optional byte budget for client-cache state.
    ///
    /// Returns `Ok(None)` when the backend cannot meter all relevant storage
    /// classes or when the cache is already at or below the high-water budget.
    pub async fn enforce_client_cache_budget(
        &mut self,
        budget: ClientCacheBudget,
    ) -> Result<Option<ClientCacheBudgetReport>, Error> {
        let Some(before_bytes) = self.client_cache_metered_bytes().await? else {
            return Ok(None);
        };
        if before_bytes <= budget.max_bytes {
            return Ok(None);
        }
        let mut report = self
            .evict_cold_inner(Some(budget.low_water_bytes()))
            .await?;
        report.before_bytes = before_bytes;
        report.after_bytes = self
            .client_cache_metered_bytes()
            .await?
            .unwrap_or(report.after_bytes);
        Ok(Some(report))
    }

    /// Return metered client-cache bytes, if every relevant class can be metered.
    pub async fn client_cache_metered_bytes(&mut self) -> Result<Option<u64>, Error> {
        let logical_families = self.client_cache_metered_column_families().await?;
        self.database
            .approximate_class_bytes_for_logical_families(
                logical_families.iter().map(String::as_str),
            )
            .await
            .map_err(Error::from)
    }

    async fn evict_cold_inner(
        &mut self,
        low_water_bytes: Option<u64>,
    ) -> Result<ClientCacheBudgetReport, Error> {
        let mut report = EvictColdReport {
            parked_families_pinned: self.parking.parked_commit_units.len()
                + self.parking.parked_catalogue_commit_units.len()
                + self.parking.parked_shape_registrations.len(),
            ..EvictColdReport::default()
        };

        let before_bytes = self.client_cache_metered_bytes().await?.unwrap_or(0);
        let mut remaining_bytes = before_bytes;

        let mut seen_pinned_txs = BTreeSet::new();
        let mut evictable = Vec::new();
        for table in self.catalogue.schema.tables.clone() {
            for version in self.query_table_versions(&table.name).await? {
                let tx_id = self.version_tx_id(&version)?;
                match self.classify_row_version_for_eviction(tx_id).await? {
                    ClientCacheClass::Evictable => {
                        evictable.push(EvictableRowVersion { tx_id, version })
                    }
                    ClientCacheClass::Pinned => {
                        if seen_pinned_txs.insert(tx_id) {
                            report.row_versions_pinned += 1;
                            if self
                                .query_transaction(tx_id)
                                .await?
                                .is_some_and(|tx| matches!(tx.fate, Fate::Pending))
                            {
                                report.fate_pending_txs_pinned += 1;
                            }
                        }
                    }
                }
            }
        }
        evictable.sort_by_key(|candidate| candidate.tx_id);
        if !evictable.is_empty() {
            // INV-SYNC-27: once local row-version bodies may be removed, no
            // in-memory fast known-state cursor may survive. Scope and cursor
            // invalidation is infallible and precedes any body deletion.
            self.invalidate_subscription_scopes();
            self.clear_content_version_reachability_cache();
        }

        if low_water_bytes.is_none() {
            // Manual eviction publishes one batch, so every affected cache
            // must be invalid before that batch can have an ambiguous outcome.
            let mut last_invalidated_tx_id = None;
            for candidate in &evictable {
                if last_invalidated_tx_id == Some(candidate.tx_id) {
                    continue;
                }
                self.invalidate_tx_version_tables_cache(candidate.tx_id);
                last_invalidated_tx_id = Some(candidate.tx_id);
            }
        }

        let mut batch = self.database.open_batch();
        let mut batch_deletes = 0_usize;
        for candidate in evictable {
            if low_water_bytes.is_some_and(|low_water| remaining_bytes <= low_water) {
                break;
            }
            report.row_versions_evictable += 1;
            if low_water_bytes.is_some() {
                // A budgeted deletion is persisted per candidate. Invalidate
                // both transaction-version caches before its fallible commit.
                self.invalidate_tx_version_tables_cache(candidate.tx_id);
            }
            let history_table = self.version_storage_table_for_row(&candidate.version)?;
            batch.delete(
                history_table.as_ref(),
                history_primary_key(&candidate.version),
            );
            batch_deletes += 1;
            if low_water_bytes.is_some() {
                let applied = self.database.apply_batch(batch).await?;
                let persisted = applied.persist().await;
                self.database.finish_persistence(persisted)?;
                remaining_bytes = self
                    .client_cache_metered_bytes()
                    .await?
                    .unwrap_or(remaining_bytes);
                batch = self.database.open_batch();
            }
        }
        if batch_deletes > 0 && low_water_bytes.is_none() {
            let applied = self.database.apply_batch(batch).await?;
            let persisted = applied.persist().await;
            self.database.finish_persistence(persisted)?;
        }

        let after_bytes = self
            .client_cache_metered_bytes()
            .await?
            .unwrap_or(remaining_bytes);
        Ok(ClientCacheBudgetReport {
            before_bytes,
            after_bytes,
            low_water_bytes: low_water_bytes.unwrap_or(0),
            evicted: report,
        })
    }

    async fn client_cache_metered_column_families(&mut self) -> Result<Vec<String>, Error> {
        let mut families = BTreeSet::new();
        for table in self.catalogue.schema.tables.clone() {
            for version in self.query_table_versions(&table.name).await? {
                families.insert(self.version_storage_table_for_row(&version)?.to_string());
            }
        }
        Ok(families.into_iter().collect())
    }
}
