/**
 * Permissions test starter.
 *
 * Suggested shape (jazz-tools/testing):
 * - createPolicyTestApp(...) for an isolated test app
 * - testApp.seed(...) to set up synthetic fixtures
 * - testApp.as(...) for request-scoped user clients
 * - testApp.expectAllowed(...) / testApp.expectDenied(...) assertions
 */
import { describe, it } from "vitest";

describe.skip("permissions", () => {
  it("add policy tests", () => {
    // Starter file generated by jazz-tools build.
  });
});
