// Auto generated by Craby. DO NOT EDIT.
#[rustfmt::skip]
use craby::prelude::*;

use crate::cojson_core_rn_impl::*;
use crate::generated::*;

use bridging::*;

#[cxx::bridge(namespace = "craby::cojsoncorern::bridging")]
pub mod bridging {




    extern "Rust" {
        type CojsonCoreRn;

        #[cxx_name = "createCojsonCoreRn"]
        fn create_cojson_core_rn(id: usize, data_path: &str) -> Box<CojsonCoreRn>;

        #[cxx_name = "add"]
        fn cojson_core_rn_add(it_: &mut CojsonCoreRn, a: f64, b: f64) -> Result<f64>;

        #[cxx_name = "divide"]
        fn cojson_core_rn_divide(it_: &mut CojsonCoreRn, a: f64, b: f64) -> Result<f64>;

        #[cxx_name = "multiply"]
        fn cojson_core_rn_multiply(it_: &mut CojsonCoreRn, a: f64, b: f64) -> Result<f64>;

        #[cxx_name = "subtract"]
        fn cojson_core_rn_subtract(it_: &mut CojsonCoreRn, a: f64, b: f64) -> Result<f64>;
    }

}

fn create_cojson_core_rn(id: usize, data_path: &str) -> Box<CojsonCoreRn> {
    let ctx = Context::new(id, data_path);
    Box::new(CojsonCoreRn::new(ctx))
}

fn cojson_core_rn_add(it_: &mut CojsonCoreRn, a: f64, b: f64) -> Result<f64, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.add(a, b);
        ret
    })
}

fn cojson_core_rn_divide(it_: &mut CojsonCoreRn, a: f64, b: f64) -> Result<f64, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.divide(a, b);
        ret
    })
}

fn cojson_core_rn_multiply(it_: &mut CojsonCoreRn, a: f64, b: f64) -> Result<f64, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.multiply(a, b);
        ret
    })
}

fn cojson_core_rn_subtract(it_: &mut CojsonCoreRn, a: f64, b: f64) -> Result<f64, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.subtract(a, b);
        ret
    })
}
