// Auto generated by Craby. DO NOT EDIT.
// Hash: 0340bf43fd9ade66
#[rustfmt::skip]
use craby::prelude::*;

use crate::ffi::bridging::*;

pub trait CojsonCoreRnSpec {
    fn new(ctx: Context) -> Self;
    fn id(&self) -> usize;
    fn add(&mut self, a: Number, b: Number) -> Number;
    fn divide(&mut self, a: Number, b: Number) -> Number;
    fn multiply(&mut self, a: Number, b: Number) -> Number;
    fn subtract(&mut self, a: Number, b: Number) -> Number;
}
