export const DEVICE_DIAGNOSTIC_CODES = [
  "fixture-metadata-failed",
  "native-admission-failed",
  "relay-command-abi-failed",
  "relay-open-failed",
  "relay-attach-failed",
  "relay-probe-failed",
  "relay-cleanup-failed",
  "foreground-byte-abi-failed",
  "foreground-install-failed",
  "foreground-open-failed",
  "foreground-probe-failed",
  "foreground-tick-failed",
  "foreground-close-failed",
  "logout-revocation-failed",
  "public-client-seed-failed",
  "public-client-open-failed",
  "public-client-subscribe-failed",
  "public-client-write-failed",
  "public-client-read-failed",
  "public-client-publish-failed",
  "public-client-shutdown-failed",
  "public-client-relay-readback-failed",
  "scope-isolation-failed",
  "scope-isolation-open-failed",
  "scope-isolation-write-failed",
  "scope-isolation-writer-read-failed",
  "scope-isolation-read-failed",
  "scope-isolation-assert-failed",
  "auth-switch-failed",
  "foreground-write-failed",
  "same-runtime-subscription-failed",
  "same-runtime-open-failed",
  "same-runtime-subscribe-failed",
  "same-runtime-initial-reset-failed",
  "same-runtime-write-failed",
  "same-runtime-transaction-open-failed",
  "same-runtime-mutation-stage-failed",
  "same-runtime-commit-failed",
  "same-runtime-delta-failed",
  "same-runtime-postcommit-wake-failed",
  "same-runtime-delta-drain-failed",
  "same-runtime-delta-decode-failed",
  "same-runtime-delta-content-failed",
  "same-runtime-delta-row-id-failed",
  "same-runtime-delta-written-content-row-id-failed",
  "same-runtime-delta-reset-row-id-failed",
  "same-runtime-delta-incremental-row-id-failed",
  "same-runtime-delta-mixed-row-id-failed",
  "same-runtime-unsubscribe-failed",
  "scope-reopen-failed",
  "public-client-restart-failed",
  "receipt-write-failed",
] as const;

export type DeviceDiagnosticCode = (typeof DEVICE_DIAGNOSTIC_CODES)[number];

export function isDeviceDiagnosticCode(value: string): value is DeviceDiagnosticCode {
  return (DEVICE_DIAGNOSTIC_CODES as readonly string[]).includes(value);
}
