//! Edge cache eviction classification and cold-state eviction.

use std::collections::BTreeSet;

use groove::records::Value;
use groove::storage::OrderedKvStorage;

use crate::peer::PeerEvictionPins;
use crate::schema::{CONTENT_CHECKPOINTS_STORE, CONTENT_EXTENTS_STORE, CONTENT_META_STORE};
use crate::tx::{DurabilityTier, Fate, TxId};

use super::*;

const EDGE_CACHE_LOW_WATER_NUMERATOR: u64 = 9;
const EDGE_CACHE_LOW_WATER_DENOMINATOR: u64 = 10;

/// Conservative edge-cache classification for cached state.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum EdgeCacheClass {
    /// State that may be dropped and regenerated by refetch.
    Evictable,
    /// State that must survive manual and future automatic eviction.
    Pinned,
}

/// Counts returned by [`NodeState::evict_cold`].
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct EvictColdReport {
    /// Number of direct-store large-value extent byte entries removed.
    pub content_extent_entries: usize,
    /// Number of materialized large-value checkpoint byte entries removed.
    pub content_checkpoint_entries: usize,
    /// Number of large-value metadata entries observed and preserved.
    pub content_meta_entries_pinned: usize,
    /// Number of stored row-version rows classified as evictable and removed.
    pub row_versions_evictable: usize,
    /// Number of stored row-version transactions classified as pinned.
    pub row_versions_pinned: usize,
    /// Number of parked family entries observed and preserved.
    pub parked_families_pinned: usize,
    /// Number of pending-fate transactions observed and preserved.
    pub fate_pending_txs_pinned: usize,
    /// Number of peer-deferred edge-fate transactions observed and preserved.
    pub deferred_edge_fate_txs_pinned: usize,
    /// Number of referenced scope subscriptions observed and preserved.
    pub referenced_scope_subscriptions_pinned: usize,
}

/// Optional edge-cache byte budget.
///
/// When absent, automatic edge eviction is disabled and the node behaves as it
/// did before budgeted eviction existed.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct EdgeCacheBudget {
    /// High-water byte budget. Eviction runs only when metered bytes exceed it.
    pub max_bytes: u64,
}

impl EdgeCacheBudget {
    /// Construct a byte budget that triggers eviction above `max_bytes`.
    pub fn new(max_bytes: u64) -> Self {
        Self { max_bytes }
    }

    fn low_water_bytes(self) -> u64 {
        self.max_bytes
            .saturating_mul(EDGE_CACHE_LOW_WATER_NUMERATOR)
            / EDGE_CACHE_LOW_WATER_DENOMINATOR
    }
}

/// Report from one budget-triggered edge-cache eviction pass.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct EdgeCacheBudgetReport {
    /// Metered bytes before eviction.
    pub before_bytes: u64,
    /// Metered bytes after eviction.
    pub after_bytes: u64,
    /// Hysteresis low-water target for the pass.
    pub low_water_bytes: u64,
    /// Entries removed or preserved during the pass.
    pub evicted: EvictColdReport,
}

#[derive(Clone)]
struct EvictableRowVersion {
    tx_id: TxId,
    version: VersionRow,
}

impl<S> NodeState<S>
where
    S: OrderedKvStorage,
{
    /// Return the conservative cache class for one stored row version.
    ///
    /// Cold globally accepted row versions are evictable unless some edge pin
    /// source names their transaction. Everything uncertain stays pinned.
    pub fn classify_row_version_for_eviction(
        &mut self,
        tx_id: TxId,
        peer_pins: &PeerEvictionPins,
    ) -> Result<EdgeCacheClass, Error> {
        if peer_pins.deferred_edge_fate_txs.contains(&tx_id) {
            return Ok(EdgeCacheClass::Pinned);
        }
        let Some(tx) = self.query_transaction(tx_id)? else {
            return Ok(EdgeCacheClass::Pinned);
        };
        if matches!(tx.fate, Fate::Pending) {
            return Ok(EdgeCacheClass::Pinned);
        }
        if matches!(tx.fate, Fate::Accepted) && tx.durability == DurabilityTier::Global {
            Ok(EdgeCacheClass::Evictable)
        } else {
            Ok(EdgeCacheClass::Pinned)
        }
    }

    /// Manually drop evictable cold edge-cache state.
    ///
    /// This is intentionally not called by any automatic trigger. It preserves
    /// large-value metadata, fate-pending rows, peer-deferred edge fates,
    /// referenced permission scopes, and all parked families.
    pub fn evict_cold(&mut self, peer_pins: &PeerEvictionPins) -> Result<EvictColdReport, Error> {
        self.evict_cold_inner(peer_pins, None)
            .map(|report| report.evicted)
    }

    /// Enforce an optional byte budget for edge-cache state.
    ///
    /// Returns `Ok(None)` when the backend cannot meter all relevant storage
    /// classes or when the cache is already at or below the high-water budget.
    pub fn enforce_edge_cache_budget(
        &mut self,
        peer_pins: &PeerEvictionPins,
        budget: EdgeCacheBudget,
    ) -> Result<Option<EdgeCacheBudgetReport>, Error> {
        let Some(before_bytes) = self.edge_cache_metered_bytes()? else {
            return Ok(None);
        };
        if before_bytes <= budget.max_bytes {
            return Ok(None);
        }
        let mut report = self.evict_cold_inner(peer_pins, Some(budget.low_water_bytes()))?;
        report.before_bytes = before_bytes;
        report.after_bytes = self
            .edge_cache_metered_bytes()?
            .unwrap_or(report.after_bytes);
        Ok(Some(report))
    }

    /// Return metered edge-cache bytes, if every relevant class can be metered.
    pub fn edge_cache_metered_bytes(&mut self) -> Result<Option<u64>, Error> {
        let mut bytes = 0_u64;
        for cf in self.edge_cache_metered_column_families()? {
            let Some(next) = self.database.approximate_class_bytes(&cf)? else {
                return Ok(None);
            };
            bytes = bytes.saturating_add(next);
        }
        Ok(Some(bytes))
    }

    fn evict_cold_inner(
        &mut self,
        peer_pins: &PeerEvictionPins,
        low_water_bytes: Option<u64>,
    ) -> Result<EdgeCacheBudgetReport, Error> {
        let mut report = EvictColdReport {
            parked_families_pinned: self.parking.parked_commit_units.len()
                + self.parking.parked_catalogue_commit_units.len()
                + self.parking.parked_shape_registrations.len(),
            deferred_edge_fate_txs_pinned: peer_pins.deferred_edge_fate_txs.len(),
            referenced_scope_subscriptions_pinned: peer_pins.referenced_scope_subscriptions.len(),
            ..EvictColdReport::default()
        };

        let before_bytes = self.edge_cache_metered_bytes()?.unwrap_or(0);
        report.content_meta_entries_pinned = self.direct_store_entry_count(CONTENT_META_STORE)?;

        let mut remaining_bytes = before_bytes;
        if low_water_bytes.is_none_or(|low_water| remaining_bytes > low_water) {
            report.content_extent_entries =
                self.delete_direct_store_entries(CONTENT_EXTENTS_STORE)?;
            report.content_checkpoint_entries =
                self.delete_direct_store_entries(CONTENT_CHECKPOINTS_STORE)?;
            remaining_bytes = self.edge_cache_metered_bytes()?.unwrap_or(remaining_bytes);
        }

        let mut seen_pinned_txs = BTreeSet::new();
        let mut evictable = Vec::new();
        for table in self.catalogue.schema.tables.clone() {
            for version in self.query_table_versions(&table.name)? {
                let tx_id = self.version_tx_id(&version)?;
                match self.classify_row_version_for_eviction(tx_id, peer_pins)? {
                    EdgeCacheClass::Evictable => {
                        evictable.push(EvictableRowVersion { tx_id, version })
                    }
                    EdgeCacheClass::Pinned => {
                        if seen_pinned_txs.insert(tx_id) {
                            report.row_versions_pinned += 1;
                            if self
                                .query_transaction(tx_id)?
                                .is_some_and(|tx| matches!(tx.fate, Fate::Pending))
                            {
                                report.fate_pending_txs_pinned += 1;
                            }
                        }
                    }
                }
            }
        }
        evictable.sort_by_key(|candidate| candidate.tx_id);

        let mut batch = self.database.open_batch();
        let mut batch_deletes = 0_usize;
        let mut evicted_tx_ids = BTreeSet::new();
        for candidate in evictable {
            if low_water_bytes.is_some_and(|low_water| remaining_bytes <= low_water) {
                break;
            }
            report.row_versions_evictable += 1;
            evicted_tx_ids.insert(candidate.tx_id);
            let schema_version = self
                .schema_version_for_alias(candidate.version.schema_version_alias())
                .ok_or(Error::InvalidStoredValue("version schema alias must exist"))?;
            batch.delete(
                version_storage_table_name_for_schema(
                    candidate.version.table(),
                    candidate.version.layer(),
                    schema_version,
                    self.catalogue.current_schema_version_id,
                ),
                history_primary_key(&candidate.version),
            );
            batch_deletes += 1;
            if low_water_bytes.is_some() {
                self.database.commit_batch(batch)?;
                remaining_bytes = self.edge_cache_metered_bytes()?.unwrap_or(remaining_bytes);
                batch = self.database.open_batch();
            }
        }
        if batch_deletes > 0 && low_water_bytes.is_none() {
            self.database.commit_batch(batch)?;
        }
        for tx_id in evicted_tx_ids {
            self.invalidate_tx_version_tables_cache(tx_id);
        }
        if report.row_versions_evictable > 0 {
            // INV-SYNC-27: once local row-version bodies are removed, no
            // persisted fast known-state cursor may survive. This coarse
            // invalidation is conservative until eviction tracks affected
            // binding views directly.
            self.clear_all_known_state_facts()?;
        }

        let after_bytes = self.edge_cache_metered_bytes()?.unwrap_or(remaining_bytes);
        Ok(EdgeCacheBudgetReport {
            before_bytes,
            after_bytes,
            low_water_bytes: low_water_bytes.unwrap_or(0),
            evicted: report,
        })
    }

    fn edge_cache_metered_column_families(&mut self) -> Result<Vec<String>, Error> {
        let mut families = BTreeSet::from([
            CONTENT_EXTENTS_STORE.to_owned(),
            CONTENT_CHECKPOINTS_STORE.to_owned(),
        ]);
        for table in self.catalogue.schema.tables.clone() {
            for version in self.query_table_versions(&table.name)? {
                let schema_version = self
                    .schema_version_for_alias(version.schema_version_alias())
                    .ok_or(Error::InvalidStoredValue("version schema alias must exist"))?;
                families.insert(version_storage_table_name_for_schema(
                    version.table(),
                    version.layer(),
                    schema_version,
                    self.catalogue.current_schema_version_id,
                ));
            }
        }
        Ok(families.into_iter().collect())
    }

    fn direct_store_entry_count(&self, store: &str) -> Result<usize, Error> {
        Ok(self.database.direct_record_store(store)?.prefix(&[])?.len())
    }

    fn delete_direct_store_entries(&self, store: &str) -> Result<usize, Error> {
        let direct = self.database.direct_record_store(store)?;
        let keys = direct
            .prefix_entries(&[])?
            .into_iter()
            .map(|entry| entry.key)
            .collect::<Vec<Vec<Value>>>();
        let count = keys.len();
        for key in keys {
            direct.delete(&key)?;
        }
        Ok(count)
    }
}
