//! Edge cache eviction classification and manual cold-state eviction.

use std::collections::BTreeSet;

use groove::records::Value;
use groove::storage::OrderedKvStorage;

use crate::peer::PeerEvictionPins;
use crate::schema::{CONTENT_CHECKPOINTS_STORE, CONTENT_EXTENTS_STORE, CONTENT_META_STORE};
use crate::tx::{DurabilityTier, Fate, TxId};

use super::*;

/// Conservative edge-cache classification for cached state.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum EdgeCacheClass {
    /// State that may be dropped and regenerated by refetch.
    Evictable,
    /// State that must survive manual and future automatic eviction.
    Pinned,
}

/// Counts returned by [`NodeState::evict_cold`].
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct EvictColdReport {
    /// Number of direct-store large-value extent byte entries removed.
    pub content_extent_entries: usize,
    /// Number of materialized large-value checkpoint byte entries removed.
    pub content_checkpoint_entries: usize,
    /// Number of large-value metadata entries observed and preserved.
    pub content_meta_entries_pinned: usize,
    /// Number of stored row-version rows classified as evictable and removed.
    pub row_versions_evictable: usize,
    /// Number of stored row-version transactions classified as pinned.
    pub row_versions_pinned: usize,
    /// Number of parked family entries observed and preserved.
    pub parked_families_pinned: usize,
    /// Number of pending-fate transactions observed and preserved.
    pub fate_pending_txs_pinned: usize,
    /// Number of peer-deferred edge-fate transactions observed and preserved.
    pub deferred_edge_fate_txs_pinned: usize,
    /// Number of referenced scope subscriptions observed and preserved.
    pub referenced_scope_subscriptions_pinned: usize,
}

impl<S> NodeState<S>
where
    S: OrderedKvStorage,
{
    /// Return the conservative cache class for one stored row version.
    ///
    /// Cold globally accepted row versions are evictable unless some edge pin
    /// source names their transaction. Everything uncertain stays pinned.
    pub fn classify_row_version_for_eviction(
        &mut self,
        tx_id: TxId,
        peer_pins: &PeerEvictionPins,
    ) -> Result<EdgeCacheClass, Error> {
        if peer_pins.deferred_edge_fate_txs.contains(&tx_id) {
            return Ok(EdgeCacheClass::Pinned);
        }
        let Some(tx) = self.query_transaction(tx_id)? else {
            return Ok(EdgeCacheClass::Pinned);
        };
        if matches!(tx.fate, Fate::Pending) {
            return Ok(EdgeCacheClass::Pinned);
        }
        if matches!(tx.fate, Fate::Accepted) && tx.durability == DurabilityTier::Global {
            Ok(EdgeCacheClass::Evictable)
        } else {
            Ok(EdgeCacheClass::Pinned)
        }
    }

    /// Manually drop evictable cold edge-cache state.
    ///
    /// This is intentionally not called by any automatic trigger. It preserves
    /// large-value metadata, fate-pending rows, peer-deferred edge fates,
    /// referenced permission scopes, and all parked families.
    pub fn evict_cold(&mut self, peer_pins: &PeerEvictionPins) -> Result<EvictColdReport, Error> {
        let mut report = EvictColdReport {
            parked_families_pinned: self.parking.parked_commit_units.len()
                + self.parking.parked_catalogue_commit_units.len()
                + self.parking.parked_shape_registrations.len(),
            deferred_edge_fate_txs_pinned: peer_pins.deferred_edge_fate_txs.len(),
            referenced_scope_subscriptions_pinned: peer_pins.referenced_scope_subscriptions.len(),
            ..EvictColdReport::default()
        };

        report.content_meta_entries_pinned = self.direct_store_entry_count(CONTENT_META_STORE)?;
        report.content_extent_entries = self.delete_direct_store_entries(CONTENT_EXTENTS_STORE)?;
        report.content_checkpoint_entries =
            self.delete_direct_store_entries(CONTENT_CHECKPOINTS_STORE)?;

        let mut seen_txs = BTreeSet::new();
        let mut batch = self.database.open_batch();
        for table in self.catalogue.schema.tables.clone() {
            for version in self.query_table_versions(&table.name)? {
                let tx_id = self.version_tx_id(&version)?;
                match self.classify_row_version_for_eviction(tx_id, peer_pins)? {
                    EdgeCacheClass::Evictable => {
                        report.row_versions_evictable += 1;
                        let schema_version = self
                            .schema_version_for_alias(version.schema_version_alias())
                            .ok_or(Error::InvalidStoredValue("version schema alias must exist"))?;
                        batch.delete(
                            version_storage_table_name_for_schema(
                                version.table(),
                                version.layer(),
                                schema_version,
                                self.catalogue.current_schema_version_id,
                            ),
                            history_primary_key(&version),
                        );
                    }
                    EdgeCacheClass::Pinned => {
                        if seen_txs.insert(tx_id) {
                            report.row_versions_pinned += 1;
                            if self
                                .query_transaction(tx_id)?
                                .is_some_and(|tx| matches!(tx.fate, Fate::Pending))
                            {
                                report.fate_pending_txs_pinned += 1;
                            }
                        }
                    }
                }
            }
        }
        self.database.commit_batch(batch)?;
        if report.row_versions_evictable > 0 {
            // INV-SYNC-27: once local row-version bodies are removed, no
            // persisted fast known-state cursor may survive. This coarse
            // invalidation is conservative until eviction tracks affected
            // binding views directly.
            self.clear_all_known_state_facts()?;
        }

        Ok(report)
    }

    fn direct_store_entry_count(&self, store: &str) -> Result<usize, Error> {
        Ok(self.database.direct_record_store(store)?.prefix(&[])?.len())
    }

    fn delete_direct_store_entries(&self, store: &str) -> Result<usize, Error> {
        let direct = self.database.direct_record_store(store)?;
        let keys = direct
            .prefix_entries(&[])?
            .into_iter()
            .map(|entry| entry.key)
            .collect::<Vec<Vec<Value>>>();
        let count = keys.len();
        for key in keys {
            direct.delete(&key)?;
        }
        Ok(count)
    }
}
