# .vale.ini
StylesPath = styles

MinAlertLevel = suggestion

Packages = proselint, write-good, MDX, Jazz

[formats]
mdx = md

[*.{md,mdx}]

BasedOnStyles = Vale, proselint, write-good, Jazz

BlockIgnores = (?s)<CodeGroup.*?</CodeGroup>

Vale.Spelling = suggestion
write-good.E-Prime = suggestion
write-good.Weasel = suggestion