packages:
  - "homepage"
  - "design-system"
  - "gcmp"

catalog:
  "@biomejs/biome": 2.1.3
  "react": "19.1.0"
  "react-dom": "19.1.0"
  "@types/react": "19.1.0"
  "@types/react-dom": "19.1.0"
  "typescript": 5.6.2
  "vitest": 3.2.4
  