#if canImport(jazz_swiftFFI)
// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(jazz_swiftFFI)
import jazz_swiftFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_jazz_swift_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_jazz_swift_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureJazzSwiftInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol JazzSwiftRuntimeProtocol: AnyObject, Sendable {
    
    func addServer() throws 
    
    func batchedTick() throws 
    
    func close() throws 
    
    func createSubscription(queryJson: String, sessionJson: String?, tier: String?) throws  -> UInt64
    
    func delete(objectId: String) throws 
    
    func deleteWithSession(objectId: String, writeContextJson: String?) throws 
    
    func executeSubscription(handle: UInt64, callback: SubscriptionCallback) throws 
    
    func flush() throws 
    
    func getSchemaHash() throws  -> String
    
    func insert(table: String, valuesJson: String) throws  -> String
    
    func insertWithSession(table: String, valuesJson: String, writeContextJson: String?) throws  -> String
    
    func onBatchedTickNeeded(callback: BatchedTickCallback?) throws 
    
    func onSyncMessageReceived(messageJson: String) throws 
    
    func onSyncMessageToSend(callback: SyncMessageCallback?) throws 
    
    func query(queryJson: String, sessionJson: String?, tier: String?) throws  -> String
    
    func removeServer() throws 
    
    func subscribe(queryJson: String, callback: SubscriptionCallback, sessionJson: String?, tier: String?) throws  -> UInt64
    
    func unsubscribe(handle: UInt64) throws 
    
    func update(objectId: String, valuesJson: String) throws 
    
    func updateWithSession(objectId: String, valuesJson: String, writeContextJson: String?) throws 
    
}
open class JazzSwiftRuntime: JazzSwiftRuntimeProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_jazz_swift_fn_clone_jazzswiftruntime(self.handle, $0) }
    }
public convenience init(schemaJson: String, appId: String, jazzEnv: String, userBranch: String, tier: String?, dataPath: String?)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeJazzSwiftError_lift) {
    uniffi_jazz_swift_fn_constructor_jazzswiftruntime_new(
        FfiConverterString.lower(schemaJson),
        FfiConverterString.lower(appId),
        FfiConverterString.lower(jazzEnv),
        FfiConverterString.lower(userBranch),
        FfiConverterOptionString.lower(tier),
        FfiConverterOptionString.lower(dataPath),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_jazz_swift_fn_free_jazzswiftruntime(handle, $0) }
    }

    

    
open func addServer()throws   {try rustCallWithError(FfiConverterTypeJazzSwiftError_lift) {
    uniffi_jazz_swift_fn_method_jazzswiftruntime_add_server(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func batchedTick()throws   {try rustCallWithError(FfiConverterTypeJazzSwiftError_lift) {
    uniffi_jazz_swift_fn_method_jazzswiftruntime_batched_tick(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func close()throws   {try rustCallWithError(FfiConverterTypeJazzSwiftError_lift) {
    uniffi_jazz_swift_fn_method_jazzswiftruntime_close(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func createSubscription(queryJson: String, sessionJson: String?, tier: String?)throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeJazzSwiftError_lift) {
    uniffi_jazz_swift_fn_method_jazzswiftruntime_create_subscription(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(queryJson),
        FfiConverterOptionString.lower(sessionJson),
        FfiConverterOptionString.lower(tier),$0
    )
})
}
    
open func delete(objectId: String)throws   {try rustCallWithError(FfiConverterTypeJazzSwiftError_lift) {
    uniffi_jazz_swift_fn_method_jazzswiftruntime_delete(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(objectId),$0
    )
}
}
    
open func deleteWithSession(objectId: String, writeContextJson: String?)throws   {try rustCallWithError(FfiConverterTypeJazzSwiftError_lift) {
    uniffi_jazz_swift_fn_method_jazzswiftruntime_deletewithsession(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(objectId),
        FfiConverterOptionString.lower(writeContextJson),$0
    )
}
}
    
open func executeSubscription(handle: UInt64, callback: SubscriptionCallback)throws   {try rustCallWithError(FfiConverterTypeJazzSwiftError_lift) {
    uniffi_jazz_swift_fn_method_jazzswiftruntime_execute_subscription(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(handle),
        FfiConverterCallbackInterfaceSubscriptionCallback_lower(callback),$0
    )
}
}
    
open func flush()throws   {try rustCallWithError(FfiConverterTypeJazzSwiftError_lift) {
    uniffi_jazz_swift_fn_method_jazzswiftruntime_flush(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func getSchemaHash()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeJazzSwiftError_lift) {
    uniffi_jazz_swift_fn_method_jazzswiftruntime_get_schema_hash(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func insert(table: String, valuesJson: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeJazzSwiftError_lift) {
    uniffi_jazz_swift_fn_method_jazzswiftruntime_insert(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(table),
        FfiConverterString.lower(valuesJson),$0
    )
})
}
    
open func insertWithSession(table: String, valuesJson: String, writeContextJson: String?)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeJazzSwiftError_lift) {
    uniffi_jazz_swift_fn_method_jazzswiftruntime_insert_with_session(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(table),
        FfiConverterString.lower(valuesJson),
        FfiConverterOptionString.lower(writeContextJson),$0
    )
})
}
    
open func onBatchedTickNeeded(callback: BatchedTickCallback?)throws   {try rustCallWithError(FfiConverterTypeJazzSwiftError_lift) {
    uniffi_jazz_swift_fn_method_jazzswiftruntime_on_batched_tick_needed(
            self.uniffiCloneHandle(),
        FfiConverterOptionCallbackInterfaceBatchedTickCallback.lower(callback),$0
    )
}
}
    
open func onSyncMessageReceived(messageJson: String)throws   {try rustCallWithError(FfiConverterTypeJazzSwiftError_lift) {
    uniffi_jazz_swift_fn_method_jazzswiftruntime_on_sync_message_received(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(messageJson),$0
    )
}
}
    
open func onSyncMessageToSend(callback: SyncMessageCallback?)throws   {try rustCallWithError(FfiConverterTypeJazzSwiftError_lift) {
    uniffi_jazz_swift_fn_method_jazzswiftruntime_on_sync_message_to_send(
            self.uniffiCloneHandle(),
        FfiConverterOptionCallbackInterfaceSyncMessageCallback.lower(callback),$0
    )
}
}
    
open func query(queryJson: String, sessionJson: String?, tier: String?)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeJazzSwiftError_lift) {
    uniffi_jazz_swift_fn_method_jazzswiftruntime_query(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(queryJson),
        FfiConverterOptionString.lower(sessionJson),
        FfiConverterOptionString.lower(tier),$0
    )
})
}
    
open func removeServer()throws   {try rustCallWithError(FfiConverterTypeJazzSwiftError_lift) {
    uniffi_jazz_swift_fn_method_jazzswiftruntime_remove_server(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func subscribe(queryJson: String, callback: SubscriptionCallback, sessionJson: String?, tier: String?)throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeJazzSwiftError_lift) {
    uniffi_jazz_swift_fn_method_jazzswiftruntime_subscribe(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(queryJson),
        FfiConverterCallbackInterfaceSubscriptionCallback_lower(callback),
        FfiConverterOptionString.lower(sessionJson),
        FfiConverterOptionString.lower(tier),$0
    )
})
}
    
open func unsubscribe(handle: UInt64)throws   {try rustCallWithError(FfiConverterTypeJazzSwiftError_lift) {
    uniffi_jazz_swift_fn_method_jazzswiftruntime_unsubscribe(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(handle),$0
    )
}
}
    
open func update(objectId: String, valuesJson: String)throws   {try rustCallWithError(FfiConverterTypeJazzSwiftError_lift) {
    uniffi_jazz_swift_fn_method_jazzswiftruntime_update(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(objectId),
        FfiConverterString.lower(valuesJson),$0
    )
}
}
    
open func updateWithSession(objectId: String, valuesJson: String, writeContextJson: String?)throws   {try rustCallWithError(FfiConverterTypeJazzSwiftError_lift) {
    uniffi_jazz_swift_fn_method_jazzswiftruntime_update_with_session(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(objectId),
        FfiConverterString.lower(valuesJson),
        FfiConverterOptionString.lower(writeContextJson),$0
    )
}
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeJazzSwiftRuntime: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = JazzSwiftRuntime

    public static func lift(_ handle: UInt64) throws -> JazzSwiftRuntime {
        return JazzSwiftRuntime(unsafeFromHandle: handle)
    }

    public static func lower(_ value: JazzSwiftRuntime) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> JazzSwiftRuntime {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: JazzSwiftRuntime, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJazzSwiftRuntime_lift(_ handle: UInt64) throws -> JazzSwiftRuntime {
    return try FfiConverterTypeJazzSwiftRuntime.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJazzSwiftRuntime_lower(_ value: JazzSwiftRuntime) -> UInt64 {
    return FfiConverterTypeJazzSwiftRuntime.lower(value)
}




public enum JazzSwiftError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case InvalidJson(message: String
    )
    case InvalidUuid(message: String
    )
    case InvalidTier(message: String
    )
    case Schema(message: String
    )
    case Runtime(message: String
    )
    case Internal(message: String
    )

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension JazzSwiftError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeJazzSwiftError: FfiConverterRustBuffer {
    typealias SwiftType = JazzSwiftError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> JazzSwiftError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InvalidJson(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .InvalidUuid(
            message: try FfiConverterString.read(from: &buf)
            )
        case 3: return .InvalidTier(
            message: try FfiConverterString.read(from: &buf)
            )
        case 4: return .Schema(
            message: try FfiConverterString.read(from: &buf)
            )
        case 5: return .Runtime(
            message: try FfiConverterString.read(from: &buf)
            )
        case 6: return .Internal(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: JazzSwiftError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .InvalidJson(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .InvalidUuid(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .InvalidTier(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Schema(message):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Runtime(message):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Internal(message):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJazzSwiftError_lift(_ buf: RustBuffer) throws -> JazzSwiftError {
    return try FfiConverterTypeJazzSwiftError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeJazzSwiftError_lower(_ value: JazzSwiftError) -> RustBuffer {
    return FfiConverterTypeJazzSwiftError.lower(value)
}




public protocol BatchedTickCallback: AnyObject, Sendable {
    
    func requestBatchedTick() 
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceBatchedTickCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceBatchedTickCallback] = [UniffiVTableCallbackInterfaceBatchedTickCallback(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterCallbackInterfaceBatchedTickCallback.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface BatchedTickCallback: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterCallbackInterfaceBatchedTickCallback.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface BatchedTickCallback: handle missing in uniffiClone")
            }
        },
        requestBatchedTick: { (
            uniffiHandle: UInt64,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceBatchedTickCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.requestBatchedTick(
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )]
}

private func uniffiCallbackInitBatchedTickCallback() {
    uniffi_jazz_swift_fn_init_callback_vtable_batchedtickcallback(UniffiCallbackInterfaceBatchedTickCallback.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceBatchedTickCallback {
    fileprivate static let handleMap = UniffiHandleMap<BatchedTickCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceBatchedTickCallback : FfiConverter {
    typealias SwiftType = BatchedTickCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceBatchedTickCallback_lift(_ handle: UInt64) throws -> BatchedTickCallback {
    return try FfiConverterCallbackInterfaceBatchedTickCallback.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceBatchedTickCallback_lower(_ v: BatchedTickCallback) -> UInt64 {
    return FfiConverterCallbackInterfaceBatchedTickCallback.lower(v)
}




public protocol SubscriptionCallback: AnyObject, Sendable {
    
    func onUpdate(deltaJson: String) 
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceSubscriptionCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceSubscriptionCallback] = [UniffiVTableCallbackInterfaceSubscriptionCallback(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterCallbackInterfaceSubscriptionCallback.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface SubscriptionCallback: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterCallbackInterfaceSubscriptionCallback.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface SubscriptionCallback: handle missing in uniffiClone")
            }
        },
        onUpdate: { (
            uniffiHandle: UInt64,
            deltaJson: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceSubscriptionCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onUpdate(
                     deltaJson: try FfiConverterString.lift(deltaJson)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )]
}

private func uniffiCallbackInitSubscriptionCallback() {
    uniffi_jazz_swift_fn_init_callback_vtable_subscriptioncallback(UniffiCallbackInterfaceSubscriptionCallback.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceSubscriptionCallback {
    fileprivate static let handleMap = UniffiHandleMap<SubscriptionCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceSubscriptionCallback : FfiConverter {
    typealias SwiftType = SubscriptionCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceSubscriptionCallback_lift(_ handle: UInt64) throws -> SubscriptionCallback {
    return try FfiConverterCallbackInterfaceSubscriptionCallback.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceSubscriptionCallback_lower(_ v: SubscriptionCallback) -> UInt64 {
    return FfiConverterCallbackInterfaceSubscriptionCallback.lower(v)
}




public protocol SyncMessageCallback: AnyObject, Sendable {
    
    func onSyncMessage(destinationKind: String, destinationId: String, payloadJson: String, isCatalogue: Bool) 
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceSyncMessageCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceSyncMessageCallback] = [UniffiVTableCallbackInterfaceSyncMessageCallback(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterCallbackInterfaceSyncMessageCallback.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface SyncMessageCallback: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterCallbackInterfaceSyncMessageCallback.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface SyncMessageCallback: handle missing in uniffiClone")
            }
        },
        onSyncMessage: { (
            uniffiHandle: UInt64,
            destinationKind: RustBuffer,
            destinationId: RustBuffer,
            payloadJson: RustBuffer,
            isCatalogue: Int8,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceSyncMessageCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onSyncMessage(
                     destinationKind: try FfiConverterString.lift(destinationKind),
                     destinationId: try FfiConverterString.lift(destinationId),
                     payloadJson: try FfiConverterString.lift(payloadJson),
                     isCatalogue: try FfiConverterBool.lift(isCatalogue)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )]
}

private func uniffiCallbackInitSyncMessageCallback() {
    uniffi_jazz_swift_fn_init_callback_vtable_syncmessagecallback(UniffiCallbackInterfaceSyncMessageCallback.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceSyncMessageCallback {
    fileprivate static let handleMap = UniffiHandleMap<SyncMessageCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceSyncMessageCallback : FfiConverter {
    typealias SwiftType = SyncMessageCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceSyncMessageCallback_lift(_ handle: UInt64) throws -> SyncMessageCallback {
    return try FfiConverterCallbackInterfaceSyncMessageCallback.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceSyncMessageCallback_lower(_ v: SyncMessageCallback) -> UInt64 {
    return FfiConverterCallbackInterfaceSyncMessageCallback.lower(v)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionCallbackInterfaceBatchedTickCallback: FfiConverterRustBuffer {
    typealias SwiftType = BatchedTickCallback?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterCallbackInterfaceBatchedTickCallback.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterCallbackInterfaceBatchedTickCallback.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionCallbackInterfaceSyncMessageCallback: FfiConverterRustBuffer {
    typealias SwiftType = SyncMessageCallback?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterCallbackInterfaceSyncMessageCallback.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterCallbackInterfaceSyncMessageCallback.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}
public func currentTimestampMs() -> Int64  {
    return try!  FfiConverterInt64.lift(try! rustCall() {
    uniffi_jazz_swift_fn_func_current_timestamp_ms($0
    )
})
}
public func generateId() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_jazz_swift_fn_func_generate_id($0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_jazz_swift_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_jazz_swift_checksum_func_current_timestamp_ms() != 39072) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jazz_swift_checksum_func_generate_id() != 4974) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jazz_swift_checksum_method_jazzswiftruntime_add_server() != 24966) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jazz_swift_checksum_method_jazzswiftruntime_batched_tick() != 60148) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jazz_swift_checksum_method_jazzswiftruntime_close() != 6471) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jazz_swift_checksum_method_jazzswiftruntime_create_subscription() != 49060) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jazz_swift_checksum_method_jazzswiftruntime_delete() != 24615) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jazz_swift_checksum_method_jazzswiftruntime_deletewithsession() != 37831) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jazz_swift_checksum_method_jazzswiftruntime_execute_subscription() != 4417) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jazz_swift_checksum_method_jazzswiftruntime_flush() != 6805) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jazz_swift_checksum_method_jazzswiftruntime_get_schema_hash() != 55204) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jazz_swift_checksum_method_jazzswiftruntime_insert() != 41483) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jazz_swift_checksum_method_jazzswiftruntime_insert_with_session() != 17364) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jazz_swift_checksum_method_jazzswiftruntime_on_batched_tick_needed() != 29933) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jazz_swift_checksum_method_jazzswiftruntime_on_sync_message_received() != 52469) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jazz_swift_checksum_method_jazzswiftruntime_on_sync_message_to_send() != 20162) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jazz_swift_checksum_method_jazzswiftruntime_query() != 41098) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jazz_swift_checksum_method_jazzswiftruntime_remove_server() != 41813) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jazz_swift_checksum_method_jazzswiftruntime_subscribe() != 57956) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jazz_swift_checksum_method_jazzswiftruntime_unsubscribe() != 34091) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jazz_swift_checksum_method_jazzswiftruntime_update() != 22317) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jazz_swift_checksum_method_jazzswiftruntime_update_with_session() != 24784) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jazz_swift_checksum_constructor_jazzswiftruntime_new() != 31174) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jazz_swift_checksum_method_batchedtickcallback_request_batched_tick() != 37900) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jazz_swift_checksum_method_subscriptioncallback_on_update() != 17936) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_jazz_swift_checksum_method_syncmessagecallback_on_sync_message() != 13444) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitBatchedTickCallback()
    uniffiCallbackInitSubscriptionCallback()
    uniffiCallbackInitSyncMessageCallback()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureJazzSwiftInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all
#endif
