// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "cojson-core-rn.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "CojsonCoreRnSpec.h"

@interface CojsonCoreRn : NSObject <NativeCojsonCoreRnSpec>
#else
#import <React/RCTBridgeModule.h>

@interface CojsonCoreRn : NSObject <RCTBridgeModule>
#endif

@end