/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const __nodeFs = require('node:fs')
const __nodePath = require('node:path')
const { WASI: __nodeWASI } = require('node:wasi')
const { Worker } = require('node:worker_threads')

const {
  createOnMessage: __wasmCreateOnMessageForFsProxy,
  getDefaultContext: __emnapiGetDefaultContext,
  instantiateNapiModuleSync: __emnapiInstantiateNapiModuleSync,
} = require('@napi-rs/wasm-runtime')

const __rootDir = __nodePath.parse(process.cwd()).root

const __wasi = new __nodeWASI({
  version: 'preview1',
  env: process.env,
  preopens: {
    [__rootDir]: __rootDir,
  }
})

const __emnapiContext = __emnapiGetDefaultContext()

const __sharedMemory = new WebAssembly.Memory({
  initial: 4000,
  maximum: 65536,
  shared: true,
})

let __wasmFilePath = __nodePath.join(__dirname, 'cojson-core-napi.wasm32-wasi.wasm')
const __wasmDebugFilePath = __nodePath.join(__dirname, 'cojson-core-napi.wasm32-wasi.debug.wasm')

if (__nodeFs.existsSync(__wasmDebugFilePath)) {
  __wasmFilePath = __wasmDebugFilePath
} else if (!__nodeFs.existsSync(__wasmFilePath)) {
  try {
    __wasmFilePath = __nodePath.resolve('cojson-core-napi-wasm32-wasi')
  } catch {
    throw new Error('Cannot find cojson-core-napi.wasm32-wasi.wasm file, and cojson-core-napi-wasm32-wasi package is not installed.')
  }
}

const { instance: __napiInstance, module: __wasiModule, napiModule: __napiModule } = __emnapiInstantiateNapiModuleSync(__nodeFs.readFileSync(__wasmFilePath), {
  context: __emnapiContext,
  asyncWorkPoolSize: (function() {
    const threadsSizeFromEnv = Number(process.env.NAPI_RS_ASYNC_WORK_POOL_SIZE ?? process.env.UV_THREADPOOL_SIZE)
    // NaN > 0 is false
    if (threadsSizeFromEnv > 0) {
      return threadsSizeFromEnv
    } else {
      return 4
    }
  })(),
  reuseWorker: true,
  wasi: __wasi,
  onCreateWorker() {
    const worker = new Worker(__nodePath.join(__dirname, 'wasi-worker.mjs'), {
      env: process.env,
    })
    worker.onmessage = ({ data }) => {
      __wasmCreateOnMessageForFsProxy(__nodeFs)(data)
    }

    // The main thread of Node.js waits for all the active handles before exiting.
    // But Rust threads are never waited without `thread::join`.
    // So here we hack the code of Node.js to prevent the workers from being referenced (active).
    // According to https://github.com/nodejs/node/blob/19e0d472728c79d418b74bddff588bea70a403d0/lib/internal/worker.js#L415,
    // a worker is consist of two handles: kPublicPort and kHandle.
    {
      const kPublicPort = Object.getOwnPropertySymbols(worker).find(s =>
        s.toString().includes("kPublicPort")
      );
      if (kPublicPort) {
        worker[kPublicPort].ref = () => {};
      }

      const kHandle = Object.getOwnPropertySymbols(worker).find(s =>
        s.toString().includes("kHandle")
      );
      if (kHandle) {
        worker[kHandle].ref = () => {};
      }

      worker.unref();
    }
    return worker
  },
  overwriteImports(importObject) {
    importObject.env = {
      ...importObject.env,
      ...importObject.napi,
      ...importObject.emnapi,
      memory: __sharedMemory,
    }
    return importObject
  },
  beforeInit({ instance }) {
    for (const name of Object.keys(instance.exports)) {
      if (name.startsWith('__napi_register__')) {
        instance.exports[name]()
      }
    }
  },
})
module.exports = __napiModule.exports
module.exports.Blake3Hasher = __napiModule.exports.Blake3Hasher
module.exports.SessionLog = __napiModule.exports.SessionLog
module.exports.blake3HashOnce = __napiModule.exports.blake3HashOnce
module.exports.blake3HashOnceWithContext = __napiModule.exports.blake3HashOnceWithContext
module.exports.decrypt = __napiModule.exports.decrypt
module.exports.decryptXsalsa20 = __napiModule.exports.decryptXsalsa20
module.exports.ed25519Sign = __napiModule.exports.ed25519Sign
module.exports.ed25519SignatureFromBytes = __napiModule.exports.ed25519SignatureFromBytes
module.exports.ed25519SigningKeyFromBytes = __napiModule.exports.ed25519SigningKeyFromBytes
module.exports.ed25519SigningKeySign = __napiModule.exports.ed25519SigningKeySign
module.exports.ed25519SigningKeyToPublic = __napiModule.exports.ed25519SigningKeyToPublic
module.exports.ed25519Verify = __napiModule.exports.ed25519Verify
module.exports.ed25519VerifyingKey = __napiModule.exports.ed25519VerifyingKey
module.exports.ed25519VerifyingKeyFromBytes = __napiModule.exports.ed25519VerifyingKeyFromBytes
module.exports.encrypt = __napiModule.exports.encrypt
module.exports.encryptXsalsa20 = __napiModule.exports.encryptXsalsa20
module.exports.generateNonce = __napiModule.exports.generateNonce
module.exports.getSealerId = __napiModule.exports.getSealerId
module.exports.getSignerId = __napiModule.exports.getSignerId
module.exports.newEd25519SigningKey = __napiModule.exports.newEd25519SigningKey
module.exports.newX25519PrivateKey = __napiModule.exports.newX25519PrivateKey
module.exports.seal = __napiModule.exports.seal
module.exports.sign = __napiModule.exports.sign
module.exports.unseal = __napiModule.exports.unseal
module.exports.verify = __napiModule.exports.verify
module.exports.x25519DiffieHellman = __napiModule.exports.x25519DiffieHellman
module.exports.x25519PublicKey = __napiModule.exports.x25519PublicKey
