// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "rn-cojson-core-spec.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RnCojsonCoreSpec.h"

@interface RnCojsonCoreSpec : NSObject <NativeRnCojsonCoreSpecSpec>
#else
#import <React/RCTBridgeModule.h>

@interface RnCojsonCoreSpec : NSObject <RCTBridgeModule>
#endif

@end