/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function generateId(): string;
export declare function currentTimestamp(): number;
export declare function parseSchema(json: string): any;
export declare class NapiRuntime {
  /** Create a new NapiRuntime with BfTree-backed persistent storage. */
  constructor(
    schemaJson: string,
    appId: string,
    grooveEnv: string,
    userBranch: string,
    dataPath: string,
    tier?: string | undefined | null,
  );
  insert(table: string, values: any): string;
  update(objectId: string, values: any): void;
  delete(objectId: string): void;
  query(
    queryJson: string,
    sessionJson?: string | undefined | null,
    settledTier?: string | undefined | null,
  ): Promise<any>;
  subscribe(
    queryJson: string,
    onUpdate: (...args: any[]) => any,
    sessionJson?: string | undefined | null,
    settledTier?: string | undefined | null,
  ): number;
  unsubscribe(handle: number): void;
  insertPersisted(table: string, values: any, tier: string): Promise<string>;
  updatePersisted(objectId: string, values: any, tier: string): Promise<void>;
  deletePersisted(objectId: string, tier: string): Promise<void>;
  onSyncMessageReceived(messageJson: string): void;
  onSyncMessageToSend(callback: (...args: any[]) => any): void;
  addServer(): void;
  addClient(): string;
  addClientWithFullSync(): string;
  getSchema(): any;
  flush(): void;
}
