import { expect, it } from "vitest";
import { schema as s } from "../schema-namespace.js";
import { toWriteRecord } from "../runtime/value-converter.js";
import { equalityValue } from "./equality-data.js";
import { encryptedSchemas } from "./encrypted-schema.js";

const names = [
  "flag",
  "integer",
  "wide",
  "real",
  "text",
  "bytes",
  "uuid",
  "time",
  "json",
  "variant",
  "payload",
  "numbers",
  "words",
  "maybeText",
  "maybeFlag",
] as const;
const app = s.defineApp({
  projects: s.table({ title: s.string() }, {}),
  values: s
    .table(
      {
        projectId: s.uuid(),
        flag: s.boolean(),
        integer: s.int(),
        wide: s.bigint(),
        real: s.float(),
        text: s.string(),
        bytes: s.bytes(),
        uuid: s.uuid(),
        time: s.timestamp(),
        json: s.json(),
        variant: s.enum("a", "b"),
        payload: s.enum({ v: { n: s.float() } }),
        numbers: s.array(s.float()),
        words: s.array(s.string()),
        maybeText: s.string().optional(),
        maybeFlag: s.boolean().optional(),
      },
      { project: s.rel("projects", "projectId") },
    )
    .encrypted({
      space: "projectId",
      columns: [...names],
      indexes: Object.fromEntries(names.map((name) => [name, "equality"])) as Record<
        (typeof names)[number],
        "equality"
      >,
    }),
});

// Hand-authored wire literals, not snapshots generated by the encoder under test.
// Single-column records have no field-count or offset header.
it.each([
  ["flag", false, "00"],
  ["flag", true, "01"],
  ["integer", -2147483648, "00000080"],
  ["integer", 2147483647, "ffffff7f"],
  ["wide", -9223372036854775808n, "0000000000000080"],
  ["wide", 9223372036854775807n, "ffffffffffffff7f"],
  ["real", 1.5, "000000000000f83f"],
  ["real", -0, "0000000000000000"],
  ["real", 0, "0000000000000000"],
  ["text", "é", "02c3a9"],
  ["text", "", "02"],
  ["bytes", new Uint8Array([0, 255]), "0200ff"],
  ["uuid", "00112233-4455-6677-8899-AABBCCDDEEFF", "00112233445566778899aabbccddeeff"],
  ["time", new Date(1), "0100000000000000"],
  ["json", { x: 1 }, "027b2278223a317d"],
  ["variant", "a", "0261"],
  ["payload", { type: "v", n: -0 }, "010000007600080000000000000000000000"],
  ["numbers", [-0, 1.5], "0000000000000000000000000000f83f"],
  ["numbers", [], ""],
  ["words", ["a", "bc"], "020000000a0000000261026263"],
  ["words", [], "00000000"],
  ["maybeText", null, "00"],
  ["maybeText", "hi", "01026869"],
  ["maybeFlag", null, "0000"],
  ["maybeFlag", true, "0101"],
] as const)("pins equality value bytes for %s (%s)", (name, value, hex) => {
  const logical = encryptedSchemas.get(app.values._schema)!.logical;
  const typed = toWriteRecord({ [name]: value }, logical, "values")[name]!;
  const encoded = equalityValue(app.values, name, typed);
  expect(Array.from(encoded, (byte) => byte.toString(16).padStart(2, "0")).join("")).toBe(hex);
});
