import { table, col } from "jazz-tools";

table("codex_sessions", {
  session_id: col.string(),
  rollout_path: col.string(),
  cwd: col.string(),
  project_root: col.string(),
  repo_root: col.string().optional(),
  git_branch: col.string().optional(),
  originator: col.string().optional(),
  source: col.string().optional(),
  cli_version: col.string().optional(),
  model_provider: col.string().optional(),
  model_name: col.string().optional(),
  reasoning_effort: col.string().optional(),
  agent_nickname: col.string().optional(),
  agent_role: col.string().optional(),
  agent_path: col.string().optional(),
  first_user_message: col.string().optional(),
  latest_user_message: col.string().optional(),
  latest_assistant_message: col.string().optional(),
  latest_assistant_partial: col.string().optional(),
  latest_preview: col.string().optional(),
  status: col.string(),
  created_at: col.timestamp(),
  updated_at: col.timestamp(),
  latest_activity_at: col.timestamp(),
  last_user_at: col.timestamp().optional(),
  last_assistant_at: col.timestamp().optional(),
  last_completion_at: col.timestamp().optional(),
  metadata_json: col.json().optional(),
});

table("codex_turns", {
  turn_id: col.string(),
  session_id: col.string(),
  session_row_id: col.ref("codex_sessions"),
  sequence: col.int(),
  status: col.string(),
  user_message: col.string().optional(),
  assistant_message: col.string().optional(),
  assistant_partial: col.string().optional(),
  plan_text: col.string().optional(),
  reasoning_summary: col.string().optional(),
  started_at: col.timestamp().optional(),
  completed_at: col.timestamp().optional(),
  duration_ms: col.int().optional(),
  updated_at: col.timestamp(),
});

table("codex_session_presence", {
  session_id: col.string(),
  session_row_id: col.ref("codex_sessions"),
  project_root: col.string(),
  repo_root: col.string().optional(),
  cwd: col.string(),
  state: col.string(),
  current_turn_id: col.string().optional(),
  current_turn_row_id: col.ref("codex_turns").optional(),
  current_turn_status: col.string().optional(),
  started_at: col.timestamp(),
  latest_activity_at: col.timestamp(),
  last_event_at: col.timestamp(),
  last_user_at: col.timestamp().optional(),
  last_assistant_at: col.timestamp().optional(),
  last_completion_at: col.timestamp().optional(),
  last_synced_at: col.timestamp(),
  runtime_pid: col.int().optional(),
  runtime_tty: col.string().optional(),
  runtime_host: col.string().optional(),
  last_heartbeat_at: col.timestamp().optional(),
  updated_at: col.timestamp(),
});

table("codex_sync_states", {
  source_id: col.string(),
  absolute_path: col.string(),
  session_id: col.string().optional(),
  session_row_id: col.ref("codex_sessions").optional(),
  line_count: col.int(),
  synced_at: col.timestamp(),
});

table("j_agent_definitions", {
  definition_id: col.string(),
  name: col.string(),
  version: col.string(),
  source_kind: col.string(),
  entrypoint: col.string(),
  metadata_json: col.json().optional(),
  created_at: col.timestamp(),
  updated_at: col.timestamp(),
});

table("j_agent_runs", {
  run_id: col.string(),
  definition_id: col.string(),
  definition_row_id: col.ref("j_agent_definitions"),
  status: col.string(),
  project_root: col.string(),
  repo_root: col.string().optional(),
  cwd: col.string().optional(),
  trigger_source: col.string().optional(),
  parent_session_id: col.string().optional(),
  parent_session_row_id: col.ref("codex_sessions").optional(),
  parent_turn_id: col.string().optional(),
  initiator_session_id: col.string().optional(),
  initiator_session_row_id: col.ref("codex_sessions").optional(),
  requested_role: col.string().optional(),
  requested_model: col.string().optional(),
  requested_reasoning_effort: col.string().optional(),
  fork_turns: col.int().optional(),
  current_step_key: col.string().optional(),
  input_json: col.json().optional(),
  output_json: col.json().optional(),
  error_text: col.string().optional(),
  started_at: col.timestamp(),
  updated_at: col.timestamp(),
  completed_at: col.timestamp().optional(),
});

table("j_agent_steps", {
  step_id: col.string(),
  run_id: col.string(),
  run_row_id: col.ref("j_agent_runs"),
  sequence: col.int(),
  step_key: col.string(),
  step_kind: col.string(),
  status: col.string(),
  input_json: col.json().optional(),
  output_json: col.json().optional(),
  error_text: col.string().optional(),
  started_at: col.timestamp(),
  updated_at: col.timestamp(),
  completed_at: col.timestamp().optional(),
});

table("j_agent_attempts", {
  attempt_id: col.string(),
  run_id: col.string(),
  run_row_id: col.ref("j_agent_runs"),
  step_id: col.string(),
  step_row_id: col.ref("j_agent_steps"),
  attempt: col.int(),
  status: col.string(),
  codex_session_id: col.string().optional(),
  codex_session_row_id: col.ref("codex_sessions").optional(),
  codex_turn_id: col.string().optional(),
  codex_turn_row_id: col.ref("codex_turns").optional(),
  fork_turns: col.int().optional(),
  model_name: col.string().optional(),
  reasoning_effort: col.string().optional(),
  started_at: col.timestamp(),
  completed_at: col.timestamp().optional(),
  error_text: col.string().optional(),
});

table("j_agent_waits", {
  wait_id: col.string(),
  run_id: col.string(),
  run_row_id: col.ref("j_agent_runs"),
  step_id: col.string(),
  step_row_id: col.ref("j_agent_steps"),
  wait_kind: col.string(),
  target_session_id: col.string().optional(),
  target_session_row_id: col.ref("codex_sessions").optional(),
  target_turn_id: col.string().optional(),
  target_turn_row_id: col.ref("codex_turns").optional(),
  resume_condition_json: col.json().optional(),
  status: col.string(),
  started_at: col.timestamp(),
  resumed_at: col.timestamp().optional(),
});

table("j_agent_session_bindings", {
  binding_id: col.string(),
  run_id: col.string(),
  run_row_id: col.ref("j_agent_runs"),
  codex_session_id: col.string(),
  codex_session_row_id: col.ref("codex_sessions"),
  binding_role: col.string(),
  parent_session_id: col.string().optional(),
  parent_session_row_id: col.ref("codex_sessions").optional(),
  created_at: col.timestamp(),
});

table("j_agent_artifacts", {
  artifact_id: col.string(),
  run_id: col.string(),
  run_row_id: col.ref("j_agent_runs"),
  step_id: col.string().optional(),
  step_row_id: col.ref("j_agent_steps").optional(),
  kind: col.string(),
  path: col.string(),
  text_preview: col.string().optional(),
  metadata_json: col.json().optional(),
  created_at: col.timestamp(),
});
