// Auto generated by Craby. DO NOT EDIT.
#include <CxxCojsonCoreRnModule.hpp>
#include <ReactCommon/CxxTurboModuleUtils.h>
#include <jni.h>

jint JNI_OnLoad(JavaVM *vm, void *reserved) {
  facebook::react::registerCxxModuleToGlobalModuleMap(
    craby::cojsoncorern::modules::CxxCojsonCoreRnModule::kModuleName,
    [](std::shared_ptr<facebook::react::CallInvoker> jsInvoker) {
      return std::make_shared<craby::cojsoncorern::modules::CxxCojsonCoreRnModule>(jsInvoker);
    });
  return JNI_VERSION_1_6;
}

extern "C"
JNIEXPORT void JNICALL
Java_rs_craby_cojsoncorern_CojsonCoreRnPackage_nativeSetDataPath(JNIEnv *env, jclass clazz, jstring jDataPath) {
  auto dataPath = std::string(env->GetStringUTFChars(jDataPath, nullptr));
  craby::cojsoncorern::modules::CxxCojsonCoreRnModule::dataPath = dataPath;
}
