export interface SeedVenue {
  name: string;
  city: string;
  country: string;
  lat: number;
  lng: number;
  capacity: number;
}

export const defaultBandName = "The Groove Syndicate";

export const venues: SeedVenue[] = [
  { name: "O2 Arena", city: "London", country: "UK", lat: 51.503, lng: 0.003, capacity: 20000 },
  {
    name: "Madison Square Garden",
    city: "New York",
    country: "USA",
    lat: 40.7505,
    lng: -73.9934,
    capacity: 20789,
  },
  { name: "Budokan", city: "Tokyo", country: "Japan", lat: 35.6932, lng: 139.75, capacity: 14471 },
  {
    name: "Olympiastadion",
    city: "Berlin",
    country: "Germany",
    lat: 52.5147,
    lng: 13.2395,
    capacity: 74475,
  },
  {
    name: "Allianz Parque",
    city: "São Paulo",
    country: "Brazil",
    lat: -23.5275,
    lng: -46.6781,
    capacity: 43713,
  },
  {
    name: "Qudos Bank Arena",
    city: "Sydney",
    country: "Australia",
    lat: -33.8468,
    lng: 151.0694,
    capacity: 21032,
  },
  {
    name: "AccorHotels Arena",
    city: "Paris",
    country: "France",
    lat: 48.8386,
    lng: 2.3786,
    capacity: 20300,
  },
  {
    name: "Movistar Arena",
    city: "Buenos Aires",
    country: "Argentina",
    lat: -34.6345,
    lng: -58.4122,
    capacity: 15500,
  },
  {
    name: "Rogers Centre",
    city: "Toronto",
    country: "Canada",
    lat: 43.6414,
    lng: -79.3894,
    capacity: 49282,
  },
  {
    name: "Cape Town Stadium",
    city: "Cape Town",
    country: "South Africa",
    lat: -33.9035,
    lng: 18.4113,
    capacity: 64100,
  },
  {
    name: "Red Rocks Amphitheatre",
    city: "Morrison",
    country: "USA",
    lat: 39.6654,
    lng: -105.2057,
    capacity: 9525,
  },
  {
    name: "Paradiso",
    city: "Amsterdam",
    country: "Netherlands",
    lat: 52.3622,
    lng: 4.8838,
    capacity: 1500,
  },
  { name: "Roundhouse", city: "London", country: "UK", lat: 51.5434, lng: -0.1525, capacity: 3300 },
  {
    name: "Blue Note",
    city: "New York",
    country: "USA",
    lat: 40.7311,
    lng: -74.0003,
    capacity: 240,
  },
  {
    name: "Montreux Jazz Lab",
    city: "Montreux",
    country: "Switzerland",
    lat: 46.4312,
    lng: 6.9107,
    capacity: 3500,
  },
  {
    name: "Ronnie Scott's",
    city: "London",
    country: "UK",
    lat: 51.5133,
    lng: -0.1317,
    capacity: 250,
  },
  {
    name: "Hollywood Bowl",
    city: "Los Angeles",
    country: "USA",
    lat: 34.1122,
    lng: -118.3391,
    capacity: 17500,
  },
  {
    name: "Nippon Budokan",
    city: "Tokyo",
    country: "Japan",
    lat: 35.6932,
    lng: 139.75,
    capacity: 14471,
  },
  {
    name: "Zenith Paris",
    city: "Paris",
    country: "France",
    lat: 48.8937,
    lng: 2.3932,
    capacity: 6293,
  },
  {
    name: "Sala Apolo",
    city: "Barcelona",
    country: "Spain",
    lat: 41.3741,
    lng: 2.1688,
    capacity: 1100,
  },
];

export const descriptions: string[] = [
  "Festival stage headline set",
  "Intimate acoustic evening",
  "Deep cuts and new material",
  "Special guest appearance",
  "Headline show",
  "Late-night jazz session",
  "Outdoor amphitheatre under the stars",
  "Unplugged and up close",
  "Full band — horns, strings, the works",
  "Charity benefit concert",
  "Double bill with local act",
  "Rooftop sunset set",
  "Extended set with full visual production",
  "Stripped-back trio format",
  "Late-addition show by popular demand",
];

export const privateNotes: string[] = [
  "Load-in at 2pm. Rider: extra monitors stage left.",
  "Promoter contact: check shared notes.",
  "Sound check at 16:00. Green room confirmed.",
  "Visa paperwork submitted — awaiting confirmation.",
  "After-party at nearby rooftop bar TBD.",
  "Merch table booked. 200 units of new vinyl.",
  "Crew arriving a day early for setup.",
  "Catering: vegetarian options required.",
  "Local press interview at 14:00.",
  "Pyrotechnics approved — fire marshal signed off.",
  "Transport: two buses from hotel, 30 min ride.",
  "Backup generator on standby.",
  "VIP meet-and-greet at 18:30.",
  "Extended set — 3 hours minimum.",
  "Rain contingency plan in place.",
];
