config:
  jazz-cloud2:region: us-east-2
  jazz-cloud2:allowedAccountId: "739068833263"
  jazz-cloud2:domainName: cloud2.aws.cloud.jazz.tools
  jazz-cloud2:containerImageRepository: 739068833263.dkr.ecr.us-east-2.amazonaws.com/jazz-multi-server
  jazz-cloud2:containerImageTag: latest
  jazz-cloud2:dataVolumeSizeGiB: "100"
  jazz-cloud2:instanceType: t3.large
