// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "jazz-rn.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "JazzRnSpec.h"

@interface JazzRn : NSObject <NativeJazzRnSpec>
#else
#import <React/RCTBridgeModule.h>

@interface JazzRn : NSObject <RCTBridgeModule>
#endif

@end