[package]
name = "jazz-crypto"
version = "0.15.12"
edition = "2021"
build = "build.rs"

[dependencies]
cxx = { version = "1.0.160", features = ["alloc", "std", "c++20"] }

[build-dependencies]
cxx-build = "1.0.160"

[lib]
name = "jazz_crypto"
crate-type = ["staticlib"]
path = "src/rust/lib.rs"

