import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import {
  existsSync,
  mkdtempSync,
  mkdirSync,
  readFileSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import test from "node:test";
import { stageNapiLoader } from "./stage-napi-loader.mjs";
import { stageNativeFingerprints } from "./stage-native-fingerprints.mjs";

const fingerprint = "a".repeat(64);
const wasmFiles = ["jazz_wasm_bg.wasm", "jazz_wasm_bg.wasm.d.ts", "jazz_wasm.d.ts", "jazz_wasm.js"];
const repositoryRoot = resolve(import.meta.dirname, "../..");

test("NAPI staging script parses as the executable CI runs", () => {
  execFileSync(process.execPath, [
    "--check",
    join(repositoryRoot, "dev/artifacts/stage-napi-loader.mjs"),
  ]);
});

test("release workflow uploads the sealed WASM provenance manifest", () => {
  const workflow = readFileSync(
    join(repositoryRoot, ".github/workflows/build-jazz-packages.yml"),
    "utf8",
  );
  const wasmUpload = workflow.match(/name: jazz-wasm-pkg[\s\S]*?if-no-files-found: error/)?.[0];
  assert.ok(wasmUpload, "missing jazz-wasm package artifact upload");
  assert.match(wasmUpload, /path: crates\/jazz-wasm\/pkg/);
  assert.match(wasmUpload, /include-hidden-files: true/);
});

test("release workflow does not carry a local NAPI generation pointer into package assembly", () => {
  const workflow = readFileSync(
    join(repositoryRoot, ".github/workflows/build-jazz-packages.yml"),
    "utf8",
  );
  const loaderUpload = workflow.match(
    /name: jazz-napi-loader[\s\S]*?if-no-files-found: error/,
  )?.[0];
  assert.ok(loaderUpload, "missing jazz-napi loader artifact upload");
  assert.doesNotMatch(loaderUpload, /crates\/jazz-napi\/native-binding\.pointer\.cjs/);
  assert.match(loaderUpload, /crates\/jazz-napi\/native-loader\.provenance\.json/);
});

const napiPlatformTargets = {
  "linux-x64-gnu": "x86_64-unknown-linux-gnu",
  "darwin-x64": "x86_64-apple-darwin",
  "darwin-arm64": "aarch64-apple-darwin",
};

function writeAssembledNapiLoader(
  root,
  {
    loader = true,
    fingerprintReceipt = true,
    fingerprintValue = fingerprint,
    platforms = ["linux-x64-gnu"],
  } = {},
) {
  const packageDir = join(root, "crates/jazz-napi");
  if (loader)
    writeFileSync(
      join(packageDir, "native-loader.cjs"),
      "/* auto-generated by NAPI-RS */\nmodule.exports = {};\n",
    );
  if (fingerprintReceipt)
    writeFileSync(
      join(packageDir, "native-artifact-fingerprint.cjs"),
      `module.exports = { expectedNativeArtifactFingerprint: ${JSON.stringify(fingerprintValue)} };\n`,
    );
  const loaderBytes = "/* auto-generated by NAPI-RS */\nmodule.exports = {};\n";
  writeFileSync(
    join(packageDir, "native-loader.provenance.json"),
    JSON.stringify({
      schema: 1,
      kind: "napi-loader",
      profile: "release",
      nativeArtifactFingerprint: fingerprintValue,
      artifacts: [
        {
          file: "native-loader.cjs",
          sha256: createHash("sha256").update(loaderBytes).digest("hex"),
        },
      ],
    }),
  );
  for (const platform of platforms) {
    const target = napiPlatformTargets[platform];
    if (!target) throw new Error(`test fixture lacks target for ${platform}`);
    const provenanceDir = join(packageDir, "provenance");
    mkdirSync(provenanceDir, { recursive: true });
    writeFileSync(
      join(provenanceDir, `jazz-napi.${platform}.manifest.json`),
      JSON.stringify({
        kind: "napi",
        profile: "release",
        target,
        nativeArtifactFingerprint: fingerprintValue,
      }),
    );
  }
}

test("assembled NAPI package prepack preserves its downloaded loader without a local generation", () => {
  const root = releaseFixture();
  const packageDir = join(root, "crates/jazz-napi");
  writeAssembledNapiLoader(root);
  stageNapiLoader(root, "linux-x64-gnu");
  assert.equal(existsSync(join(packageDir, "native-binding.pointer.cjs")), false);
});

test("assembled NAPI package accepts a matching receipt across multiple staged targets", () => {
  const root = releaseFixture();
  writeAssembledNapiLoader(root, { platforms: ["linux-x64-gnu", "darwin-x64", "darwin-arm64"] });
  stageNapiLoader(root, "linux-x64-gnu");
});

test("assembled NAPI package prepack rejects missing loader receipts and stale local pointers", () => {
  const missingLoader = releaseFixture();
  writeAssembledNapiLoader(missingLoader, { loader: false });
  assert.throws(
    () => stageNapiLoader(missingLoader, "linux-x64-gnu"),
    /missing generated native loader/,
  );

  const stalePointer = releaseFixture();
  writeAssembledNapiLoader(stalePointer);
  writeFileSync(
    join(stalePointer, "crates/jazz-napi/native-binding.pointer.cjs"),
    `const nativeBinding = require("./.native-artifacts/generation-missing/index.js");\nmodule.exports = { nativeBinding, expectedNativeArtifactFingerprint: "${fingerprint}" };\n`,
  );
  assert.throws(
    () => stageNapiLoader(stalePointer, "linux-x64-gnu"),
    /active NAPI generation must be a real directory/,
  );
});

test("assembled NAPI package prepack rejects loader and fingerprint tampering that preserve markers", () => {
  const loaderTamper = releaseFixture();
  writeAssembledNapiLoader(loaderTamper);
  writeFileSync(
    join(loaderTamper, "crates/jazz-napi/native-loader.cjs"),
    "/* auto-generated by NAPI-RS */\nmodule.exports = { compromised: true };\n",
  );
  assert.throws(
    () => stageNapiLoader(loaderTamper, "linux-x64-gnu"),
    /native loader hash disagrees with sealed provenance/,
  );

  const fingerprintTamper = releaseFixture();
  writeAssembledNapiLoader(fingerprintTamper);
  writeFileSync(
    join(fingerprintTamper, "crates/jazz-napi/native-artifact-fingerprint.cjs"),
    `module.exports = { expectedNativeArtifactFingerprint: ${JSON.stringify("b".repeat(64))} };\n`,
  );
  assert.throws(
    () => stageNapiLoader(fingerprintTamper, "linux-x64-gnu"),
    /fingerprint receipt disagrees with sealed native loader provenance/,
  );
});

test("assembled NAPI package prepack rejects a self-consistent loader receipt replayed with another platform provenance", () => {
  const root = releaseFixture();
  writeAssembledNapiLoader(root);
  writeFileSync(
    join(root, "crates/jazz-napi/provenance/jazz-napi.linux-x64-gnu.manifest.json"),
    JSON.stringify({
      kind: "napi",
      profile: "release",
      target: "x86_64-unknown-linux-gnu",
      nativeArtifactFingerprint: "b".repeat(64),
    }),
  );
  assert.throws(
    () => stageNapiLoader(root, "linux-x64-gnu"),
    /loader provenance disagrees with selected platform manifest/,
  );
});

function releaseFixture() {
  const root = mkdtempSync(join(tmpdir(), "jazz-release-staging-"));
  for (const path of [
    "crates/jazz-napi/.native-artifacts/generation-test",
    "crates/jazz-wasm/pkg",
    "crates/jazz-napi/provenance",
    "packages/jazz-tools/src/runtime",
  ])
    mkdirSync(join(root, path), { recursive: true });
  return root;
}

function writeWasmRelease(root, { artifacts = undefined } = {}) {
  const wasmDir = join(root, "crates/jazz-wasm/pkg");
  const generated = wasmFiles.map((file) => {
    const bytes = `expected ${file}`;
    writeFileSync(join(wasmDir, file), bytes);
    return { file, sha256: createHash("sha256").update(bytes).digest("hex") };
  });
  writeFileSync(
    join(wasmDir, ".jazz-artifact-manifest.json"),
    JSON.stringify({
      kind: "wasm",
      profile: "release",
      nativeArtifactFingerprint: fingerprint,
      artifacts: artifacts ?? generated,
    }),
  );
}

function writeReleaseNapiManifest(root) {
  writeFileSync(
    join(root, "crates/jazz-napi/provenance/jazz-napi.linux-x64-gnu.manifest.json"),
    JSON.stringify({ kind: "napi", profile: "release", nativeArtifactFingerprint: fingerprint }),
  );
}

test("release NAPI staging rejects a valid sealed manifest whose fingerprint disagrees with the pointer", () => {
  const root = releaseFixture();
  const packageDir = join(root, "crates/jazz-napi");
  const generation = join(packageDir, ".native-artifacts/generation-test");
  writeFileSync(
    join(packageDir, "native-binding.pointer.cjs"),
    `const nativeBinding = require("./.native-artifacts/generation-test/index.js");\nmodule.exports = { nativeBinding, expectedNativeArtifactFingerprint: "${fingerprint}" };\n`,
  );
  writeFileSync(join(generation, "jazz-napi.linux-x64-gnu.node"), "native bytes");
  writeFileSync(join(generation, "index.js"), "module.exports = {};\n");
  writeFileSync(
    join(generation, ".jazz-artifact-manifest.json"),
    JSON.stringify({ kind: "napi", profile: "release", nativeArtifactFingerprint: "b".repeat(64) }),
  );

  assert.throws(
    () => stageNapiLoader(root, "linux-x64-gnu"),
    /pointer fingerprint does not match its sealed manifest/,
  );
  assert.equal(
    readFileSync(join(packageDir, "native-binding.pointer.cjs"), "utf8").includes(fingerprint),
    true,
  );
});

test("release NAPI staging rejects a symlinked active native binding", () => {
  const root = releaseFixture();
  const packageDir = join(root, "crates/jazz-napi");
  const generation = join(packageDir, ".native-artifacts/generation-test");
  writeFileSync(
    join(packageDir, "native-binding.pointer.cjs"),
    `const nativeBinding = require("./.native-artifacts/generation-test/index.js");\nmodule.exports = { nativeBinding, expectedNativeArtifactFingerprint: "${fingerprint}" };\n`,
  );
  const outside = join(root, "outside.node");
  writeFileSync(outside, "outside native bytes");
  symlinkSync(outside, join(generation, "jazz-napi.linux-x64-gnu.node"));
  writeFileSync(join(generation, "index.js"), "module.exports = {};\n");
  writeFileSync(
    join(generation, ".jazz-artifact-manifest.json"),
    JSON.stringify({ kind: "napi", profile: "release", nativeArtifactFingerprint: fingerprint }),
  );
  assert.throws(() => stageNapiLoader(root, "linux-x64-gnu"), /real regular file/);
});

test("release fingerprint staging verifies downloaded WASM bytes before deriving expectations", () => {
  const root = releaseFixture();
  const wasmDir = join(root, "crates/jazz-wasm/pkg");
  const wasm = join(wasmDir, "jazz_wasm_bg.wasm");
  writeWasmRelease(root);
  writeReleaseNapiManifest(root);

  stageNativeFingerprints(root);
  const generatedNapi = readFileSync(
    join(root, "packages/jazz-tools/src/runtime/native-artifact-fingerprint-napi.ts"),
    "utf8",
  );
  const generatedWasm = readFileSync(
    join(root, "packages/jazz-tools/src/runtime/native-artifact-fingerprint-wasm.ts"),
    "utf8",
  );
  stageNativeFingerprints(root);
  assert.equal(
    readFileSync(
      join(root, "packages/jazz-tools/src/runtime/native-artifact-fingerprint-napi.ts"),
      "utf8",
    ),
    generatedNapi,
  );
  assert.equal(
    readFileSync(
      join(root, "packages/jazz-tools/src/runtime/native-artifact-fingerprint-wasm.ts"),
      "utf8",
    ),
    generatedWasm,
  );
  assert.match(
    readFileSync(
      join(root, "packages/jazz-tools/src/runtime/native-artifact-fingerprint-wasm.ts"),
      "utf8",
    ),
    new RegExp(fingerprint),
  );
  writeFileSync(wasm, "tampered bytes");
  assert.throws(() => stageNativeFingerprints(root), /downloaded WASM artifact hash mismatch/);
});

test("release fingerprint staging rejects omitted, duplicate, empty, and malformed WASM artifact entries", () => {
  const cases = [
    { name: "omitted", artifacts: [], expected: /list each generated artifact exactly once/ },
    {
      name: "duplicate",
      artifacts: wasmFiles.map((file, index) => ({
        file: index === 3 ? wasmFiles[0] : file,
        sha256: "a".repeat(64),
      })),
      expected: /list each generated artifact exactly once/,
    },
    {
      name: "empty",
      artifacts: wasmFiles.map((file) => ({ file, sha256: "" })),
      expected: /artifact hash mismatch/,
    },
    {
      name: "malformed",
      artifacts: wasmFiles.map((file) => ({ file, sha256: "not-a-hash" })),
      expected: /artifact hash mismatch/,
    },
  ];
  for (const { name, artifacts, expected } of cases) {
    const root = releaseFixture();
    writeWasmRelease(root, { artifacts });
    writeReleaseNapiManifest(root);
    assert.throws(() => stageNativeFingerprints(root), expected, name);
  }
});

test("release publishing rebuilds when workflow changes invalidate preview artifacts", () => {
  const workflow = readFileSync(
    new URL("../../.github/workflows/publish-jazz-tools-alpha.yml", import.meta.url),
    "utf8",
  );

  assert.match(
    workflow,
    /if \(!treeReuseSafe\) \{\s+reason = `main tree \$\{currentTree\} differs from release PR head tree \$\{previewTree\}`;/,
  );
  assert.doesNotMatch(workflow, /workflow-only drift|nonWorkflowFiles/);
});
