// Generated by uniffi-bindgen-react-native
#include "cojson-core-rn.h"
#include "generated/cojson_core_rn.hpp"

namespace cojsoncorern {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeCojsonCoreRn::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}