// Auto generated by Craby. DO NOT EDIT.
#include "CxxCojsonCoreRnModule.hpp"
#include "cxx.h"
#include "bridging-generated.hpp"
#include <react/bridging/Bridging.h>

using namespace facebook;

namespace craby {
namespace cojsoncorern {
namespace modules {

std::string CxxCojsonCoreRnModule::dataPath = std::string();

CxxCojsonCoreRnModule::CxxCojsonCoreRnModule(
    std::shared_ptr<react::CallInvoker> jsInvoker)
    : TurboModule(CxxCojsonCoreRnModule::kModuleName, jsInvoker) {
  // No signals
  callInvoker_ = std::move(jsInvoker);
  module_ = std::shared_ptr<craby::cojsoncorern::bridging::CojsonCoreRn>(
    craby::cojsoncorern::bridging::createCojsonCoreRn(
      reinterpret_cast<uintptr_t>(this),
      rust::Str(dataPath.data(), dataPath.size())).into_raw(),
    [](craby::cojsoncorern::bridging::CojsonCoreRn *ptr) { rust::Box<craby::cojsoncorern::bridging::CojsonCoreRn>::from_raw(ptr); }
  );
  threadPool_ = std::make_shared<craby::cojsoncorern::utils::ThreadPool>(10);
  methodMap_["add"] = MethodMetadata{2, &CxxCojsonCoreRnModule::add};
  methodMap_["divide"] = MethodMetadata{2, &CxxCojsonCoreRnModule::divide};
  methodMap_["multiply"] = MethodMetadata{2, &CxxCojsonCoreRnModule::multiply};
  methodMap_["subtract"] = MethodMetadata{2, &CxxCojsonCoreRnModule::subtract};
}

CxxCojsonCoreRnModule::~CxxCojsonCoreRnModule() {
  invalidate();
}

void CxxCojsonCoreRnModule::invalidate() {
  if (invalidated_.exchange(true)) {
    return;
  }

  invalidated_.store(true);
  listenersMap_.clear();

  // No signals

  // Shutdown thread pool
  threadPool_->shutdown();
}

jsi::Value CxxCojsonCoreRnModule::add(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxCojsonCoreRnModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<double>(rt, args[1], callInvoker);
    auto ret = craby::cojsoncorern::bridging::add(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::cojsoncorern::utils::errorMessage(err));
  }
}

jsi::Value CxxCojsonCoreRnModule::divide(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxCojsonCoreRnModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<double>(rt, args[1], callInvoker);
    auto ret = craby::cojsoncorern::bridging::divide(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::cojsoncorern::utils::errorMessage(err));
  }
}

jsi::Value CxxCojsonCoreRnModule::multiply(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxCojsonCoreRnModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<double>(rt, args[1], callInvoker);
    auto ret = craby::cojsoncorern::bridging::multiply(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::cojsoncorern::utils::errorMessage(err));
  }
}

jsi::Value CxxCojsonCoreRnModule::subtract(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxCojsonCoreRnModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<double>(rt, args[1], callInvoker);
    auto ret = craby::cojsoncorern::bridging::subtract(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::cojsoncorern::utils::errorMessage(err));
  }
}

} // namespace modules
} // namespace cojsoncorern
} // namespace craby
