[package]
name = "jazz-example-music-agent-benchmark"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
jazz = { workspace = true, features = ["testing"] }
groove = { workspace = true, features = ["test"] }

[dev-dependencies]
divan = { workspace = true }

[[bench]]
name = "loads"
harness = false
