[package]
name = "jazz-storage-rocksdb"
version = "0.1.0"
edition = "2024"

[dependencies]
groove.workspace = true
rocksdb = { package = "rust-rocksdb", version = "0.48.0", default-features = false, features = [
  "lz4",
  "zstd",
] }
serde = { version = "1.0.228", features = ["derive"] }

[dev-dependencies]
groove = { workspace = true, features = ["test"] }
base64 = "0.22"
flate2 = "1"
tempfile = "3.27.0"
futures-test = "0.3"
jazz-benchmark-guard = { path = "../benchmark-guard" }
serde_json = "1"
sha2 = "0.10"
tar = "0.4"
