name: Build Examples

on:
  push:
    branches: [ "main" ]

jobs:
  build-examples:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    strategy:
      matrix:
        example: [
          "chat",
          "clerk",
          "passkey",
          "inspector",
          "music-player",
          "password-manager",
          "pets",
          "reactions",
          "todo",
          "onboarding",
        ]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup Source Code
      uses: ./.github/actions/source-code/

    - name: Pnpm Build
      run: |
        pnpm install
        pnpm turbo build;
      working-directory: ./examples/${{ matrix.example }}
