name: Code quality

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci .

      - name: Check Catalog Dependencies
        run: node scripts/check-catalog-deps.js
