name: Jazz Run Tests

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Source Code
        uses: ./.github/actions/source-code/

      - name: Build jazz-run
        run: pnpm exec turbo build && chmod +x dist/index.js;
        working-directory: ./packages/jazz-run

      - name: Run create account
        run: ./dist/index.js account create --name "Jazz Run CI test"
        working-directory: ./packages/jazz-run
