name: Playwright Tests

concurrency:
  # For pushes, this lets concurrent runs happen, so each push gets a result.
  # But for other events (e.g. PRs), we can cancel the previous runs.
  group: ${{ github.workflow }}-${{ github.event_name == 'push' && github.sha || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    timeout-minutes: 60
    runs-on: blacksmith-4vcpu-ubuntu-2404
    continue-on-error: true
    strategy:
      matrix:
        project: [
          "tests/e2e",
          "examples/chat",
          "examples/chat-svelte",
          "examples/clerk",
          "examples/betterauth",
          "examples/file-share-svelte",
          "examples/form",
          "examples/inspector",
          "examples/music-player",
          "examples/organization",
          "examples/tanstack-form",
          "starters/react-passkey-auth",
          "starters/svelte-passkey-auth",
          "tests/jazz-svelte"
        ]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Source Code
        uses: ./.github/actions/source-code/

      - name: Pnpm Build
        run: |
          if [ -f .env.test ]; then
            cp .env.test .env
          fi
          pnpm turbo build
        working-directory: ./${{ matrix.project }}

      - name: Install Playwright Browsers
        run: pnpm exec playwright install
        working-directory: ./${{ matrix.project }}

      - name: Run Playwright tests
        run: pnpm exec playwright test
        working-directory: ./${{ matrix.project }}

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ${{ hashFiles(format('{0}/package.json', matrix.project)) }}-playwright-report
          path: ./${{ matrix.project }}/playwright-report/
          retention-days: 30
