name: Pre-Publish tagged Pull Requests
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pre-release:
    if: contains(github.event.pull_request.labels.*.name, 'pre-release')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Source Code
        uses: ./.github/actions/source-code/

      - name: Pnpm Build
        run: pnpm turbo build --filter="./packages/*"

      - name: Pre publish
        run: pnpm exec pkg-pr-new publish "./packages/*"
