name: Unit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - 'main'

jobs:
  unit-tests:
    runs-on: blacksmith-4vcpu-ubuntu-2204

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Source Code
        uses: ./.github/actions/source-code/

      - name: Pnpm Build
        run: pnpm turbo build --filter="./packages/*"

      - name: Install Playwright Browsers
        run: pnpm exec playwright install

      - name: Unit Tests
        run: pnpm test:ci
