name: Unit Tests

concurrency:
  # For pushes, this lets concurrent runs happen, so each push gets a result.
  # But for other events (e.g. PRs), we can cancel the previous runs.
  group: ${{ github.workflow }}-${{ github.event_name == 'push' && github.sha || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - 'main'

jobs:
  unit-tests:
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Source Code
        uses: ./.github/actions/source-code/

      - name: Pnpm Build
        run: pnpm turbo build --filter="./packages/*"

      - name: Build NAPI packages
        run: pnpm exec turbo run build:napi --filter='./crates/*'

      - name: Install Playwright Browsers
        run: pnpm exec playwright install

      - name: Unit Tests
        run: pnpm test:ci
